(function(g){var window=this;/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var F0=function(a){a.X("cardstatechange",a.Oh()&&a.Ll()?1:0)},G0=function(a,b){var c=g.Ma(b),d=c?b:arguments;
for(c=c?0:1;c<d.length;c++){if(null==a)return;a=a[d[c]]}return a},RTa=function(a){var b=g.Cm(a);
a=g.Fm(a);return new g.rm(b.x,b.y,a.width,a.height)},STa=function(a){return Math.pow(a,3)},TTa=function(a){return 3*a*a-2*a*a*a},J0=function(a){a=g.Qa(a);
delete H0[a];g.Qf(H0)&&I0&&I0.stop()},VTa=function(){I0||(I0=new g.L(function(){UTa()},20));
var a=I0;a.isActive()||a.start()},UTa=function(){var a=g.Ta();
g.Bf(H0,function(b){WTa(b,a)});
g.Qf(H0)||VTa()},K0=function(a,b,c,d){g.Ap.call(this);
if(!Array.isArray(a)||!Array.isArray(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.u=a;this.N=b;this.duration=c;this.I=d;this.coords=[];this.progress=this.J=0;this.D=null},WTa=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.J=1E3/(b-a.D);a.D=b;XTa(a,a.progress);1==a.progress?(a.j=0,J0(a),a.onFinish(),a.Oy()):a.Lc()&&a.yE()},XTa=function(a,b){"function"===typeof a.I&&(b=a.I(b));
a.coords=Array(a.u.length);for(var c=0;c<a.u.length;c++)a.coords[c]=(a.N[c]-a.u[c])*b+a.u[c]},YTa=function(a,b){g.rf.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.J;this.state=b.j},L0=function(a,b,c,d,e){K0.call(this,b,c,d,e);
this.element=a},M0=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
L0.call(this,a,b,c,d,e)},N0=function(a){g.G.call(this);
this.u=a||window;this.j=[]},O0=function(a){return a.baseUrl||null},P0=function(a,b){return g.sn(g.Bl(a,b),function(c){return!!c})},ZTa=function(a,b,c){function d(Xa){var Pa=Xa.hovercardButton;
if(!Pa)return null;Pa=Pa.subscribeButtonRenderer;if(!Pa)return null;var Ob=f(Pa.unsubscribedButtonText),Db=f(Pa.subscribedButtonText);if(Pa.subscribed){var zc=f(Pa.subscriberCountWithUnsubscribeText);var Sc=f(Pa.subscriberCountText)}else zc=f(Pa.subscriberCountText),Sc=f(Pa.subscriberCountWithSubscribeText);var hd=null;if(Xa.signinEndpoint){hd=G0(Xa,"signinEndpoint","webNavigationEndpointData","url");if(!hd){var je,Kf,jf;hd=null==(je=Pa.signInEndpoint)?void 0:null==(Kf=je.commandMetadata)?void 0:
null==(jf=Kf.webCommandMetadata)?void 0:jf.url}if(!hd)return null}return Ob&&(Db||hd)?{subscribed:Pa.subscribed,subscribeText:Ob,subscribeCount:zc,unsubscribeText:Db,unsubscribeCount:Sc,enabled:Pa.enabled,signinUrl:hd,classic:Xa.useClassicSubscribeButton}:null}
function e(Xa){if(Xa){var Pa=[],Ob=Xa.videoId;Ob&&Pa.push("v="+Ob);(Ob=Xa.playlistId)&&Pa.push("list="+Ob);(Xa=Xa.startTimeSeconds)&&Pa.push("t="+Xa);return"/watch?"+Pa.join("&")}}
function f(Xa){if(!Xa)return null;var Pa=Xa.simpleText;return Pa?Pa:Xa.runs?g.Bl(Xa.runs,function(Ob){return Ob.text}).join(""):null}
b=b.endscreenElementRenderer;if(!b)return null;var k=b.style,l=b.endpoint||{},m=null,n=null,p=!1,q=null,t=null,v=null,x=null,y=!1,z=null,E=null,J=null,I=null,M=null,da=null;if("VIDEO"===k)l.urlEndpoint?m=l.urlEndpoint.url:(da=l.watchEndpoint,m=e(da)),n=!1,q=a,b.thumbnailOverlays?(p=b.thumbnailOverlays[0].thumbnailOverlayTimeStatusRenderer,t=f(p.text),p="LIVE"===p.style):t=f(b.videoDuration);else if("PLAYLIST"===k)l.urlEndpoint?m=l.urlEndpoint.url:(da=l.watchEndpoint,m=e(da)),n=!1,q=a,v=f(b.playlistLength);
else if("CHANNEL"===k){if(y=G0(l,"browseEndpoint","browseId"))x=y,m="/channel/"+x;n=!1;q="new";(y=!!b.isSubscribe)?z=d(b):E=f(b.subscribersText)}else"WEBSITE"===k?((J=G0(l,"urlEndpoint","url"))&&(m=J),n=!0,q="new",J=b.icon.thumbnails[0].url):"CREATOR_MERCHANDISE"===k&&(b.productPrice&&(I=f(b.productPrice)),b.additionalFeesText&&(M=f(b.additionalFeesText)),(n=G0(l,"urlEndpoint","url"))&&(m=n),n=!0,q="new");a=G0(b,"title","accessibility","accessibilityData","label");var K=b.endpoint?b.endpoint.clickTrackingParams:
null,pa="";if(b.metadata){var za=f(b.metadata);za&&(pa=za)}return{id:"element-"+c,type:k,title:f(b.title),metadata:pa,callToAction:f(b.callToAction),cN:b.image,iconUrl:J,left:Number(b.left),width:Number(b.width),top:Number(b.top),aspectRatio:Number(b.aspectRatio),startMs:Math.floor(Number(b.startMs)),endMs:Math.floor(Number(b.endMs)),videoDuration:t,isLiveVideo:p,playlistLength:v,channelId:x,subscribeButton:z,subscribersText:E,isSubscribe:y,targetUrl:m||null,IW:n,sessionData:K?{itct:K}:null,r0:q,
Ww:a?a:null,isPlaceholder:b.isPlaceholder,impressionUrls:P0(b.impressionUrls||[],O0),vW:P0(b.hovercardShowUrls||[],O0),clickUrls:P0(l.loggingUrls||[],O0),visualElement:g.xv(b.trackingParams),productPrice:I,additionalFeesText:M,watchEndpoint:da||null}},Q0=function(a,b){var c={startMs:Math.floor(Number(a.startMs)),
impressionUrls:P0(a.impressionUrls||[],O0),elements:P0(a.elements||[],function(d,e){return ZTa(b,d,e)})};
a.trackingParams&&(c.visualElement=g.xv(a.trackingParams));return c},R0=function(a){g.CJ.call(this,a);
this.B=this.endscreen=null;this.j={};this.D={};this.C=this.u=null;this.J=[];this.V=!0;this.I=0;a=a.S();this.N=g.dC(a)||g.hC(a);this.events=new g.Uz(this);g.H(this,this.events);this.events.P(this.player,g.vw("creatorendscreen"),this.onCueRangeEnter);this.events.P(this.player,g.ww("creatorendscreen"),this.onCueRangeExit);this.events.P(this.player,"resize",this.ub);this.events.P(window,"focus",this.n_);this.load();var b=g.Oh("STYLE");(g.Gh("HEAD")[0]||document.body).appendChild(b);g.qf(this,function(){g.Th(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},$Ta=function(a){return a.player.getVideoData().D?"current":a.N?"new":"current"},S0=function(a){return"creator-endscreen-editor"===a.player.S().playerStyle},aUa=function(a){var b=a.player.getVideoData(),c=b.videoId;
a.B&&a.B.abort();c={method:"POST",onFinish:function(e){var f=a.B=null;200===e.status&&(e=e.responseText,")]}"===e.substring(0,3)&&(e=e.substring(3),f=JSON.parse(e),f=Q0(f,$Ta(a))));T0(a,f)},
urlParams:{v:c},withCredentials:!0};a.N&&(c.urlParams.ptype="embedded");var d=b.Iq;d&&(c.postParams={ad_tracking:d});if(b=g.xwa(b))if(b=g.Sg(b),b=g.Og(b))a.B=g.ir(b,c)},T0=function(a,b,c){c=void 0===c?!0:c;
a.player.Kf("creatorendscreen");a.u&&(a.u.dispose(),a.u=null,a.C.dispose(),a.C=null);for(var d=g.r(Object.values(a.j)),e=d.next();!e.done;e=d.next())e.value.dispose();a.j={};a.D={};0<a.J.length&&(a.J.forEach(function(l){l.dispose()}),a.J.length=0);
a.I=0;if((a.endscreen=b)&&b.elements){c&&bUa(a);c=[];d=new g.tw(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);a.player.S().isMobile||(a.u=new g.W({F:"div",K:"ytp-ce-shadow"}),g.oJ(a.player,a.u.element,4),a.C=new g.sH(a.u,200));for(d=0;d<b.elements.length;++d){e=b.elements[d];var f=cUa(a,e);if(f){a.j[e.id]=f;a.D[e.id]=e;g.oJ(a.player,f.element,4);var k=new g.tw(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(k);dUa(a,
f,e)}else g.uv(new g.us("buildEndscreenElement null",e))}a.player.Yd(c);a.ub()}},bUa=function(a){var b=g.Dv(),c=g.Ev();
c&&b&&a.endscreen.visualElement&&g.Iv(void 0,c,b,[a.endscreen.visualElement])},cUa=function(a,b){var c=null;
switch(b.type){case "VIDEO":a={F:"div",Ba:["ytp-ce-element","ytp-ce-video"],T:{tabindex:"0","aria-label":b.Ww||"","aria-hidden":"true"},R:[{F:"div",K:"ytp-ce-element-shadow"},{F:"div",K:"ytp-ce-covering-image",T:U0(b)},{F:"div",K:"ytp-ce-covering-shadow-top"},{F:"a",K:"ytp-ce-covering-overlay",T:{href:V0(a,b.targetUrl),tabindex:"-1"},R:[{F:"div",Ba:["ytp-ce-video-title","ytp-webkit-ellipsis"],T:{dir:g.Ep(b.title||"")},Z:b.title},{F:"div",K:b.isLiveVideo?"ytp-ce-live-video-duration":"ytp-ce-video-duration",
Z:b.videoDuration||void 0}]}]};c=new g.W(a);break;case "PLAYLIST":a={F:"div",Ba:["ytp-ce-element","ytp-ce-playlist"],T:{tabindex:"0","aria-label":b.Ww||"","aria-hidden":"true"},R:[{F:"div",K:"ytp-ce-element-shadow"},{F:"div",K:"ytp-ce-covering-image",T:U0(b)},{F:"div",K:"ytp-ce-covering-shadow-top"},{F:"a",K:"ytp-ce-covering-overlay",T:{href:V0(a,b.targetUrl),tabindex:"-1"},R:[{F:"div",Ba:["ytp-ce-playlist-title","ytp-webkit-ellipsis"],T:{dir:g.Ep(b.title||"")},Z:b.title},{F:"div",K:"ytp-ce-playlist-count",
R:[{F:"div",K:"ytp-ce-playlist-icon"},{F:"div",K:"ytp-ce-playlist-count-text",Z:b.playlistLength||void 0}]}]}]};c=new g.W(a);break;case "CHANNEL":c={F:"div",Ba:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],T:{tabindex:"0","aria-label":b.Ww||"","aria-hidden":"true"},R:[{F:"div",K:"ytp-ce-element-shadow"},{F:"div",K:"ytp-ce-expanding-overlay",R:[{F:"div",K:"ytp-ce-expanding-overlay-hider"},{F:"div",K:"ytp-ce-expanding-overlay-background"},{F:"div",K:"ytp-ce-expanding-overlay-content",
R:[{F:"div",K:"ytp-ce-expanding-overlay-body",R:[{F:"div",K:"ytp-ce-expanding-overlay-body-padding",R:[{F:"a",Ba:["ytp-ce-channel-title","ytp-ce-link"],T:{href:V0(a,b.targetUrl),target:"_blank",tabindex:"-1",dir:g.Ep(b.title||"")},Z:b.title},b.subscribeButton?{F:"div",K:"ytp-ce-subscribe-container",R:[{F:"div",K:"ytp-ce-channel-subscribe"}]}:"",b.subscribersText?{F:"div",K:"ytp-ce-channel-subscribers-text",Z:b.subscribersText}:"",b.metadata?{F:"div",Ba:["ytp-ce-channel-metadata","yt-ui-ellipsis",
"yt-ui-ellipsis-3"],Z:b.metadata}:""]}]}]}]},{F:"div",K:"ytp-ce-expanding-image",T:U0(b)}]};c=new g.W(c);var d=g.Hh(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton&&b.channelId){g.N(d,"ytp-ce-subscribe-button");if(a.player.S().isMobile){var e=null;var f=b.sessionData.itct}else e="endscreen",f=null;e=new g.TK(b.subscribeButton.subscribeText,b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,!!b.subscribeButton.enabled,
!!b.subscribeButton.classic,b.channelId,!!b.subscribeButton.subscribed,e,f,b.subscribeButton.signinUrl,a.player);d.appendChild(e.element);a.J.push(e)}break;case "WEBSITE":a={F:"div",Ba:["ytp-ce-element","ytp-ce-website"],T:{tabindex:"0","aria-label":b.Ww||"","aria-hidden":"true"},R:[{F:"div",K:"ytp-ce-element-shadow"},{F:"div",K:"ytp-ce-expanding-overlay",R:[{F:"div",K:"ytp-ce-expanding-overlay-hider"},{F:"div",K:"ytp-ce-expanding-overlay-background"},{F:"div",K:"ytp-ce-expanding-overlay-content",
R:[{F:"div",K:"ytp-ce-expanding-overlay-body",R:[{F:"div",K:"ytp-ce-expanding-overlay-body-padding",R:[{F:"div",K:"ytp-ce-website-title",T:{dir:g.Ep(b.title||"")},Z:b.title},{F:"div",K:"ytp-ce-website-metadata",Z:b.metadata},{F:"a",Ba:["ytp-ce-website-goto","ytp-ce-link"],T:{href:V0(a,b.targetUrl),target:"_blank",tabindex:"-1"},Z:b.callToAction}]}]}]}]},{F:"div",K:"ytp-ce-expanding-image",T:U0(b)},{F:"div",K:"ytp-ce-expanding-icon",T:eUa(b.iconUrl)}]};c=new g.W(a);break;case "CREATOR_MERCHANDISE":c=
"",b.productPrice&&(c={F:"div",K:"ytp-ce-merchandise-price-container",R:[{F:"div",K:"ytp-ce-merchandise-price",Z:b.productPrice}]},b.additionalFeesText&&c.R.push({F:"div",K:"ytp-ce-merchandise-additional-fees",Z:b.additionalFeesText})),a={F:"div",Ba:["ytp-ce-element","ytp-ce-merchandise"],T:{tabindex:"0","aria-label":b.Ww||"","aria-hidden":"true"},R:[{F:"div",K:"ytp-ce-element-shadow"},{F:"div",K:"ytp-ce-expanding-overlay",R:[{F:"div",K:"ytp-ce-expanding-overlay-hider"},{F:"div",K:"ytp-ce-expanding-overlay-background"},
{F:"div",K:"ytp-ce-expanding-overlay-content",R:[{F:"div",K:"ytp-ce-expanding-overlay-body",R:[{F:"div",K:"ytp-ce-expanding-overlay-body-padding",R:[{F:"div",K:"ytp-ce-merchandise-title",T:{dir:g.Ep(b.title||"")},Z:b.title},c,{F:"div",K:"ytp-ce-merchandise-metadata",Z:b.metadata},{F:"a",Ba:["ytp-ce-merchandise-goto","ytp-ce-link"],T:{href:V0(a,b.targetUrl),target:"_blank",tabindex:"-1"},Z:b.callToAction}]}]}]}]},{F:"div",K:"ytp-ce-expanding-image",T:U0(b)},{F:"div",K:"ytp-ce-merchandise-invideo-cta-container",
R:[{F:"div",K:"ytp-ce-merchandise-invideo-cta",Z:b.callToAction||void 0}]}]},c=new g.W(a)}b.isPlaceholder&&g.N(c.element,"ytp-ce-placeholder");return c},U0=function(a){if(a.cN)var b=a.cN.thumbnails;
return eUa(b?b[b.length-1].url:null)},eUa=function(a){return a?{style:"background-image: url("+a+")"}:{}},dUa=function(a,b,c){function d(m){m&&(b.Ja("blur",function(){"none"!=m.style.display&&a.V&&m.focus()}),b.P(m,"focus",f),b.P(m,"blur",k))}
function e(m){a.I+=m;0<a.I?(g.N(b.element,"ytp-ce-force-expand"),W0(a,c.id,!0)):(g.rp(b.element,"ytp-ce-force-expand"),g.rp(b.element,"ytp-ce-element-hover"),W0(a,c.id,!1))}
function f(){e(1)}
function k(){e(-1)}
b.Ja("mouseenter",function(){X0(a,b,c)});
b.Ja("mouseleave",function(){Y0(a,b,c)});
a.player.S().isMobile||b.Ja("click",function(){g.N(b.element,"ytp-ce-element-hover")});
b.Ja("click",function(m){fUa(a,c,m)});
b.Ja("keypress",function(m){fUa(a,c,m)});
b.Ja("focus",function(){X0(a,b,c)});
b.Ja("blur",function(){Y0(a,b,c)});
b.Ja("touchstart",function(){X0(a,b,c)});
var l=g.Jh("ytp-ce-expanding-overlay-hider",b.element);l&&b.P(l,"touchstart",function(m){m=m||window.event;m.cancelBubble=!0;m.stopPropagation&&m.stopPropagation();g.rp(b.element,"ytp-ce-element-hover");g.rp(b.element,"ytp-ce-force-expand")});
b.Ja("keydown",function(m){a.V=9===m.keyCode&&!m.shiftKey});
d(g.Jh("ytp-sb-subscribe",b.element));d(g.Jh("ytp-sb-unsubscribe",b.element));b.Ja("focus",f);b.Ja("blur",k)},fUa=function(a,b,c){if(b.targetUrl&&(!c||"keypress"!==c.type||13===c.keyCode)){for(var d=c.target;d&&!g.pp(d,"ytp-ce-element");){g.pp(d,"subscribe-label")&&Z0(a,b);
if(g.pp(d,"ytp-ce-channel-subscribe"))return;d=g.Uh(d)}if(!d||g.pp(d,"ytp-ce-element-hover")){c.preventDefault();c.stopPropagation();if(d=a.j[b.id])Y0(a,d,b),d.element.blur();if(c.ctrlKey||c.metaKey||"new"===b.r0)Z0(a,b),a.player.sendVideoStatsEngageEvent(17,void 0),a.player.pauseVideo(),c=g.Sg(V0(a,b.targetUrl)),g.SH(g.Og(c),void 0,b.sessionData);else{var e=g.xC(a.player.S())||a.player.getVideoData().D,f=function(){var k=V0(a,b.targetUrl),l=b.sessionData,m=b.watchEndpoint,n=g.Vq(k);e&&n&&(n.v||n.list)?
a.player.ll(n.v,l,n.list,!1,void 0,m||void 0):g.RH(k,l)};
Z0(a,b,function(){a.player.sendVideoStatsEngageEvent(17,f)})}}}},V0=function(a,b){a=a.player.S();
if(b){if(b.startsWith("//"))return a.protocol+":"+b;if(b.startsWith("/"))return g.IC(a)+b}else return"";return b},X0=function(a,b,c){g.pp(b.element,"ytp-ce-element-hover")||("VIDEO"===c.type||"PLAYLIST"===c.type?g.N(b.element,"ytp-ce-element-hover"):a.player.S().isMobile?(new g.L(function(){g.N(b.element,"ytp-ce-element-hover")},200)).start():g.N(b.element,"ytp-ce-element-hover"),$0(a,c.vW),W0(a,c.id,!0))},Y0=function(a,b,c){g.rp(b.element,"ytp-ce-element-hover");
g.rp(b.element,"ytp-ce-force-expand");W0(a,c.id,!1)},W0=function(a,b,c){a.u&&(c?a.C.show():a.C.hide());
for(var d=g.r(Object.keys(a.j)),e=d.next();!e.done;e=d.next())e=e.value,e!==b&&g.O(a.j[e].element,"ytp-ce-element-shadow-show",c)},$0=function(a,b,c){function d(){f||(e++,e===b.length&&(k.stop(),c&&c()))}
if(!b||0===b.length||S0(a))c&&c();else{b=gUa(a,b);var e=0,f=!1,k=new g.L(function(){f=!0;c&&c()},1E3,a);
k.start();for(a=0;a<b.length;a++)g.zt(b[a],d)}},Z0=function(a,b,c){$0(a,b.clickUrls,c);
(a=g.Ev())&&b.IW&&g.Ov(a,b.visualElement)},gUa=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce;
a=a.player.getCurrentTime().toFixed(2);c={CPN:c,AD_CPN:c,MT:a};a=[];for(var d=0;d<b.length;d++)a.push(hUa(b[d],c));return a},hUa=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},iUa=function(a){return"string"===typeof a?a:""},a1=function(a,b,c){for(var d in b)if(b[d]===a)return a;
return c},jUa=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.j=d},b1=function(a){return a.value?a.value:null},c1=function(a){if(!a)return null;
var b=g.Sg(iUa(a.value));b=g.Og(b);if(!b)return null;var c=a1(a.target,kUa,"current");if(null==c)a=null;else{var d=a.show_link_icon;a=new jUa(b,c,"true"===d||"false"===d?"true"===d:!0,null!=a.pause_on_navigation?a.pause_on_navigation:!0)}return a},lUa=function(a,b,c){this.type=a;
this.trigger=b;this.url=c},oUa=function(a){if(!a)return null;
var b=a1(a.type,mUa),c=a1(a.trigger,nUa);a=a.url;a=Array.isArray(a)&&a.length?a[0]:a;a=c1(a?a:null);return b?new lUa(b,c,a):null},pUa=function(a,b,c,d,e){this.id=a;
this.type=b;this.style=c;this.data=e;this.action=d||[]},rUa=function(a){return(a=qUa(a,function(b){return"openUrl"===b.type&&null!=b.url}))?a.url:null},qUa=function(a,b){return g.Qb(a.action,b)},sUa=function(a,b){this.context=a;
this.j=b},e1=function(a){return a.customMessage?d1("div","iv-card-message",a.customMessage):""},f1=function(a,b){a="background-image: url("+a+");";
var c=[];b&&c.push(b);return{F:"div",K:"iv-card-image",T:{style:a},R:c}},g1=function(a){if(!a.metaInfo||0===a.metaInfo.length)return"";
var b=[];a=g.r(a.metaInfo);for(var c=a.next();!c.done;c=a.next())b.push(d1("li","",c.value));return{F:"ul",K:"iv-card-meta-info",R:b}},d1=function(a,b,c){b?"string"===typeof b?b={"class":b}:Array.isArray(b)&&(b={"class":b.join(" ")}):b={};
b.dir=g.Ep(c);return{F:a,T:b,Z:c}},tUa=function(a){if(!a.customMessage)return"";
var b=["iv-card-action","iv-card-primary-link"],c={};a.hx&&(b.push("iv-card-action-icon"),c.style="background-image: url("+a.hx+");");c.dir=g.Ep(a.customMessage);var d=[{F:"span",Z:a.customMessage}];a.showLinkIcon&&(d.push("\u00a0"),d.push({F:"span",K:"iv-card-link-icon"}));return{F:"div",Ba:b,T:c,R:d}},h1=function(a,b,c,d){if(d){b=g.r(b);
for(var e=b.next();!e.done;e=b.next())a.j(e.value,d,c.id,c.sessionData,c.tracking.click,5)}},uUa=function(a,b){this.merchant=a;
this.price=b},vUa=function(a){var b;
(b=a)&&!(b=1<a.length?"/"===a.charAt(0)&&"/"!==a.charAt(1):"/"===a)&&(b=a.replace(/^(https?:)?\/\//,""),b=b.split("/",1),b=!b||1>b.length||!b[0]?[]:b[0].toLowerCase().split(".").reverse(),b="com"===b[0]&&"youtube"===b[1]||"be"===b[0]&&"youtu"===b[1]);return b?-1===a.indexOf("/redirect?"):!1},wUa=function(a,b){return b?b:vUa(a)?"current":"new"},i1=function(a,b){g.G.call(this);
var c=this;this.element=a;this.context=b;this.gb=!1;this.Ra=new Map;this.Ta=new Map;this.context.G.addEventListener(g.vw("annotations_module"),function(d){(d=c.Ra.get(d))&&d.apply(c)});
this.context.G.addEventListener(g.ww("annotations_module"),function(d){(d=c.Ta.get(d))&&d.apply(c)})},j1=function(a,b,c,d,e,f,k){a.context.j.Ja(b,"click",function(l){a.zE(c,d,e,f||[],k||0,l)});
a.context.j.Ja(b,"touchstart",function(){a.gb=!1});
a.context.j.Ja(b,"touchmove",function(){a.gb=!0})},xUa=function(a){if(a.urlEndpoint&&a.urlEndpoint.url)return a.urlEndpoint.url;
if(a.watchEndpoint&&a.watchEndpoint.videoId){var b="/watch?v="+a.watchEndpoint.videoId;a.watchEndpoint.playlistId&&(b+="&list="+a.watchEndpoint.playlistId);a.watchEndpoint.index&&(b+="&index="+a.watchEndpoint.index);a.watchEndpoint.startTimeSeconds&&(b+="&t="+a.watchEndpoint.startTimeSeconds);return b}return null},k1=function(a,b,c){return{impression:(a.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
click:(c.loggingUrls||[]).map(function(d){return d.baseUrl||""}),
close:(b.dismissLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
oR:(b.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
nD:(b.clickLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""})}},n1=function(a,b,c){i1.call(this,b,c);
var d=this;this.G=a;this.eventId=null;this.Ia=this.Gb=this.B=this.isInitialized=!1;this.ma=null;this.cards=[];this.ib=this.N=this.Fa=this.D=this.Qa=this.j=null;this.W=[];this.Y=this.J=this.df=this.Da=null;this.I=0;this.va=new g.L(function(){},c.U.Ne?4E3:3E3);
g.H(this,this.va);this.eb=new g.L(function(){});
g.H(this,this.eb);this.oa=new sUa(c,function(e,f,k,l,m,n){j1(d,e,f,k,l,m,n)});
this.V=new g.W({F:"div",K:"iv-drawer",T:{id:"iv-drawer"},R:[{F:"div",K:"iv-drawer-header",T:{"aria-role":"heading"},R:[{F:"span",K:"iv-drawer-header-text"},{F:"button",Ba:["iv-drawer-close-button","ytp-button"],T:{"aria-label":"Hide cards",tabindex:"0"}}]},{F:"div",K:"iv-drawer-content"}]});g.H(this,this.V);this.C=this.V.element;this.Za=new g.sH(this.V,330);g.H(this,this.Za);this.Fb=g.Jh("iv-drawer-header-text",this.C);this.u=g.Jh("iv-drawer-content",this.C);this.addCueRange(0,1E3*c.videoData.lengthSeconds,
"",function(){d.Gb&&l1(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.Gb=d.B)&&m1(d)});
this.G.addEventListener("videodatachange",this.Ap.bind(this))},yUa=function(a,b){b=b.data;
b.autoOpenMs&&a.addCueRange(b.autoOpenMs,0x8000000000000,"",function(){l1(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.autoCloseMs&&a.addCueRange(b.autoCloseMs,0x8000000000000,"",function(){m1(a)});
var c=b.headerText;g.Wh(a.Fb,c);a.N&&a.N.setAttribute("title",c);b.eventId&&(a.eventId=b.eventId);a.Da=g.xv(b.trackingParams);a.J=g.xv(b.closeTrackingParams);a.df=g.xv(b.iconTrackingParams)},zUa=function(a,b){var c=b.cardId?b.cardId:"cr:"+a.I,d=a.G.S().experiments.fb("enable_error_corrections_infocard");
if(!b.content&&b.teaser.simpleCardTeaserRenderer&&d){d=b.teaser.simpleCardTeaserRenderer;var e=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"simple",teaserText:g.Aw(d.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:{},sponsored:!1,tracking:{},Ml:null,cj:d.trackingParams?g.xv(d.trackingParams):null,df:e&&e.trackingParams?g.xv(e.trackingParams):null,imageUrl:"",displayDomain:null,
showLinkIcon:!1,hx:null,title:"",customMessage:"",url:null,onClickCommand:d.onTapCommand||null};o1(a,b)}else if(b.content.simpleCardContentRenderer){if(!b.cueRanges.length)return;d=b.content.simpleCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;var f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"simple",teaserText:g.Aw(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:p1(a,
c,b,d),sponsored:!1,tracking:k1(d,e,d.command),Ml:d.trackingParams?g.xv(d.trackingParams):null,cj:e.trackingParams?g.xv(e.trackingParams):null,df:f&&f.trackingParams?g.xv(f.trackingParams):null,imageUrl:q1(d.image.thumbnails,290).url,displayDomain:d.displayDomain?g.Aw(d.displayDomain):null,showLinkIcon:!!d.showLinkIcon,hx:null,title:d.title?g.Aw(d.title):"",customMessage:d.callToAction?g.Aw(d.callToAction):"",url:d.command.urlEndpoint.url?c1({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:d.command.urlEndpoint.url}):null,onClickCommand:null};o1(a,b)}else if(b.content.collaboratorInfoCardContentRenderer){if(!b.cueRanges.length)return;d=b.content.collaboratorInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"collaborator",teaserText:g.Aw(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:p1(a,
c,b,d),sponsored:!1,tracking:k1(d,e,d.endpoint),Ml:d.trackingParams?g.xv(d.trackingParams):null,cj:e.trackingParams?g.xv(e.trackingParams):null,df:f&&f.trackingParams?g.xv(f.trackingParams):null,channelId:d.endpoint.browseEndpoint.browseId,customMessage:d.customText?g.Aw(d.customText):null,profileImageUrl:q1(d.channelAvatar.thumbnails,290).url,title:d.channelName?g.Aw(d.channelName):"",metaInfo:[d.subscriberCountText?g.Aw(d.subscriberCountText):""],url:c1({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:d.endpoint.browseEndpoint.canonicalBaseUrl?d.endpoint.browseEndpoint.canonicalBaseUrl:"/channel/"+d.endpoint.browseEndpoint.browseId}),onClickCommand:null};o1(a,b)}else if(b.content.playlistInfoCardContentRenderer){if(!b.cueRanges.length)return;d=b.content.playlistInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"playlist",teaserText:g.Aw(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:p1(a,c,b,d),sponsored:!1,tracking:k1(d,e,d.action),Ml:d.trackingParams?g.xv(d.trackingParams):null,cj:e.trackingParams?g.xv(e.trackingParams):null,df:f&&f.trackingParams?g.xv(f.trackingParams):null,Iz:q1(d.playlistThumbnail.thumbnails,258).url,customMessage:d.customMessage?g.Aw(d.customMessage):null,playlistVideoCount:g.Aw(d.playlistVideoCount),title:d.playlistTitle?g.Aw(d.playlistTitle):"",metaInfo:[d.channelName?
g.Aw(d.channelName):"",d.videoCountText?g.Aw(d.videoCountText):""],url:c1({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:xUa(d.action)}),onClickCommand:null};o1(a,b)}else if(b.content.videoInfoCardContentRenderer){if(!b.cueRanges.length)return;d=b.content.videoInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"video",teaserText:g.Aw(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:p1(a,c,b,d),sponsored:!1,tracking:k1(d,e,d.action),Ml:d.trackingParams?g.xv(d.trackingParams):null,cj:e.trackingParams?g.xv(e.trackingParams):null,df:f&&f.trackingParams?g.xv(f.trackingParams):null,Iz:q1(d.videoThumbnail.thumbnails,258).url,videoDuration:d.lengthString?g.Aw(d.lengthString):null,customMessage:d.customMessage?g.Aw(d.customMessage):null,title:d.videoTitle?g.Aw(d.videoTitle):"",metaInfo:[d.channelName?
g.Aw(d.channelName):"",d.viewCountText?g.Aw(d.viewCountText):""],isLiveNow:!!d.badge,url:c1({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:xUa(d.action)}),onClickCommand:null};o1(a,b)}a.I++},q1=function(a,b){for(var c=-1,d=-1,e=0;e<a.length;e++){if(a[e].height===b||290===a[e].width)return a[e];
((a[e].height||0)<b||290>(a[e].width||0))&&(0>c||(a[c].height||0)<(a[e].height||0)||(a[c].width||0)<(a[e].width||0))?c=e:((a[e].height||0)>=b||290<=(a[e].width||0))&&(0>d||(a[d].height||0)>(a[e].height||0)||(a[d].width||0)>(a[e].width||0))&&(d=e)}return a[0<=d?d:c]},p1=function(a,b,c,d){return{feature:c.feature?c.feature:"cards",
src_vid:a.context.videoData.videoId,annotation_id:b,ei:a.context.videoData.eventId||"",itct:d.trackingParams||""}},BUa=function(a,b){if(b=AUa(a,b))b===a.j&&(a.j=null),a.G.removeCueRange(b.card.id),g.Th(b.qF),g.Zb(a.cards,b),a.EA(),r1(a)},l1=function(a,b,c){if(!a.B){a.Za.show();
a.Qa=new g.L(function(){g.N(a.context.G.getRootNode(),g.bP.IV_DRAWER_OPEN)},0);
a.Qa.start();a.ma=g.au(a.u,"mousewheel",function(k){a.va.start();k.preventDefault();k=k||window.event;var l=0;"MozMousePixelScroll"==k.type?l=0==(k.axis==k.HORIZONTAL_AXIS)?k.detail:0:window.opera?l=k.detail:l=0==k.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?k.wheelDeltaY/-30:k.wheelDeltaY/-1.2:k.wheelDelta/-1.6:k.wheelDeltaY/-3;if(k=l)a.u.scrollTop+=k});
a.B=!0;var d=g.Ev();d&&a.Da&&a.J&&g.Mv(d,[a.Da,a.J]);b={TRIGGER_TYPE:b};for(var e=g.r(a.cards),f=e.next();!f.done;f=e.next())f=f.value,f.NO||(f.NO=!0,CUa(a.context.logger,f.card.tracking.impression,b)),d&&g.Mv(d,[f.card.Ml]);F0(a.G);c&&(a.D=new g.L(function(){a.Fa=a.N;a.ib.focus()},330),a.D.start())}},m1=function(a){a.B&&(a.Za.hide(),g.bu(a.ma),a.ma=null,g.rp(a.context.G.getRootNode(),g.bP.IV_DRAWER_OPEN),a.B=!1,F0(a.G),a.D&&a.D.stop(),a.D=new g.L(function(){a.Fa&&(a.Fa.focus(),a.Fa=null)},330),a.D.start())},
EUa=function(a){g.qp(a.element,[g.bP.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.oJ(a.G,a.C,5);DUa(a);a.N=g.Jh("ytp-cards-button",a.G.getRootNode());a.ib=g.Jh("iv-drawer-close-button",a.C);a.isInitialized=!0},DUa=function(a){var b=g.Jh("iv-drawer-close-button",a.C);
a.context.j.Ja(b,"click",a.hV,a);a.context.j.Ja(a.u,"touchend",function(){a.va.start()});
a.context.j.Ja(a.u,"scroll",a.tV,a);a.context.u.subscribe("onHideControls",function(){a.Ia=!0});
a.context.u.subscribe("onShowControls",function(){a.Ia=!1});
a.context.u.subscribe("onVideoAreaChange",function(){a.Ia=g.pp(a.G.getRootNode(),"ytp-autohide")});
a.W.push(g.uu("iv-button-shown",a.RW,a));a.W.push(g.uu("iv-button-hidden",a.QW,a));a.W.push(g.uu("iv-teaser-shown",a.XT,a));a.W.push(g.uu("iv-teaser-hidden",a.SW,a));a.W.push(g.uu("iv-teaser-clicked",a.VT,a))},FUa=function(a,b){var c,d=null==(c=a.G.getVideoData())?void 0:c.multiMarkersPlayerBarRenderer;
if(null==d?0:d.markersMap){var e;for(c=0;(null==(e=d)?void 0:e.markersMap.length)>c;c++){var f=void 0,k=null==(f=d)?void 0:f.markersMap[c];if("ERROR_CORRECTION_MARKERS"===k.key&&(f=void 0,(k=null==(f=k.value)?void 0:f.markers)&&0<k.length))return d=void 0,b.startMs=(null==(d=k[0].markerRenderer)?void 0:d.timeRangeStartMillis)||0,a.Y=null,!0}}a.Y=b;return!1},o1=function(a,b){if(b.onClickCommand&&b.onClickCommand.changeEngagementPanelVisibilityAction&&"engagement-panel-error-corrections"===b.onClickCommand.changeEngagementPanelVisibilityAction.targetId){a.Y=
b;
var c=!0}else c=!1;if(!c||FUa(a,b))if(c=GUa(a,b)){var d={card:b,qF:c.element,NO:!1};if(!b.onClickCommand){a.isInitialized||EUa(a);BUa(a,b.id);var e=HUa(a,d);g.ec(a.cards,e,0,d);c.xa(a.u,e);a.EA()}b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,function(){a.B||(a.j=d,r1(a),IUa(a,d),l1(a,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(c=1E3*a.context.G.getCurrentTime(),5E3>c&&c>b.startMs&&JUa(a,d),a.addCueRange(b.startMs,b.startMs+1,b.id,function(){JUa(a,d)}),r1(a))}},GUa=function(a,b){switch(b.type){case "simple":a=
a.oa;
var c=b.displayDomain?{F:"div",K:"iv-card-image-text",Z:b.displayDomain}:void 0;var d=tUa(b);c={F:"div",Ba:["iv-card"],R:[{F:"a",K:"iv-click-target",T:{href:b.url?b1(b.url)||"":""},R:[f1(b.imageUrl,c),{F:"div",K:"iv-card-content",R:[d1("h2",void 0,b.title),d]}]}]};c=new g.W(c);h1(a,g.Ih("iv-click-target",c.element),b,b.url);return c;case "collaborator":return a=a.oa,c={F:"div",Ba:["iv-card","iv-card-channel"],R:[{F:"a",Ba:["iv-click-target"],T:{href:b1(b.url)||"","data-ytid":b.channelId},R:[f1(b.profileImageUrl),
{F:"div",K:"iv-card-content",R:[e1(b),{F:"h2",K:"iv-card-primary-link",Z:b.title},g1(b)]}]}]},c=new g.W(c),h1(a,g.Ih("iv-click-target",c.element),b,b.url),c;case "playlist":return a=a.oa,c={F:"div",Ba:["iv-card","iv-card-playlist"],R:[{F:"a",K:"iv-click-target",T:{href:b1(b.url)||""},R:[f1(b.Iz,{F:"div",K:"iv-card-image-overlay",R:[{F:"span",K:"iv-card-playlist-video-count",Z:b.playlistVideoCount}]}),{F:"div",K:"iv-card-content",R:[e1(b),d1("h2","iv-card-primary-link",b.title),g1(b)]}]}]},c=new g.W(c),
h1(a,g.Ih("iv-click-target",c.element),b,b.url),c;case "productListing":a=a.oa;var e=!g.Vb(b.offers);c=["iv-card"];d="";var f=tUa(b);e&&(c.push("iv-card-product-listing"),d="iv-card-primary-link",f=b.offers[0],e=[],f.price&&e.push({F:"div",K:"iv-card-offer-price",Z:f.price}),f.merchant&&e.push({F:"div",K:"iv-card-offer-merchant",Z:f.merchant}),f={F:"div",R:e});e=b.url?b1(b.url)||"":"";c={F:"div",Ba:c,T:{tabindex:"0"},R:[{F:"a",Ba:["iv-card-image","iv-click-target"],T:{style:"background-image: url("+
b.imageUrl+");",href:e,"aria-hidden":"true",tabindex:"-1"}},{F:"div",K:"iv-card-content",R:[b.sponsored?{F:"div",K:"iv-card-sponsored",R:["Sponsored",{F:"div",K:"iv-ad-info-container",R:[{F:"div",K:"iv-ad-info",Z:"{{adInfo}}"},{F:"div",K:"iv-ad-info-icon-container",R:[{F:"div",K:"iv-ad-info-icon"},{F:"div",K:"iv-ad-info-callout"}]}]}]}:"",{F:"a",K:"iv-click-target",T:{href:e},R:[d1("h2",d,b.title),f]}]}]};c=new g.W(c);d=g.Oh("span");g.Wh(d,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");
c.Ld(d,"adInfo");h1(a,g.Ih("iv-click-target",c.element),b,b.url);return c;case "video":return a=a.oa,d=b.videoDuration?{F:"span",K:"iv-card-video-duration",Z:b.videoDuration}:void 0,f=b.isLiveNow?{F:"span",Ba:["yt-badge","yt-badge-live"],Z:"LIVE NOW"}:null,e={F:"div",Ba:["iv-card","iv-card-video"],R:[{F:"a",K:"iv-click-target",T:{href:(null==(c=b.url)?void 0:b1(c))||""},R:[f1(b.Iz,d),{F:"div",K:"iv-card-content",R:[e1(b),d1("h2","iv-card-primary-link",b.title),g1(b),f]}]}]},c=new g.W(e),h1(a,g.Ih("iv-click-target",
c.element),b,b.url),c;default:return null}},HUa=function(a,b){if(0===a.cards.length)return 0;
a=g.Rb(a.cards,function(c){return b.card.startMs>c.card.startMs||b.card.startMs===c.card.startMs&&b.card.timestamp>=c.card.timestamp?!0:!1});
return-1===a?0:a+1},KUa=function(a){return a.j?"productListing"===a.j.card.type:g.Cl(a.cards,function(b){return"productListing"===b.card.type})},r1=function(a){g.O(a.G.getRootNode(),"ytp-cards-shopping-active",KUa(a))},JUa=function(a,b){if(!g.pp(a.G.getRootNode(),"ytp-cards-teaser-shown")){if(a.j!==b){var c=g.Ev(),d=a.j?a.j.card.df:a.df;
c&&d&&g.Nv(c,[d]);a.j=b;r1(a)}(c=a.isInitialized&&"none"==a.element.style.display)||(c=a.context.G.getPlayerState(),d=0===c&&0===a.context.G.getCurrentTime(),c=!(1===c||3===c||d));c||b.card.teaserDurationMs&&a.G.Dv(!0,{teaserText:b.card.teaserText,durationMs:b.card.teaserDurationMs,onClickCommand:b.card.onClickCommand});a.eb.isActive()||((!a.B||!a.va.isActive()&&a.Ia)&&IUa(a,b),a.eb.start(910+b.card.teaserDurationMs))}},IUa=function(a,b){a.V.ob?(b=new K0([0,
a.u.scrollTop],[0,b.qF.offsetTop],600,TTa),a.context.B.Ja(b,"animate",function(c){a.u.scrollTop=c.y}),a.context.B.Ja(b,"finish",function(c){a.u.scrollTop=c.y}),b.play()):(g.HG(a.V,!0),a.u.scrollTop=b.qF.offsetTop,g.HG(a.V,!1))},s1=function(a){return a.j&&a.j.card?a.j.card:a.cards[0]&&a.cards[0].card?a.cards[0].card:null},AUa=function(a,b){return g.Qb(a.cards,function(c){return c.card.id===b})},t1=function(a,b,c){i1.call(this,a,b);
this.annotation=c;this.isActive=!1},LUa=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(b.start_ms,b.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},u1=function(a,b,c){t1.call(this,a,b,c);
this.u=null;this.J=!1;this.B=null;this.C=!1;this.j=this.I=this.D=null},MUa=function(a,b){var c=void 0===c?0:c;
var d=RTa(b).width;g.Am(b,d);c=new M0(b,[d,b.offsetTop],[d-d-c,b.offsetTop],200,STa);g.H(a,c);a.context.B.Ja(c,"begin",function(){g.Gm(b,!0)});
c.play()},PUa=function(a,b){if(b.channel_name){var c=a.createElement({F:"div",
Ba:["iv-branding-context-name"],Z:b.channel_name}),d=a.createElement({F:"div",Ba:["iv-branding-context-subscribe"]}),e=b.standalone_subscribe_button_data;e&&(a.j=new g.TK(e.subscribeText,e.subscribeCount,e.unsubscribeText,e.unsubscribeCount,!!e.enabled,!!e.classic,b.channel_id,!!e.subscribed,e.feature,b.session_data.itct,e.signInUrl,a.context.G),a.j.xa(d));var f=a.createElement({F:"div",Ba:["iv-branding-context-subscribe-caret"]}),k=a.createElement({F:"div",Ba:["branding-context-container-inner"]});
k.appendChild(f);k.appendChild(c);k.appendChild(d);g.Gm(k,!1);var l=a.createElement({F:"div",Ba:["branding-context-container-outer"]});l.appendChild(k);g.um(l,"right",b.image_width+"px");a.element.appendChild(l);a.B=new g.L(function(){NUa(a,k,l)},500);
g.H(a,a.B);a.context.j.Ja(a.element,"mouseover",function(){OUa(a,k,l,f,b.image_height)});
a.context.j.Ja(a.element,"mouseout",function(){a.B.start()})}},OUa=function(a,b,c,d,e){a.B.stop();
if(!a.C){var f=g.Fm(b);a.j||(b.style.width=g.zm(f.width,!0),c.style.width=g.zm(f.width,!0));g.um(d,"top",f.height-Math.max(Math.min(f.height,e)/2+10,20)+"px");g.um(d,"right","1px");a.C=!0;g.Gm(b,!0);a.D=new g.L(function(){g.N(this.element,"iv-branding-active")},0,a);
a.D.start()}},NUa=function(a,b,c){g.rp(a.element,"iv-branding-active");
a.I=new g.L(function(){g.Gm(b,!1);a.j||(c.style.width=g.zm(0,!0))},250);
a.I.start();a.C=!1},QUa=function(a,b,c,d,e,f,k){this.j=a;
this.B=b;this.U=c;this.videoData=d;this.logger=e;this.G=f;this.u=k},v1=function(a,b,c){t1.call(this,a,b,c);
var d=this;this.N=this.isCollapsed=this.V=!1;this.I=5E3;this.u=this.B=this.j=this.C=null;this.J=this.createElement({F:"div",Ba:["iv-promo-contents"]});this.D=new g.L(function(){d.j.setAttribute("aria-hidden","true");g.Gm(d.B,!1);g.Gm(d.u,!0)},700,this);
g.H(this,this.D)},RUa=function(a){var b=a.annotation.data;
if("cta"===a.annotation.style)var c=6;else if("video"===a.annotation.style||"playlist"===a.annotation.style)c=7;a.I=b.collapsedelay_ms||a.I;var d=["iv-promo","iv-promo-inactive"];a.element.setAttribute("aria-hidden","true");a.element.setAttribute("aria-label","Promotion");a.element.tabIndex=0;var e=rUa(a.annotation),f=b.image_url;if(f){var k=a.createElement({F:"div",Ba:["iv-promo-img","iv-click-target"]});f=a.createElement({F:"img",T:{src:f,"aria-hidden":"true"}});k.appendChild(f);b.video_duration&&
!b.is_live?(f=a.createElement({F:"span",K:"iv-promo-video-duration",Z:b.video_duration}),k.appendChild(f)):b.playlist_length&&(f=a.createElement({F:"span",K:"iv-promo-playlist-length",Z:b.playlist_length.toString()}),k.appendChild(f));e&&j1(a,k,e,a.annotation.id,b.session_data,void 0,c)}e?(f=a.createElement({F:"a",K:"iv-promo-txt"}),g.lh(f,b1(e)),a.j=f):a.j=a.createElement({F:"div",K:"iv-promo-txt"});switch(a.annotation.style){case "cta":case "website":var l=a.createElement({F:"p",R:[{F:"strong",
Z:b.text_line_1}]});var m=a.createElement({F:"p",R:[{F:"span",K:"iv-promo-link",Z:b.text_line_2}]});if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");var n=a.createElement({F:"button",Ba:["iv-promo-round-expand-icon","ytp-button"]});f=a.createElement({F:"button",Ba:["iv-button","iv-promo-button"],R:[{F:"span",K:"iv-button-content",Z:f}]});var p=a.createElement({F:"div",K:"iv-promo-button-container"});p.appendChild(f);e&&j1(a,a.element,e,a.annotation.id,b.session_data,void 0,c)}g.N(a.j,
"iv-click-target");e&&j1(a,a.j,e,a.annotation.id,b.session_data,void 0,c);break;case "playlist":case "video":l=a.createElement({F:"p",R:[{F:"span",Z:b.text_line_1}]}),m=a.createElement({F:"p",R:[{F:"strong",Z:b.text_line_2}]}),b.is_live&&(l=m,m=a.createElement({F:"span",Ba:["yt-badge","iv-promo-badge-live"],Z:"LIVE NOW"})),g.N(a.j,"iv-click-target"),e&&j1(a,a.j,e,a.annotation.id,b.session_data,void 0,c),d.push("iv-promo-video")}l&&a.j.appendChild(l);m&&a.j.appendChild(m);a.J.appendChild(a.j);p&&a.J.appendChild(p);
c=a.createElement({F:"div",K:"iv-promo-actions"});a.u=a.createElement({F:"button",Ba:["iv-promo-expand","ytp-button"]});a.u.title="Expand";a.context.j.Ja(a.u,"click",function(q){w1(a,5E3,q)});
c.appendChild(a.u);g.Gm(a.u,!1);a.context.j.Ja(a.element,"mouseover",a.ZV,a);a.context.j.Ja(a.element,"mouseout",a.YV,a);a.context.j.Ja(a.element,"touchend",function(q){w1(a,5E3,q)});
a.B=a.createElement({F:"button",Ba:["iv-promo-close","ytp-button"]});a.B.title="Close";a.context.j.Ja(a.B,"click","cta"===a.annotation.style&&b.text_line_3?a.UV:a.TV,a);c.appendChild(a.B);g.qp(a.element,d);k&&(a.element.appendChild(k),n&&k.appendChild(n));a.element.appendChild(a.J);a.element.appendChild(c)},w1=function(a,b,c){c.stopPropagation();
SUa(a);TUa(a,b);a.j.focus()},UUa=function(a){a.isCollapsed||a.N||a.C||(g.N(a.element,"iv-promo-collapsed"),a.isCollapsed=!0,a.D.start())},SUa=function(a){a.D.stop();
a.isCollapsed&&(g.sp(a.element,["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.isCollapsed=!1,a.j&&a.j.removeAttribute("aria-hidden"),g.Gm(a.u,!1),g.Gm(a.B,!0))},TUa=function(a,b){a.C||(a.C=g.pi(function(){x1(this);
UUa(this)},b,a))},x1=function(a){a.C&&(g.C.clearTimeout(a.C),a.C=null)},VUa=function(a){this.G=a},CUa=function(a,b,c){b&&(c?y1(a,b.map(function(d){return g.cp(d,c)})):y1(a,b))},y1=function(a,b,c,d){var e=1,f=void 0,k=-1;
if(c){var l=!1;f=function(){e--;e||l||(clearTimeout(k),l=!0,c())};
k=setTimeout(function(){l=!0;c()},1E3)}b=g.r(b||[]);
for(var m=b.next();!m.done;m=b.next())m=m.value,e++,g.zt(m,f);d&&(e++,0!==d&&a.G.sendVideoStatsEngageEvent(d,f))},z1=function(a){g.CJ.call(this,a);
var b=this;this.loadNumber=0;this.I={};this.logger=new VUa(this.player);this.D=new g.Uz(this);this.C=this.Gm=null;this.events=new g.Uz(this);this.J=this.j=null;this.N=[];g.H(this,this.D);this.D.P(this.player,"onVideoAreaChange",function(){b.X("onVideoAreaChange")});
this.D.P(this.player,"onHideControls",function(){b.X("onHideControls")});
this.D.P(this.player,"onShowControls",function(){b.X("onShowControls")});
this.D.P(this.player,"resize",function(d){b.X("resize",d)});
this.D.P(this.player,"presentingplayerstatechange",function(d){b.X("presentingplayerstatechange",d)});
this.subscribe("presentingplayerstatechange",this.ZT,this);this.subscribe("resize",this.uC,this);this.player.S().W.subscribe("vast_info_card_add",this.ZP,this);g.H(this,this.events);this.V=this.createElement({F:"div",K:"video-custom-annotations"});this.u=new g.W({F:"div",Ba:["ytp-player-content","ytp-iv-player-content"]});g.H(this,this.u);g.oJ(this.player,this.u.element,4);this.u.hide();this.B=new g.W({F:"div",Ba:["ytp-iv-video-content"]});g.H(this,this.B);a=this.createElement({F:"div",K:"video-annotations"});
a.appendChild(this.V);this.B.element.appendChild(a);this.Is()&&this.load();var c=this.createElement({F:"style"});(g.Gh("HEAD")[0]||document.body).appendChild(c);g.qf(this,function(){g.Th(c)});
if(a=c.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},WUa=function(a){a=a.createElement({F:"div",
Ba:["annotation","annotation-type-custom"]});g.Gm(a,!1);return a},XUa=function(a,b){b=!b.isCued()&&!g.V(b,1024);
g.HG(a.u,b);g.HG(a.B,b)},YUa=function(a,b){for(var c={},d=g.r(b.attributes),e=d.next();!e.done;e=d.next())e=e.value,c[e.name]=e.nodeValue;
for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],g.Na(e)&&1==e.nodeType){if(c[e.tagName])var f=c[e.tagName];else if("data"===e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"===typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"===e.tagName?1===e.childNodes.length&&3===e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(YUa(a,e))}return c},aVa=function(a){var b=a.player.getVideoData();
if(b.Ra){var c=a.player.S().W.get(b.videoId);if(c){var d={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(e,f,k){e=b.videoId;a.loaded&&a.loadNumber===a.loadNumber&&a.player.getVideoData().videoId===e&&(k=g.cr(k)&&k.responseXML?k.responseXML:null)&&A1(a,k)}};
g.hs()&&(d.onFinish=ZUa(a,d.onFinish));d.postParams={ic_only:"1"};$Ua(d,c);g.ir(b.Ra,d)}}},$Ua=function(a,b){a.method="POST";
a.postParams=a.postParams||{};b.ix&&(a.postParams.ic_coll=b.ix);b.JA&&(a.postParams.ic_xml=b.JA);b.Lz&&(a.postParams.ic_track=b.Lz)},bVa=function(a){var b=new g.W({F:"div"});
g.Gm(b.element,!1);var c=new n1(a.player,b.element,B1(a));g.H(c,b);b.xa(a.u.element);c.wz();return c},B1=function(a){if(!a.J){var b=new N0(a);
g.H(a,b);var c=new g.sk(a);g.H(a,c);a.J=new QUa(b,c,a.player.S(),a.player.getVideoData(),a.logger,a.player,a.Ke)}return a.J},A1=function(a,b){var c=!1,d=b.getElementsByTagName("annotations");
if(d&&!(1>d.length)&&(d=d[0].getAttribute("itct"))){var e=g.Ev();if(e){var f=g.Dv();f&&g.Iv(void 0,e,f,[g.xv(d)])}}b=b.getElementsByTagName("annotation");for(d=0;d<b.length;d++){f=YUa(a,b[d]);e=null;try{if(f){var k=f.id,l=/.+/;var m="string"===typeof k&&null!=l&&null!=k&&k.match(l)?k:"";var n=a1(f.type,cVa),p=a1(f.style,dVa),q=iUa(f.data),t=0!==q.length?JSON.parse(q):{};var v=f.action;f=oUa;if(null==v)var x=null;else if(g.Ma(v)){l=[];for(var y=g.r(v),z=y.next();!z.done;z=y.next()){var E=f(z.value);
E&&l.push(E)}x=l}else{var J=f(v);x=J?[J]:[]}e=m&&n?new pUa(m,n,p,x,t):null}else e=null}catch(za){}if(e)if("branding"===e.type||"promotion"===e.type){f=a;l=e;var I=WUa(f),M=null;switch(l.type){case "branding":if(f.player.S().Kc)break;f.u.element.appendChild(I);M=new u1(I,B1(f),l);break;case "promotion":g.oJ(f.player,I,4),M=new v1(I,B1(f),l)}M&&M.wz();if(f=M)g.H(a,f),a.I[e.id]=f}else if("card"===e.type||"drawer"===e.type){a.j||(a.j=bVa(a),g.H(a,a.j));if("card"===e.type){c=a.j;var da=e&&e.data&&e.data.card_type;
f=e.data;if(da)switch(l=f.tracking||{},l={impression:l.impression,click:l.click,close:l.close,oR:l.teaser_impression,nD:l.teaser_click},I=f.tracking_params||{},M=null,da){case "collaborator":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,Ml:I.card?g.xv(I.card):null,cj:I.teaser?g.xv(I.teaser):null,df:I.icon?g.xv(I.icon):
null,channelId:f.channel_id,customMessage:f.custom_message?f.custom_message:null,profileImageUrl:f.image_url,title:f.title,metaInfo:f.meta_info,url:c1({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null};o1(c,e);break;case "playlist":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,
Ml:I.card?g.xv(I.card):null,cj:I.teaser?g.xv(I.teaser):null,df:I.icon?g.xv(I.icon):null,Iz:f.image_url,playlistVideoCount:f.playlist_video_count,customMessage:f.custom_message?f.custom_message:null,title:f.title,metaInfo:f.meta_info,url:c1({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null};o1(c,e);break;case "productListing":f.signin_url&&(M=c1({target:"current",value:f.signin_url}));da=[];for(var K=f.offers||[],pa=0;pa<K.length;pa++)da.push(new uUa(g.Ah(K[pa].merchant),
g.Ah(K[pa].price)));e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,Ml:I.card?g.xv(I.card):null,cj:I.teaser?g.xv(I.teaser):null,df:I.icon?g.xv(I.icon):null,imageUrl:f.image_url,displayDomain:f.display_domain?f.display_domain:null,showLinkIcon:!!f.show_link_icon,hx:f.button_icon_url?f.button_icon_url:null,title:f.title,customMessage:f.custom_message?
f.custom_message:null,url:c1({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),dka:M,cka:f.signin_title?f.signin_title:void 0,bka:f.signin_message?f.signin_message:void 0,offers:da,onClickCommand:null};o1(c,e);break;case "simple":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,Ml:I.card?g.xv(I.card):
null,cj:I.teaser?g.xv(I.teaser):null,df:I.icon?g.xv(I.icon):null,imageUrl:f.image_url,displayDomain:f.display_domain?f.display_domain:null,showLinkIcon:!!f.show_link_icon,hx:f.button_icon_url?f.button_icon_url:null,title:f.title,customMessage:f.custom_message?f.custom_message:null,url:c1({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null};o1(c,e);break;case "video":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,
startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,Ml:I.card?g.xv(I.card):null,cj:I.teaser?g.xv(I.teaser):null,df:I.icon?g.xv(I.icon):null,Iz:f.image_url,videoDuration:f.video_duration||null,customMessage:f.custom_message?f.custom_message:null,title:f.title,metaInfo:f.meta_info,isLiveNow:!!f.is_live_now,url:c1({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null},o1(c,e)}}else yUa(a.j,e);c=
!0}}c&&(F0(a.player),a.uC())},eVa=function(a,b){var c=!1;
a.j||(a.j=bVa(a),g.H(a,a.j));for(var d=g.r(b.cards||[]),e=d.next();!e.done;e=d.next())e=e.value,e.cardRenderer&&(zUa(a.j,e.cardRenderer),c=!0);c&&(c=a.j,d=b.headerText?g.Aw(b.headerText):"",g.Wh(c.Fb,d),c.N&&c.N.setAttribute("title",d),c.context.videoData.eventId&&(c.eventId=c.context.videoData.eventId),c.Da=b.trackingParams?g.xv(b.trackingParams):null,c.J=b.closeButton.infoCardIconRenderer.trackingParams?g.xv(b.closeButton.infoCardIconRenderer.trackingParams):null,c.df=b.icon.infoCardIconRenderer.trackingParams?
g.xv(b.icon.infoCardIconRenderer.trackingParams):null,F0(a.player),a.uC())},fVa=function(a,b,c,d,e){if(!a.player.S().Kc){var f=[];
b.navigationEndpoint&&b.navigationEndpoint.browseEndpoint&&b.navigationEndpoint.browseEndpoint.browseId&&f.push(new lUa("openUrl","click",new jUa("/channel/"+b.navigationEndpoint.browseEndpoint.browseId,"new",!0,!0)));var k=b.watermark.thumbnails[0];d={channel_name:b.channelName,end_ms:b.endTimeMs,image_height:k.height,image_type:1,image_url:k.url,image_width:k.width,is_mobile:!1,session_data:{annotation_id:c,ei:e,feature:"iv",itct:b.trackingParams,src_vid:d},start_ms:b.startTimeMs};if(b.subscribeButton&&
b.subscribeButton.subscribeButtonRenderer){d.channel_id=b.subscribeButton.subscribeButtonRenderer.channelId;var l;b=b.subscribeButton.subscribeButtonRenderer;k=e=null;b.subscribed?(b.subscriberCountWithUnsubscribeText&&(e=g.Aw(b.subscriberCountWithUnsubscribeText)),b.subscriberCountText&&(k=g.Aw(b.subscriberCountText))):(b.subscriberCountText&&(e=g.Aw(b.subscriberCountText)),b.subscriberCountWithSubscribeText&&(k=g.Aw(b.subscriberCountWithSubscribeText)));if(b.signInEndpoint&&b.signInEndpoint.webNavigationEndpointData&&
b.signInEndpoint.webNavigationEndpointData.url)var m=b.signInEndpoint.webNavigationEndpointData.url;else{var n,p;m=(null==(l=b.signInEndpoint)?void 0:null==(n=l.commandMetadata)?void 0:null==(p=n.webCommandMetadata)?void 0:p.url)||""}l={subscribeText:g.Aw(b.unsubscribedButtonText),subscribeCount:e||"",unsubscribeText:g.Aw(b.subscribedButtonText),unsubscribeCount:k||"",enabled:b.enabled||!1,classic:!1,subscribed:b.subscribed||!1,feature:"iv",signInUrl:m};d.standalone_subscribe_button_data=l}f=new pUa(c,
"branding","branding",f,d);l=WUa(a);a.u.element.appendChild(l);f=new u1(l,B1(a),f);f.wz();g.H(f,f);a.I[c]=f}},ZUa=function(a,b){return function(){var c=g.Ca.apply(0,arguments);
a.isDisposed()||a.N.push(g.fp.Rg(function(){b.apply(null,g.u(c))}))}},gVa=function(a){return"annotation-editor"===a||"live-dashboard"===a};
g.hJ.prototype.Dv=g.ca(13,function(a,b){var c=g.eK(this.jb());c&&c.Dv(a,b)});
var H0={},I0=null;g.Ua(K0,g.Ap);g.h=K0.prototype;g.h.getDuration=function(){return this.duration};
g.h.play=function(a){if(a||0==this.j)this.progress=0,this.coords=this.u;else if(this.Lc())return!1;J0(this);this.startTime=a=g.Ta();-1==this.j&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.D=this.startTime;this.progress||this.pC();this.uj("play");-1==this.j&&this.uj("resume");this.j=1;var b=g.Qa(this);b in H0||(H0[b]=this);VTa();WTa(this,a);return!0};
g.h.stop=function(a){J0(this);this.j=0;a&&(this.progress=1);XTa(this,this.progress);this.uj("stop");this.Oy()};
g.h.pause=function(){this.Lc()&&(J0(this),this.j=-1,this.uj("pause"))};
g.h.ea=function(){0==this.j||this.stop(!1);this.uj("destroy");K0.He.ea.call(this)};
g.h.destroy=function(){this.dispose()};
g.h.yE=function(){this.uj("animate")};
g.h.uj=function(a){this.dispatchEvent(new YTa(a,this))};
g.Ua(YTa,g.rf);g.Ua(L0,K0);L0.prototype.C=function(){};
L0.prototype.yE=function(){this.C();L0.He.yE.call(this)};
L0.prototype.Oy=function(){this.C();L0.He.Oy.call(this)};
L0.prototype.pC=function(){this.C();L0.He.pC.call(this)};
g.Ua(M0,L0);M0.prototype.C=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.w(N0,g.G);N0.prototype.Ja=function(a,b,c,d){c=(0,g.Ra)(c,d||this.u);a=g.au(a,b,c);this.j.push(a);return a};
N0.prototype.aC=function(a,b,c,d){c=(0,g.Ra)(c,d||this.u);a=g.Aoa(a,b,c);this.j.push(a);return a};
N0.prototype.wc=function(a){g.bu(a);g.Zb(this.j,a)};
N0.prototype.ea=function(){g.bu(this.j);this.j.length=0;g.G.prototype.ea.call(this)};g.w(R0,g.CJ);g.h=R0.prototype;g.h.load=function(){g.CJ.prototype.load.call(this);if(!S0(this)){var a=g.ywa(this.player.getVideoData());a?(a=Q0(a,$Ta(this)),T0(this,a,!1)):aUa(this)}};
g.h.unload=function(){T0(this,null);this.B&&(this.B.abort(),this.B=null);g.CJ.prototype.unload.call(this)};
g.h.Yf=function(a,b){return S0(this)?"loadCustomEndscreenRenderer"===a?(a=Q0(b,"new"),T0(this,a),!0):null:null};
g.h.getOptions=function(){return S0(this)?["loadCustomEndscreenRenderer"]:[]};
g.h.ub=function(){if(this.endscreen&&this.endscreen.elements){var a=this.player.getVideoContentRect();if(a&&0!==a.width&&0!==a.height){var b=this.player.getPlayerSize();if(b&&0!==b.width&&0!==b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<hVa.length;f++){var k=Math.abs(b.width-hVa[f]);if(-1===e||d>=k)e=f,d=k}d=iVa[e];this.u&&g.um(this.u.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.endscreen.elements.length;++b)if(f=this.endscreen.elements[b].id,e=this.j[f],
k=this.D[f],e&&k){var l=k.width*c/k.aspectRatio;f=Math.round(l*a.height);var m=a.left+Math.round(k.left*a.width),n=a.top+Math.round(k.top*a.height);g.Em(e.element,Math.round(k.width*a.width),f);g.Am(e.element,m,n);g.sp(e.element,jVa);m=k.left+k.width/2;k=k.top+l/2;g.N(e.element,.5>=m&&.5>=k?"ytp-ce-top-left-quad":.5<m&&.5>=k?"ytp-ce-top-right-quad":.5>=m&&.5<k?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.sp(e.element,iVa);g.N(e.element,d);(e=g.Hh(document,"div","ytp-ce-expanding-overlay-body",
e.element)[0])&&g.um(e,"height",f+"px")}}}}};
g.h.onCueRangeEnter=function(a){if(this.endscreen)if("ytp-ce-in-endscreen"===a.getId())$0(this,this.endscreen.impressionUrls),(a=g.Ev())&&this.endscreen.visualElement&&g.Jv(a,this.endscreen.visualElement);else{a=a.getId().substring(15);var b=this.j[a],c=this.D[a];g.N(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.N(b,"ytp-ce-shown");$0(this,c.impressionUrls);(b=g.Ev())&&g.Jv(b,c.visualElement);this.player.S().B&&this.player.La("endscreenelementshown",
a)}};
g.h.onCueRangeExit=function(a){if("ytp-ce-in-endscreen"!==a.getId()){a=a.getId().substring(15);var b=this.j[a];g.rp(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden","true");b=this.player.getRootNode();g.rp(b,"ytp-ce-shown");this.player.S().B&&this.player.La("endscreenelementhidden",a)}};
g.h.n_=function(a){var b=this;a.target===window&&(new g.L(function(){for(var c=g.r(Object.values(b.j)),d=c.next();!d.done;d=c.next())g.sp(d.value.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
var hVa=[346,426,470,506,570,640,853,1280,1920],iVa="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),jVa=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"];var kUa={z6:"current",Dca:"new"};var mUa={CLOSE:"close",Xca:"openUrl",SUBSCRIBE:"subscribe"},nUa={g3:"click",CLOSE:"close",g8:"hidden",Fea:"rollOut",Gea:"rollOver",Ffa:"shown"};var dVa={X1:"anchored",fS:"branding",CHANNEL:"channel",y6:"cta",j8:"highlightText",M9:"label",PLAYLIST:"playlist",Rda:"popup",Qfa:"speech",SUBSCRIBE:"subscribe",wga:"title",VIDEO:"video",bia:"website"},cVa={fS:"branding",R2:"card",T6:"drawer",i8:"highlight",waa:"marker",bea:"promotion",TEXT:"text",Hia:"widget"};g.w(i1,g.G);g.h=i1.prototype;g.h.addCueRange=function(a,b,c,d,e){a=new g.tw(a,b,{id:c,namespace:"annotations_module"});d&&this.Ra.set(a,d);e&&this.Ta.set(a,e);this.context.G.Yd([a])};
g.h.wz=function(){this.context.u.subscribe("resize",this.EA,this)};
g.h.zE=function(a,b,c,d,e,f){if(this.gb)return!1;f&&(f.stopPropagation(),f.preventDefault());this.navigate(a,c,d,e);return!1};
g.h.show=function(){};
g.h.hide=function(){};
g.h.destroy=function(){g.Th(this.element)};
g.h.EA=function(){};
g.h.navigate=function(a,b,c,d){var e=this,f=b1(a);if(f){var k=wUa(f,a.target),l=function(){a.j&&e.context.G.pauseVideo();var m=e.context.videoData.D||!1,n=g.Vq(f||"");m&&n&&(n.v||n.list)?e.context.G.ll(n.v,b,n.list,!1):g.SH(f||"","current"===k?"_top":void 0,b)};
"new"===k&&(l(),l=null);y1(this.context.logger,c,l,d);vUa(f)||(c=g.Ev(),d=b.itct,c&&d&&g.Ov(c,g.xv(d)))}};
g.h.ea=function(){this.Ra.clear();this.Ta.clear();g.G.prototype.ea.call(this)};
g.h.createElement=function(a){a=new g.W(a);g.H(this,a);return a.element};g.w(n1,i1);g.h=n1.prototype;g.h.Ap=function(){this.Y&&o1(this,this.Y)};
g.h.isAvailable=function(){var a;if(a=!!this.cards.length)(a=this.G.getRootNode())?(a=g.Fm(a),a=173<a.width&&173<a.height):a=!1;return a};
g.h.EA=function(){var a=this.isAvailable();g.Gm(this.element,a);g.O(this.context.G.getRootNode(),g.bP.IV_DRAWER_ENABLED,a);F0(this.G)};
g.h.destroy=function(){this.G.Dv(!1);try{this.G.getRootNode().removeChild(this.C)}catch(a){}g.vu(this.W);g.bu(this.ma);this.Qa&&this.Qa.dispose();this.D&&this.D.dispose();i1.prototype.destroy.call(this)};
g.h.hV=function(){if(this.B){y1(this.context.logger,s1(this).tracking.close);var a=g.Ev();a&&this.J&&g.Ov(a,this.J);m1(this)}};
g.h.tV=function(){g.O(this.C,"iv-drawer-scrolled",0<this.u.scrollTop)};
g.h.RW=function(){var a=g.Ev(),b=s1(this);b=b?b.df:this.df;a&&b&&g.Mv(a,[b])};
g.h.QW=function(){var a=g.Ev(),b=s1(this);b=b?b.df:this.df;a&&b&&g.Nv(a,[b])};
g.h.XT=function(){var a=s1(this);y1(this.context.logger,a.tracking.oR);var b=g.Ev();b&&a&&g.Mv(b,[a.cj,a.df])};
g.h.SW=function(){var a=g.Ev(),b=s1(this);a&&b&&g.Nv(a,[b.cj])};
g.h.VT=function(a){var b=s1(this),c=g.Ev();this.j?a?(a=this.context.logger,y1(a,b.tracking.nD),a.G.sendVideoStatsEngageEvent(4,void 0),c&&b.cj&&g.Ov(c,b.cj)):(a=this.context.logger,y1(a,b.tracking.nD),a.G.sendVideoStatsEngageEvent(4,void 0),c&&b.df&&g.Ov(c,b.df)):(a=this.context.logger,y1(a,b.tracking.nD),a.G.sendVideoStatsEngageEvent(4,void 0),c&&this.df&&g.Ov(c,this.df))};g.w(t1,i1);t1.prototype.wz=function(){i1.prototype.wz.call(this);LUa(this)};
t1.prototype.show=function(){i1.prototype.show.call(this);var a=g.Ev(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.Mv(a,[g.xv(b.itct)])};
t1.prototype.hide=function(){i1.prototype.hide.call(this);var a=g.Ev(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.Nv(a,[g.xv(b.itct)])};g.w(u1,t1);
u1.prototype.show=function(){if(!this.isActive){t1.prototype.show.call(this);if(!this.J){g.N(this.element,"iv-branding");var a=this.annotation.data;this.u=this.createElement({F:"img",Ba:["branding-img","iv-click-target"],T:{"aria-label":"Channel watermark",src:a.image_url,width:a.image_width,height:a.image_height}});g.Gm(this.u,!1);var b=this.context.U.L("html5_player_branding_button_killswitch")?this.createElement({F:"div",Ba:["branding-img-container"]}):this.createElement({F:"button",Ba:["branding-img-container",
"ytp-button"]});b.appendChild(this.u);this.element.appendChild(b);var c=rUa(this.annotation);c&&(b=this.context.U.L("html5_player_branding_button_killswitch")?this.u:b,j1(this,b,c,this.annotation.id,a.session_data));PUa(this,a);this.J=!0}g.Gm(this.element,!0);this.isActive=!0;this.u&&MUa(this,this.u)}};
u1.prototype.hide=function(){this.isActive&&(t1.prototype.hide.call(this),g.Gm(this.element,!1),this.isActive=!1)};
u1.prototype.destroy=function(){this.j&&(this.j.dispose(),this.j=null);t1.prototype.destroy.call(this)};g.w(v1,t1);g.h=v1.prototype;g.h.show=function(){this.isActive||(t1.prototype.show.call(this),this.V||(RUa(this),this.V=!0),g.Gm(this.element,!0),g.pi(function(){g.rp(this.element,"iv-promo-inactive")},100,this),this.element.removeAttribute("aria-hidden"),this.isActive=!0,x1(this),SUa(this),TUa(this,this.I))};
g.h.hide=function(){this.isActive&&(g.N(this.element,"iv-promo-inactive"),this.isActive=!1,this.element.setAttribute("aria-hidden","true"))};
g.h.zE=function(a,b,c,d,e,f){return this.isCollapsed?!1:t1.prototype.zE.call(this,a,b,c,d,e,f)};
g.h.ZV=function(a){this.N=!0;w1(this,500,a)};
g.h.YV=function(){this.N=!1;UUa(this)};
g.h.TV=function(a){a.stopPropagation();this.hide()};
g.h.UV=function(a){a.stopPropagation();x1(this);this.isCollapsed=!0;g.N(this.element,"iv-promo-collapsed-no-delay");this.D.start()};
g.h.destroy=function(){this.D.dispose();t1.prototype.destroy.call(this)};g.w(z1,g.CJ);g.h=z1.prototype;g.h.Yf=function(a,b){if(!gVa(this.player.S().playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":return(a=g.WZ(b))&&A1(this,a),!0;case "removeCustomAnnotationById":return b&&this.j&&(BUa(this.j,b),F0(this.player)),!0}return null};
g.h.getOptions=function(){return gVa(this.player.S().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.h.Is=function(){var a=this.player.S(),b=this.player.getVideoData();return b.D&&a.pfpChazalUi?!1:1===(a.annotationsLoadPolicy||b.annotationsLoadPolicy)&&!b.XO||a.W.get(b.videoId)||g.bE(b)||g.cE(b)?!0:!1};
g.h.uC=function(){if(this.B){var a=this.player.Va().getVideoContentRect(!0);g.Em(this.B.element,a.width,a.height);g.Am(this.B.element,a.left,a.top)}if(this.j){var b=this.player.Bk();a=this.j;b=b.width;g.O(a.C,"iv-drawer-small",426>=b);g.O(a.C,"iv-drawer-big",1280<=b)}};
g.h.ZT=function(a){XUa(this,a.state);g.V(a.state,2)&&(this.Oh()&&this.Ll()&&2!==this.player.getPresentingPlayerType()&&this.setCardsVisible(!1),this.Dv(!1))};
g.h.load=function(){function a(k){var l=b.loadNumber;b.C=null;b.loaded&&b.loadNumber===l&&b.player.getVideoData().videoId===d&&(k=g.cr(k)&&k.responseXML?k.responseXML:null)&&(A1(b,k),g.N(b.player.getRootNode(),"iv-module-loaded"))}
var b=this;g.CJ.prototype.load.call(this);XUa(this,this.player.vb());this.loadNumber++;var c=this.player.getVideoData(),d=c.videoId;g.hs()&&(a=ZUa(this,a));var e={format:"XML",onFinish:a,onError:function(){b.C=null},
urlParams:{}};c.isPharma&&(e.urlParams.pharma="1");e.method="POST";e.withCredentials=!0;var f=this.player.S().W.get(d);f&&$Ua(e,f);f=f&&(f.JA||f.ix);if(!c.Um||f)c.Ra?this.C=g.ir(c.Ra,e):(this.Gm=function(){b.onVideoDataChange(e)},this.player.addEventListener("videodatachange",this.Gm));
g.oJ(this.player,this.B.element,4);this.uC();(f=g.bE(c))&&eVa(this,f);(f=g.cE(c))&&f.featuredChannel&&fVa(this,f.featuredChannel,f.annotationId||"branding",c.videoId||null,c.eventId||null)};
g.h.onVideoDataChange=function(a){var b=this.player.getVideoData();b.Ra&&(this.Gm&&(this.player.removeEventListener("videodatachange",this.Gm),this.Gm=null),this.C=g.ir(b.Ra,a))};
g.h.unload=function(){this.player.Kf("annotations_module");for(var a=g.r(Object.keys(this.I)),b=a.next();!b.done;b=a.next())this.I[b.value].destroy();this.J=null;this.j&&(this.j.destroy(),this.j=null,F0(this.player));this.C&&(this.C.abort(),this.C=null);this.I={};this.u.hide();g.CJ.prototype.unload.call(this);this.B.detach();this.Gm&&(this.player.removeEventListener("videodatachange",this.Gm),this.Gm=null)};
g.h.ZP=function(a){a===this.player.getVideoData().videoId&&(this.loaded?aVa(this):this.load())};
g.h.Oh=function(){return!!this.j&&this.j.isAvailable()};
g.h.Ll=function(){return!!this.j&&this.j.B};
g.h.setCardsVisible=function(a,b,c){b=void 0===b?!1:b;this.Oh();this.j&&(a?c?l1(this.j,c,b):l1(this.j,"YOUTUBE_DRAWER_AUTO_OPEN",b):m1(this.j))};
g.h.Dv=function(a,b){this.player.X(a?"cardsteasershow":"cardsteaserhide",b)};
g.h.ea=function(){this.player.S().W.unsubscribe("vast_info_card_add",this.ZP,this);g.rp(this.player.getRootNode(),g.bP.IV_DRAWER_OPEN);for(var a=this.N,b=g.fp,c=0,d=a.length;c<d;c++)b.sj(a[c]);this.N.length=0;g.CJ.prototype.ea.call(this)};
g.h.createElement=function(a){a=new g.W(a);g.H(this,a);return a.element};g.BJ("annotations_module",z1);g.BJ("creatorendscreen",R0);})(_yt_player);
