(function(g){var window=this;'use strict';var F1=function(a,b){return b?a.captionsInitialState:"CAPTIONS_INITIAL_STATE_UNKNOWN"},G1=function(a){return g.xC(a)&&!a.L("web_player_i_see_captions_3_killswitch")},kVa=function(a,b){var c,d,e;
return g.B(function(f){if(1==f.j)return c=a+"|"+b,g.A(f,g.dt(),2);if(3!=f.j){d=f.u;if(!d)throw g.Es("gct");return g.A(f,g.fD(d),3)}e=f.u;return f.return(e.get("captions",c))})},lVa=function(a,b){var c=new g.iD;
c.languageCode=a.languageCode;c.languageName=a.languageName;c.name=a.name;c.kind=a.kind;c.isDefault=!1;c.j=a.j;c.isTranslateable=a.isTranslateable;c.vssId=a.vssId;c.url=a.url;c.translationLanguage=b;return c},mVa=function(a,b,c){kVa(a,b).then(function(d){d&&c(d.trackData,new g.iD(d.metadata))})},H1=function(){this.segments=[]},nVa=function(a,b){var c=g.hc(a.segments,b);
0<=c||0>c&&1===(-c-1)%2||(c=-c-1,0<c&&1===b-a.segments[c-1]&&c<a.segments.length&&1===a.segments[c]-b?(g.Yb(a.segments,c),g.Yb(a.segments,c-1)):0<c&&1===b-a.segments[c-1]?a.segments[c-1]=b:c<a.segments.length&&1===a.segments[c]-b?a.segments[c]=b:(g.ec(a.segments,c,0,b),g.ec(a.segments,c+1,0,b)))},I1=function(a,b,c,d,e,f){g.G.call(this);
this.policy=a;this.player=b;this.W=c;this.N=d;this.D=e;this.V=f;this.U=this.player.S();this.C=new H1;this.I=-1;this.B=this.u=this.j=null;this.J=new g.L(this.JO,1E3,this);this.events=new g.Uz(this);g.H(this,this.J);g.H(this,this.events);this.events.P(b,"SEEK_COMPLETE",this.wC);this.wC();this.JO()},oVa=function(a){return a.j&&a.j.C?a.j.C+a.player.xd()<a.player.getCurrentTime():!1},pVa=function(a,b){var c=g.Ty(g.pz(b,a.policy,{})),d={format:"RAW",
withCredentials:!0};a.D&&(d.responseType="arraybuffer");a.B=g.lr(c,d,3,100).then(function(e){a:{e=e.xhr;a.isDisposed();if(a.u){var f=!(a.D?e.response:e.responseText)||400<=e.status,k=g.$sa(e);if(k){e=g.pz(a.u,a.policy,{});a.u.Ek(e,k);pVa(a,a.u);break a}f?a.player.qa("capfail",{status:e.status}):(k=a.u.j[0].Ga,null!=a.N&&a.I!==k&&(f=a.u.j[0],a.D?a.N(e.response,1E3*(f.startTime+a.player.xd())):a.N(e.responseText,1E3*(f.startTime+a.player.xd())),a.I=k))}a.u=null;a.B=null}}).Di(function(e){a.u=null;
a.B=null;var f;a.player.qa("capfail",{status:null==(f=e.xhr)?void 0:f.status})});
a.u=b;nVa(a.C,a.u.j[0].Ga)},J1=function(a,b){g.QJ.call(this,b.S());
this.j=a;this.G=b;this.B=null;this.D=!1;this.I=g.zC(this.G.S())&&!this.j.isManifestless},rVa=function(a,b){var c=[],d;
for(d in a.j.j)if(a.j.j.hasOwnProperty(d)){var e=a.j.j[d];if(g.SJ(e,b||null)){var f=e.info.id,k=f,l="."+f,m="";if(e=e.info.captionTrack)f=e.languageCode,k=e.displayName,l=e.vssId,m=e.kind;else{e=f;var n=g.CTa.get(e);null==n&&(n=qVa[e]||qVa[e.replace(/-/g,"_")],g.CTa.set(e,n));k=n||k}c.push(new g.iD({id:d,languageCode:f,languageName:k,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:l,kind:m}))}}return c},sVa=function(a,b){return null!=b&&b in a.j.j?a.j.j[b]:null},tVa=function(a,b,c){var d=
[],e;
for(e in a.j.j)if(a.j.j.hasOwnProperty(e)){var f=a.j.j[e];if(g.SJ(f,c||null)){var k=f.info.captionTrack;k&&k.languageCode===b&&d.push(f)}}return d.length?d[0]:null},K1=function(a){if(!uVa.test(a))throw Error("'"+a+"' is not a valid hex color");
4==a.length&&(a=a.replace(vVa,"#$1$1$2$2$3$3"));a=a.toLowerCase();a=parseInt(a.slice(1),16);return[a>>16,a>>8&255,a&255]},L1=function(a,b,c,d,e,f,k,l){var m={};
Object.assign(m,b);Object.assign(m,a.params);Object.assign(m,c);var n={};Object.assign(n,b.Pd);a.params.Pd&&Object.assign(n,a.params.Pd);Object.assign(n,c.Pd);m.Pd=n;g.W.call(this,{F:"div",K:"caption-window",T:{id:"caption-window-"+a.id,dir:1===m.Mg?"rtl":"ltr",tabindex:"0",lang:m.lang},R:[{F:"span",K:"captions-text",T:{style:"word-wrap: normal; display: block;"}}]});this.D=[];this.ma=!1;this.u=a;this.Da=this.va=null;this.playerWidth=f;this.playerHeight=k;this.I=null;this.maxWidth=.96*f;this.Ra=.96*
k;this.j=m;this.Gb=c;this.Fa=b;this.C=this.ya("captions-text");this.ib=""!==this.C.style.getPropertyValue("box-decoration-break")||""!==this.C.style.getPropertyValue("-webkit-box-decoration-break");this.W=e/360*16;!l.fb("web_player_scale_font_size_for_shorts_killswitch")&&e>=d&&(this.W=f/640*16);this.type=0;this.Ta=this.W*wVa(n);a=new g.Zu(this.element,!0);g.H(this,a);a.subscribe("dragstart",this.cU,this);a.subscribe("dragmove",this.bU,this);a.subscribe("dragend",this.aU,this);this.eb=this.Za=0;b=
"";this.j.windowOpacity&&(a=K1(this.j.windowColor),b="rgba("+a[0]+","+a[1]+","+a[2]+","+this.j.windowOpacity+")");a={"background-color":b,display:!1===this.j.isVisible?"none":"","text-align":xVa[this.j.textAlign]};this.ib&&(a["border-radius"]=b?this.Ta/8+"px":"");if(this.B=2===this.u.params.Mg||3===this.u.params.Mg)b=this.element,c="vertical-rl",1===this.j.vJ&&(c="vertical-lr"),g.Fc&&(c="vertical-lr"===c?"tb-lr":"tb-rl"),g.um(b,"-o-writing-mode",c),g.um(b,"-webkit-writing-mode",c),g.um(b,"writing-mode",
c),g.um(b,"text-orientation","upright"),g.N(b,"ytp-vertical-caption"),3===this.u.params.Mg&&(g.um(b,"text-orientation",""),g.um(b,"transform","rotate(180deg)"));g.um(this.element,a);switch(this.j.rj){case 0:case 1:case 2:g.N(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.N(this.element,"ytp-caption-window-bottom")}},wVa=function(a){var b=1+.25*(a.fontSizeIncrement||0);
if(0===a.offset||2===a.offset)b*=.8;return b},yVa=function(a,b){var c={},d=b.background?b.background:a.j.Pd.background;
if(null!=b.backgroundOpacity||b.background){var e=null!=b.backgroundOpacity?b.backgroundOpacity:a.j.Pd.backgroundOpacity;d=K1(d);c.background="rgba("+d[0]+","+d[1]+","+d[2]+","+e+")";a.ib&&(c["box-decoration-break"]="clone",c["border-radius"]=a.Ta/8+"px")}if(null!=b.fontSizeIncrement||null!=b.offset)c["font-size"]=a.W*wVa(b)+"px";d=1;e=b.color||a.j.Pd.color;if(b.color||null!=b.textOpacity)e=K1(e),d=null==b.textOpacity?a.j.Pd.textOpacity:b.textOpacity,e="rgba("+e[0]+","+e[1]+","+e[2]+","+d+")",c.color=
e,c.fill=e;var f=b.charEdgeStyle;0===f&&(f=void 0);if(f){e="rgba(34, 34, 34, "+d+")";var k="rgba(204, 204, 204, "+d+")";b.sF&&(k=e=b.sF);var l=a.W/16/2,m=Math.max(l,1),n=Math.max(2*l,1),p=Math.max(3*l,1),q=Math.max(5*l,1);d=[];switch(f){case 4:for(;p<=q;p+=l)d.push(n+"px "+n+"px "+p+"px "+e);break;case 1:n=2<=window.devicePixelRatio?.5:1;for(f=m;f<=p;f+=n)d.push(f+"px "+f+"px "+e);break;case 2:d.push(m+"px "+m+"px "+k);d.push("-"+m+"px -"+m+"px "+e);break;case 3:for(p=0;5>p;p++)d.push("0 0 "+n+"px "+
e)}c["text-shadow"]=d.join(", ")}e="";switch(b.fontFamily){case 1:e='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:e='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:e='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:e='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:e='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:e=g.zr()?'"Carrois Gothic SC", sans-serif-smallcaps':
'"Arial Unicode Ms", Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:e='"YouTube Noto", Roboto, "Arial Unicode Ms", Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}e&&(c["font-family"]=e);e=b.offset;null==e&&(e=a.j.Pd.offset);switch(e){case 0:c["vertical-align"]="sub";break;case 2:c["vertical-align"]="super"}7===b.fontFamily&&(c["font-variant"]="small-caps");b.bold&&(c["font-weight"]="bold");b.Hk&&(c["font-style"]="italic");b.underline&&(c["text-decoration"]="underline");
b.uW&&(c.visibility="hidden");1===b.cO&&a.B&&(c["text-combine-upright"]="all",c["text-orientation"]="mixed",e=g.EC||g.Cs,3===a.u.params.Mg?c.transform=e?"rotate(90deg)":"rotate(180deg)":e&&(c.transform="rotate(-90deg)"));if(1===b.Zk||2===b.Zk||3===b.Zk||4===b.Zk||5===b.Zk)if(g.EC)c["font-weight"]="bold";else switch(c["text-emphasis-style"]="filled circle",c["text-emphasis-color"]="currentcolor",c["webkit-text-emphasis"]="filled circle",b.Zk){case 4:case 3:c["text-emphasis-position"]="under left";
c["webkit-text-emphasis-position"]="under left";break;case 5:case 2:c["text-emphasis-position"]="over right",c["webkit-text-emphasis-position"]="over right"}return c},zVa=function(a){a.I=g.Oh("SPAN");
g.um(a.I,{display:"block"});g.N(a.I,"caption-visual-line");a.C.appendChild(a.I)},AVa=function(a,b){var c=g.Oh("SPAN");
g.um(c,{display:"inline-block","white-space":"pre-wrap"});g.um(c,yVa(a,b));c.classList.add("ytp-caption-segment");a.I.appendChild(c);c.previousElementSibling&&(g.um(c.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.um(c,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return c},BVa=function(a,b,c){a.ma=a.ma||!!c;
var d={};Object.assign(d,a.j.Pd);Object.assign(d,c||b.j);Object.assign(d,a.Gb.Pd);(c=!a.I)&&zVa(a);for(var e=a.va&&a.Da&&g.Uf(d,a.Da)?a.va:AVa(a,d),f="string"===typeof b.text,k=f?b.text.split("\n"):[b.text],l=0;l<k.length;l++){var m=0<l||!b.append,n=k[l];m&&!c?(zVa(a),e=AVa(a,d)):m&&c&&(c=!1);n&&(e.appendChild(f?g.Ph(n):n),f||"RUBY"!==n.tagName||4!==n.childElementCount||g.EC||!g.wm(n.children[2],"text-emphasis")||(m=a.B?"padding-right":"padding-top",g.wm(n.children[2],"text-emphasis-position")&&(m=
a.B?"padding-left":"padding-bottom"),g.vf?g.um(e,m,"1em"):g.um(e,m,"0.5em")))}a.Da=d;a.va=e;a.D.push(b)},M1=function(a,b,c,d){g.QJ.call(this,a);
this.videoData=b;this.audioTrack=c;this.Pa=d;this.C=b.Uw},N1=function(a,b,c,d,e,f,k,l){L1.call(this,a,b,c,d,e,f,k,l);
this.type=1},O1=function(a,b,c,d,e,f,k,l){L1.call(this,a,b,c,d,e,f,k,l);
this.type=2;this.J=[];this.V=this.N=this.Ia=0;this.Y=NaN;this.gb=0;this.Fb=null;this.Qa=new g.L(this.tZ,433,this);g.N(this.element,"ytp-caption-window-rollup");g.H(this,this.Qa);g.um(this.element,"overflow","hidden")},CVa=function(a,b){if(!b)return"";
a.B&&1!==a.u.params.vJ&&(b*=-1);return"translate"+(a.B?"X":"Y")+"("+b+"px)"},DVa=function(a){a.J=Array.from(document.getElementsByClassName("caption-visual-line"));
for(var b=a.u.params.Xn,c=0,d=0,e=a.J.length-1;c<b&&-1<e;){var f=a.J[e];d+=a.B?f.offsetWidth:f.offsetHeight;c++;e--}a.J.length<b&&(d*=b/a.J.length);a.N=d;b=Math;c=b.max;isNaN(a.Y)&&((d=a.j.Qo)?(e=g.Oh("SPAN"),g.Wh(e,"\u2013".repeat(d)),g.um(e,yVa(a,a.j.Pd)),a.C.appendChild(e),a.Y=e.offsetWidth,a.C.removeChild(e)):a.Y=0);d=a.C;a.V=c.call(b,a.Y,a.gb,(a.B?d.offsetHeight:d.offsetWidth)+1)},EVa=function(a,b){DVa(a);
var c=a.J.reduce(function(e,f){return(a.B?f.offsetWidth:f.offsetHeight)+e},0);
c=a.N-c;if(c!==a.Ia){var d=0<c&&0===a.Ia;b||isNaN(c)||d||(g.N(a.element,"ytp-rollup-mode"),g.jp(a.Qa));g.um(a.C,"transform",CVa(a,c));a.Ia=c}DVa(a)},P1=function(a,b,c,d,e,f,k){f=void 0===f?!1:f;
k=void 0===k?null:k;g.tw.call(this,a,a+b,{priority:c,namespace:"captions"});this.windowId=d;this.text=e;this.append=f;this.j=k},Q1=function(a,b,c,d,e){g.tw.call(this,a,a+b,{priority:c,
namespace:"captions"});this.id=d;this.params=e;this.j=[]},FVa=function(a){var b="_"+R1++;
return new Q1(0,0x8000000000000,0,b,a)},HVa=function(a,b,c,d,e,f,k){var l=f[0],m=k[l.getAttribute("p")];
if(1===m.We){var n=f[1],p=f[2];f=f[3];l.getAttribute("t");n.getAttribute("t");p.getAttribute("t");f.getAttribute("t");l.getAttribute("p");n.getAttribute("p");f.getAttribute("p");k=k[p.getAttribute("p")];l=GVa(l.textContent,n.textContent,p.textContent,f.textContent,k);return new P1(a,b,e,c,l,d,m)}switch(m.We){case 9:case 10:m.Zk=1;break;case 11:m.Zk=2;break;case 12:m.Zk=3;break;case 13:m.Zk=4;break;case 14:m.Zk=5}return new P1(a,b,e,c,l.textContent||"",d,m)},GVa=function(a,b,c,d,e){var f=g.zr(),k=
f?g.Oh("DIV"):g.Oh("RUBY"),l=g.Oh("SPAN");
l.textContent=a;k.appendChild(l);a=f?g.Oh("DIV"):g.Oh("RP");a.textContent=b;k.appendChild(a);b=f?g.Oh("DIV"):g.Oh("RT");b.textContent=c;k.appendChild(b);c=e.We;if(10===c||11===c||12===c||13===c||14===c)if(g.um(b,"text-emphasis-style","filled circle"),g.um(b,"text-emphasis-color","currentcolor"),g.um(b,"webkit-text-emphasis","filled circle"),11===e.We||13===e.We)g.um(b,"webkit-text-emphasis-position","under left"),g.um(b,"text-emphasis-position","under left");c=!0;if(4===e.We||7===e.We||12===e.We||
14===e.We)g.um(k,"ruby-position","over"),g.um(k,"-webkit-ruby-position","before");else if(5===e.We||6===e.We||11===e.We||13===e.We)g.um(k,"ruby-position","under"),g.um(k,"-webkit-ruby-position","after"),c=!1;e=f?g.Oh("DIV"):g.Oh("RP");e.textContent=d;k.appendChild(e);f&&(d=c,g.um(k,{display:"inline-block",position:"relative"}),f=k.firstElementChild.nextElementSibling,g.um(f,"display","none"),f=f.nextElementSibling,g.um(f,{"font-size":"0.5em","line-height":"1.2em","text-align":"center",position:"absolute",
left:"50%",transform:"translateX(-50%)",width:"400%"}),g.um(k.lastElementChild,"display","none"),d?(g.um(k,"padding-top","0.6em"),g.um(f,"top","0")):(g.um(k,"padding-bottom","0.6em"),g.um(f,"bottom","0")));return k},S1=function(){g.G.apply(this,arguments)},T1=function(a){S1.call(this);
this.C=a;this.pens={};this.N={};this.V={};this.D="_"+R1++;this.J={};this.B=this.j=null;this.I=!0},U1=function(a,b){a=a.getAttribute(b);
if(null!=a)return Number(a)},V1=function(a,b){a=a.getAttribute(b);
if(null!=a)return"1"===a},W1=function(a,b){a=U1(a,b);
return void 0!==a?a:null},Y1=function(a,b){a=a.getAttribute(b);
if(null!=a)return X1.test(a),a},IVa=function(a,b){var c={},d=b.getAttribute("ws");
Object.assign(c,d?a.V[d]:a.C);a=W1(b,"mh");null!=a&&(c.Xu=a);a=W1(b,"ju");null!=a&&(c.textAlign=a);a=W1(b,"pd");null!=a&&(c.Mg=a);a=W1(b,"sd");null!=a&&(c.vJ=a);a=Y1(b,"wfc");null!=a&&(c.windowColor=a);b=U1(b,"wfo");void 0!==b&&(c.windowOpacity=b/255);return c},JVa=function(a,b){var c={},d=b.getAttribute("wp");
d&&Object.assign(c,a.N[d]);a=W1(b,"ap");null!=a&&(c.rj=a);a=U1(b,"cc");null!=a&&(c.Qo=a);a=U1(b,"ah");null!=a&&(c.ji=a);a=U1(b,"rc");null!=a&&(c.Xn=a);b=U1(b,"av");null!=b&&(c.al=b);return c},KVa=function(a,b,c,d){var e={};
Object.assign(e,JVa(a,b));Object.assign(e,IVa(a,b));d?g.Uf(e,a.C)?(d=a.D,e=a.C):d="_"+R1++:d=b.getAttribute("id")||"_"+R1++;a=U1(b,"t")+c;b=U1(b,"d")||0x8000000000000;if(2===e.Mg||3===e.Mg)c=e.Xn,e.Xn=e.Qo,e.Qo=c;return new Q1(a,b,0,d,e)},Z1=function(a){S1.call(this);
this.I=a;this.j=new Map;this.C=new Map;this.D=new Map;this.B=new Map},$1=function(a){a=g.oh(Math.round(a),0,16777215).toString(16).toUpperCase();
return"#000000".substr(0,7-a.length)+a},LVa=function(a,b,c,d,e){0===d&&(d=0x8000000000000);
var f={};b.wpWinPosId&&Object.assign(f,a.C.get(b.wpWinPosId));b.wsWinStyleId&&Object.assign(f,a.D.get(b.wsWinStyleId));a=b.rcRowCount;void 0!==a&&(f.Xn=a);b=b.ccColCount;void 0!==b&&(f.Qo=b);if(2===f.Mg||3===f.Mg)b=f.Xn,f.Xn=f.Qo,f.Qo=b;return new Q1(c,d,0,e,f)},b2=function(){this.B=this.time=this.mode=this.u=0;
this.C=new a2(this);this.D=new a2(this);this.j=[];this.clear()},NVa=function(a,b,c){if(255===a&&255===b||!a&&!b)return{Sq:a,
No:b,result:0};a=MVa[a];b=MVa[b];if(a&128){var d;if(d=!(b&128))d=b,d=c.isValid()&&c.No===d;if(d)return{Sq:a,No:b,result:1}}else if(b&128&&1<=a&&31>=a)return{Sq:a,No:b,result:2};return{Sq:a,No:b,result:3}},PVa=function(a,b,c,d){255===b&&255===c||!b&&!c?(45===++a.B&&a.reset(),a.C.u.clear(),a.D.u.clear()):(a.B=0,OVa(a.C,b,c,d))},QVa=function(a,b){a.j.sort(function(e,f){var k=e.time-f.time;
return 0===k?e.order-f.order:k});
for(var c=g.r(a.j),d=c.next();!d.done;d=c.next())d=d.value,a.time=d.time,0===d.type?PVa(a,d.DM,d.EM,b):1===d.type&&a.u&496&&OVa(a.D,d.DM,d.EM,b);a.j.length=0},c2=function(){this.type=0},d2=function(){this.state=this.No=this.Sq=0},RVa=function(){this.timestamp=this.j=0},e2=function(a){this.D=a;
this.B=[];this.j=this.u=this.row=0;this.style=new c2;for(a=this.C=0;15>=a;a++){this.B[a]=[];for(var b=0;32>=b;b++)this.B[a][b]=new RVa}},f2=function(a,b){if(3===a.style.type){for(var c=0,d=0,e=a.D.time+0,f="",k="",l=e,m=1;15>=m;++m){for(var n=!1,p=d?d:1;32>=p;++p){var q=a.B[m][p];
if(0!==q.j){0===c&&(c=m,d=p);n=String.fromCharCode(q.j);var t=q.timestamp;t<e&&(e=t);q.timestamp=l;k&&(f+=k,k="");f+=n;n=!0}if((0===q.j||32===p)&&n){k="\n";break}else if(d&&!n)break}if(c&&!n)break}f&&b.C(c,d,e,l,f)}else for(d=c=0,f=e=a.D.time+0,k=1;15>=k;++k)for(l="",m=1;32>=m;++m)if(p=a.B[k][m],q=p.j,0!==q&&(0===c&&(c=k,d=m),n=String.fromCharCode(q),t=p.timestamp,t<=e&&(e=t),l+=n,p.reset()),32===m||0===q)l&&b.C(c,d,e,f,l),e=f,l="",d=c=0},WVa=function(a,b){switch(a){case 0:return SVa[(b&127)-32];
case 1:return TVa[b&15];case 2:return UVa[b&31];case 3:return VVa[b&31]}return 0},g2=function(a){return a.B[a.row][a.u]},h2=function(a,b,c){2<=b&&1<a.u&&(--a.u,g2(a).j=0);
var d=g2(a);d.timestamp=a.D.time+0;d.j=WVa(b,c);32>a.u&&a.u++},XVa=function(a,b,c,d){for(var e=0;e<d;e++)for(var f=0;32>=f;f++){var k=a.B[b+e][f],l=a.B[c+e][f];
k.j=l.j;k.timestamp=l.timestamp}},i2=function(a,b,c){for(var d=0;d<c;d++)for(var e=0;32>=e;e++)a.B[b+d][e].reset()},j2=function(a){a.row=0<a.j?a.j:1;
a.u=1;i2(a,0,15)},k2=function(a){this.B=a;
this.D=0;this.style=new c2;this.I=new e2(this.B);this.J=new e2(this.B);this.text=new e2(this.B);this.u=this.I;this.C=this.J;this.j=this.u},l2=function(a,b,c){var d=a.u,e=!1;
switch(a.style.get()){case 4:case 1:case 2:4===a.style.get()&&0<d.j||(f2(d,c),j2(a.u),j2(a.C),d.row=15,d.j=b,e=!0)}a.style.set(3);a.j=d;a.j.style=a.style;a.B.mode=1<<d.C;e?d.u=1:d.j!==b&&(d.j>b?(f2(d,c),i2(d,d.row-d.j,b)):d.row<b&&(b=d.j),d.j=b)},YVa=function(a){a.style.set(1);
a.j=a.C;a.j.j=0;a.j.style=a.style;a.B.mode=1<<a.j.C},ZVa=function(a){a.style.set(4);
a.j=a.text;a.j.style=a.style;a.B.mode=1<<a.j.C},a2=function(a){this.j=a;
this.D=0;this.B=new k2(this.j);this.I=new k2(this.j);this.u=new d2;this.C=this.B},OVa=function(a,b,c,d){a.u.update();
b=NVa(b,c,a.u);switch(b.result){case 0:return;case 1:case 2:return}var e=b.Sq;c=b.No;if(32<=e||!e)a.j.mode&a.j.u&&(b=e,b&128&&(b=127),c&128&&(c=127),a=a.C.j,b&96&&h2(a,0,b),c&96&&h2(a,0,c),0!==b&&0!==c&&3===a.style.type&&f2(a,d));else if(e&16)a:if(!a.u.matches(e,c)&&(b=a.u,b.Sq=e,b.No=c,b.state=2,b=e&8?a.I:a.B,a.C=b,a.j.mode=1<<(a.D<<2)+(b.D<<1)+(4===b.style.type?1:0),(a.j.mode|1<<(a.D<<2)+(b.D<<1)+(4!==b.style.type?1:0))&a.j.u))if(c&64){d=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(e&7)<<1|c>>5&1];
a=c&16?4*((c&14)>>1):0;c=b.j;switch(b.style.get()){case 4:d=c.row;break;case 3:if(d!==c.row){if(d<c.j&&(d=c.j,d===c.row))break;var f=1+c.row-c.j,k=1+d-c.j;XVa(c,k,f,c.j);b=f;e=c.j;k<f?(f=k+e-f,0<f&&(b+=f,e-=f)):(f=f+e-k,0<f&&(e-=f));i2(c,b,e)}}c.row=d;c.u=a+1}else switch(e&7){case 1:switch(c&112){case 32:h2(b.j,0,32);break a;case 48:57===c?(d=b.j,g2(d).j=0,32>d.u&&d.u++):h2(b.j,1,c&15)}break;case 2:c&32&&h2(b.j,2,c&31);break;case 3:c&32&&h2(b.j,3,c&31);break;case 4:case 5:if(32<=c&&47>=c)switch(c){case 32:YVa(b);
break;case 33:d=b.j;1<d.u&&(--d.u,g2(d).j=0);break;case 36:d=b.j;b=g2(d);for(a=0;15>=a;a++)for(c=0;32>=c;c++)if(d.B[a][c]===b){for(;32>=c;c++)d.B[a][c].reset();break}break;case 37:l2(b,2,d);break;case 38:l2(b,3,d);break;case 39:l2(b,4,d);break;case 40:h2(b.j,0,32);break;case 41:b.style.set(2);b.j=b.u;b.j.j=0;b.j.style=b.style;b.B.mode=1<<b.j.C;break;case 42:d=b.text;d.j=15;d.style.set(4);j2(d);ZVa(b);break;case 43:ZVa(b);break;case 44:a=b.u;switch(b.style.get()){case 1:case 2:case 3:f2(a,d)}i2(a,
0,15);break;case 45:b:{a=b.j;switch(b.style.get()){default:case 2:case 1:break b;case 4:if(15>a.row){++a.row;a.u=1;break b}case 3:}2>a.j&&(a.j=2,a.row<a.j&&(a.row=a.j));b=a.row-a.j+1;f2(a,d);XVa(a,b,b+1,a.j-1);i2(a,a.row,1)}break;case 46:i2(b.C,0,15);break;case 47:f2(b.u,d),b.C.updateTime(b.B.time+0),d=b.C,b.C=b.u,b.u=d,YVa(b)}break;case 7:switch(c){case 33:case 34:case 35:d=b.j,32<(d.u+=c&3)&&(d.u=32)}}},$Va=function(){},m2=function(a,b,c){this.trackData=a;
this.I=c;this.version=this.D=this.B=this.byteOffset=0;this.j=new DataView(this.trackData);this.u=[]},n2=function(a){var b=a.byteOffset;
a.byteOffset+=1;return a.j.getUint8(b)},o2=function(a){var b=a.byteOffset;
a.byteOffset+=4;return a.j.getUint32(b)},p2=function(a,b){S1.call(this);
this.B=a;this.C=b;this.track="CC3"===this.C.languageName?4:0;this.j=new b2;this.j.u=1<<this.track},q2=function(a){if("string"===typeof a)return!1;
a=new m2(a,8,0);return aWa(a)},aWa=function(a){if(!(a.byteOffset<a.j.byteLength)||1380139777!==o2(a))return!1;
a.version=n2(a);if(1<a.version)return!1;n2(a);n2(a);n2(a);return!0},r2=function(){S1.call(this)},bWa=function(a,b,c,d,e,f,k,l,m){switch(k.tagName){case "b":l.bold=!0;
break;case "i":l.Hk=!0;break;case "u":l.underline=!0}for(var n=0;n<k.childNodes.length;n++){var p=k.childNodes[n];if(3===p.nodeType)p=new P1(b,c,d,e.id,p.nodeValue,f||0<n,g.Qf(l)?void 0:l),m.push(p),e.j.push(p);else{var q={};Object.assign(q,l);bWa(a,b,c,d,e,!0,p,q,m)}}},s2=function(a){var b=a.split(":");
a=0;b=g.r(b);for(var c=b.next();!c.done;c=b.next())a=60*a+Number(c.value);return 1E3*a},cWa=function(a,b,c,d){d=Object.assign({Xu:0},d);
return new Q1(a,b,c,"_"+R1++,d)},t2=function(a,b){g.G.call(this);
this.G=a;this.U=b;this.j=null;this.u=this.G.qB()},iWa=function(a,b,c,d,e){d=d||0;
e=e||0;if(a.u&&b){var f=e,k=dWa(a,b,d),l=[];try{for(var m=g.r(k),n=m.next();!n.done;n=m.next()){var p=n.value,q=p.trackData,t=p.mJ;l="string"!==typeof q?l.concat(eWa(a,c,q,t,f)):"WEBVTT"===q.substring(0,6)?l.concat(fWa(a,q,t)):l.concat(gWa(a,c,q,t))}var v=l}catch(x){g.S(x),a.clear(),v=[]}if(0!==v.length)return v}b=hWa(b);if(!b)return[];try{return"string"!==typeof b?eWa(a,c,b,d,e):"WEBVTT"===b.substring(0,6)?fWa(a,b,d):gWa(a,c,b,d)}catch(x){return g.S(x),a.clear(),[]}},hWa=function(a){if("string"===
typeof a||q2(a))return a;
var b=new DataView(a);if(8>=b.byteLength||1718909296!==b.getUint32(4))return"";b=g.ty(b,0,1835295092);if(!b||!b.size)return"";a=new Uint8Array(a,b.dataOffset,b.size-(b.dataOffset-b.offset));return g.fy(a)},dWa=function(a,b,c){if("string"===typeof b||q2(b))return[{trackData:b,
mJ:c}];var d=new DataView(b);if(8>=d.byteLength||1718909296!==d.getUint32(4))return[];var e=g.Pra(d);if(a.u&&e){var f=g.Ira(e);e=e.j;f&&e&&a.u.Mz(e,f)}f=g.Dy(d,1835295092);if(!f||!f.length||!f[0].size)return[];a=[];f=g.r(f.entries());for(e=f.next();!e.done;e=f.next()){var k=g.r(e.value);e=k.next().value;k=k.next().value;k=new Uint8Array(b,k.dataOffset,k.size-(k.dataOffset-k.offset));k=g.fy(k);a.push({trackData:k,mJ:c+1E3*e})}jWa(d,a,c);return a=a.filter(function(l){return!!l.trackData})},jWa=function(a,
b,c){var d=g.ty(a,0,1836476516),e=9E4;
d&&(e=g.uy(d)||9E4);d=0;var f=g.Dy(a,1836019558);f=g.r(f.entries());for(var k=f.next();!k.done;k=f.next()){var l=g.r(k.value);k=l.next().value;l=l.next().value;k<b.length&&(l=g.ty(a,l.dataOffset,1953653094))&&(l=g.ty(a,l.dataOffset,1952867444))&&(l=g.By(l)/e*1E3,0===k&&(d=l),b[k].mJ=l-d+c||c*k*1E3)}},eWa=function(a,b,c,d,e){if(!q2(c))throw Error("Invalid binary caption track data");
a.j||(a.j=new p2(e,b));return a.j.u(c,d)},fWa=function(a,b,c){a.j||(a.j=new r2);
a=a.j.u(b,c);.01>Math.random()&&g.uv(Error("Deprecated subtitles format in web player: WebVTT"));return a},gWa=function(a,b,c,d){if("{"===c[0])try{return a.j||(a.j=new Z1(kWa(b))),a.j.u(c,d)}catch(f){return g.S(f),[]}var e=g.WZ(c);
if(!e||!e.firstChild)throw a=Error("Invalid caption track data"),a.params=c,a;if("timedtext"===e.firstChild.tagName){if(3===Number(e.firstChild.getAttribute("format")))return a.j||(a.j=new T1(kWa(b),a.U)),a.j.u(e,d);a=Error("Unsupported subtitles format in web player (Format2)");a.params=c;throw a;}if("transcript"===e.firstChild.tagName)throw a=Error("Unsupported subtitles format in web player (Format1)"),a.params=c,a;a=Error("Invalid caption track data");a.params=c;throw a;},kWa=function(a){var b=
{};
if(a=g.lD(a))b.lang=a,g.URa.test(a)&&(b.Mg=1);return b},w2=function(a){g.CJ.call(this,a);
var b=this;this.G=a;this.U=this.G.S();this.videoData=this.G.getVideoData();this.eb=this.G.Va();this.C={Pd:{}};this.D={Pd:{}};this.oa=[];this.N={};this.Fa={};this.W=!1;this.Gb=g.jE(this.videoData);this.Ta=g.PBa(this.videoData,this.G);this.Fb=!!this.videoData.captionTracks.length;this.Sb=!!this.videoData.Kc;this.Ia="3"===this.U.controlsType;this.u=this.I=this.J=this.Da=this.Za=null;this.Qa=new t2(this.G,this.U);this.j=null;this.Y=new g.Uz(this);this.Ra=new g.W({F:"div",K:"ytp-caption-window-container",
T:{id:"ytp-caption-window-container"}});var c=null,d=g.Xp("yt-html5-player-modules::subtitlesModuleData");d&&(c=new g.Lp(d));this.storage=c;var e;this.gb=!(null==(e=a.Id())||!e.Fz());this.B=lWa(this);this.V=!this.B&&this.Ia&&this.gb&&this.Ta;g.H(this,this.Qa);this.B?this.va=this.ma=null:(this.ma=new g.hp(this.OJ,void 0,this),g.H(this,this.ma),this.va=new g.L(this.I_,2E3,this),g.H(this,this.va));g.H(this,this.Y);this.U.L("caption_window_container_killswitch")||g.oJ(this.player,this.Ra.element,4);g.H(this,
this.Ra);this.B||this.Y.P(a,"resize",this.QJ);(this.ib=!g.Ou()&&!this.G.isFullscreen()&&!this.B&&!this.V&&!this.U.L("switch_captions_to_track_tag_when_fullscreen_api_unavailable_killswitch"))&&this.Y.P(a,"resize",this.CY);this.Y.P(a,"onPlaybackAudioChange",this.RX);this.Y.P(a,g.vw("captions"),function(f){b.onCueRangeEnter(f)});
this.Y.P(a,g.ww("captions"),function(f){b.onCueRangeExit(f)});
u2(this,v2(this)||{})},oWa=function(a){if(1===a.U.Ta||1===a.videoData.lw||"alwayson"===g.UD(a.videoData,"yt:cc"))return!0;
if(a.videoData.captionTracks.length)var b=a.player.getAudioTrack().u;if(2===a.U.Ta){var c;g.BC(a.U)?c=mWa(a):c=nWa(a,"module-enabled");if(null!=c)return!!c}c=F1(a.player.getAudioTrack(),G1(a.U));var d=g.UD(a.videoData,"yt:cc");if(void 0===x2(a)){if("CAPTIONS_INITIAL_STATE_ON_RECOMMENDED"===c)return d?"on"===d:!0;if("CAPTIONS_INITIAL_STATE_OFF_RECOMMENDED"===c)return"on"===d}else return"on"===d;return"ON"===b||"on"===g.UD(a.videoData,"yt:cc")},y2=function(a,b){if(a.j&&(void 0===b||!b)||!a.videoData.captionTracks.length)return!1;
a=a.player.getAudioTrack();return!!a.j||"FORCED_ON"===a.u},x2=function(a){var b=void 0,c=g.Xr(g.Wr.getInstance(),65);
if(g.BC(a.U)&&null!=c){if(null!=mWa(a))return!1;b=!c}return b},pWa=function(a){var b;
a.Gb?b=new M1(a.U,a.videoData,a.player.getAudioTrack(),a.player):a.Ta?b=new J1(a.videoData.j,a.player):a.Fb?b=new g.RJ(a.U,a.videoData,a.player.getAudioTrack()):b=new g.TJ(a.U,a.videoData.Kc,a.videoData.videoId,g.Ewa(a.videoData),a.videoData.ql);return b},A2=function(a,b){if(a.u){if(a.I&&a.I.C)return a.I.C;
b||(b=a.Sb?!1:a.Fb?!1:!0);b=g.OJ(a.u.u,b);for(var c=[a.videoData.captionsLanguagePreference,a.U.captionsLanguagePreference,g.UD(a.videoData,"yt:cc_default_lang")],d=0;d<c.length;d++)for(var e=0;e<b.length;e++)if(g.lD(b[e])===c[d])return b[e];return a.I&&a.I.B?a.I.B:(c=b.find(function(f){return f.isDefault}))?c:b[0]||z2(a)}return null},z2=function(a){return a.I&&a.I.j},B2=function(a){var b=z2(a);
return!!b&&a.j===b},qWa=function(a){var b=F1(a.player.getAudioTrack(),G1(a.U)),c;
"CAPTIONS_INITIAL_STATE_ON_REQUIRED"===b?c=A2(a,a.W):"CAPTIONS_INITIAL_STATE_OFF_REQUIRED"===b&&y2(a)?c=z2(a):x2(a)||a.W||oWa(a)?c=A2(a,a.W):y2(a)&&(c=z2(a));if(a.B||a.V){var d=g.OJ(a.u.u,!0);b=[];for(var e=0;e<d.length;e++){var f=d[e],k=g.Oh("TRACK");k.setAttribute("kind","subtitles");k.setAttribute("label",g.jD(f));k.setAttribute("srclang",g.lD(f));k.setAttribute("id",f.toString());a.V||k.setAttribute("src",a.u.yr(f,"vtt"));f===c&&k.setAttribute("default","1");b.push(k)}c=a.G.Id();c.Yw(b);c=c.jf();
a.gb&&a.Y.P(c.textTracks,"change",a.a_)}else!a.j&&c&&C2(a,c),a.player.La("onCaptionsTrackListChanged"),a.player.La("onApiChange")},rWa=function(a,b){var c=a.G.Id().jf().textTracks;
a=a.j.toString();for(var d=0;d<c.length;d++){var e=c[d];e.id===a&&(b?"showing"!==e.mode&&(e.mode="showing"):"showing"===e.mode&&(e.mode="disabled"))}},C2=function(a,b,c){a.loaded&&a.unload();
null!=c&&(a.W=c,a.W&&(g.BC(a.U)?D2(a,!!b):E2(a,"module-enabled",!!b)));a.j=b;y2(a)&&(a.j=z2(a));a.load()},tWa=function(a,b){if(b instanceof Q1){var c=a.N[b.id];
c&&c.u!==b&&(c.dispose(),delete a.N[b.id],c=null);c||(c=sWa(a,b))&&(a.N[b.id]=c)}else c=b.windowId,a.Fa[c]||(a.Fa[c]=[]),a.Fa[c].push(b)},uWa=function(a,b){a.U.L("caption_window_container_killswitch")?g.oJ(a.player,b,4):a.Ra.element.appendChild(b)},sWa=function(a,b){var c=a.eb.getVideoContentRect(!0).height,d=a.eb.getVideoContentRect(!0).width;
if(!c||!d)return null;var e=a.j?g.lD(a.j):null;e&&g.URa.test(e)&&(b.params.Mg=1);e=a.eb.getPlayerSize();switch(null!=b.params.Xu?b.params.Xu:1<b.j.length?1:0){case 1:return new N1(b,a.C,a.D,d,c,e.width,e.height,a.U.experiments);case 2:return new O1(b,a.C,a.D,d,c,e.width,e.height,a.U.experiments);default:return new L1(b,a.C,a.D,d,c,e.width,e.height,a.U.experiments)}},u2=function(a,b,c){c=void 0===c?!1:c;
var d=F2.Pd;a.C={};Object.assign(a.C,F2);a.C.Pd={};Object.assign(a.C.Pd,d);a.D={Pd:{}};var e=b.backgroundOverride?a.D:a.C,f=b.background||d.background;X1.test(f);e.Pd.background=f;e=b.colorOverride?a.D:a.C;f=b.color||d.color;X1.test(f);e.Pd.color=f;e=b.windowColorOverride?a.D:a.C;f=b.windowColor||F2.windowColor;X1.test(f);e.windowColor=f;e=b.backgroundOpacityOverride?a.D:a.C;f=b.backgroundOpacity;null==f&&(f=d.backgroundOpacity);e.Pd.backgroundOpacity=f;e=b.fontSizeIncrementOverride?a.D:a.C;f=b.fontSizeIncrement;
null==f&&(f=d.fontSizeIncrement);e.Pd.fontSizeIncrement=f;f=b.fontStyleOverride?a.D:a.C;e=b.fontStyle;null==e&&(e=d.bold&&d.Hk?3:d.bold?1:d.Hk?2:0);f=f.Pd;switch(e){case 1:f.bold=!0;delete f.Hk;break;case 2:delete f.bold;f.Hk=!0;break;case 3:f.bold=!0;f.Hk=!0;break;default:delete f.bold,delete f.Hk}e=b.textOpacityOverride?a.D:a.C;f=b.textOpacity;null==f&&(f=d.textOpacity);e.Pd.textOpacity=f;e=b.windowOpacityOverride?a.D:a.C;f=b.windowOpacity;null==f&&(f=F2.windowOpacity);e.windowOpacity=f;e=b.charEdgeStyleOverride?
a.D:a.C;f=b.charEdgeStyle;null==f&&(f=d.charEdgeStyle);e.Pd.charEdgeStyle=f;e=b.fontFamilyOverride?a.D:a.C;f=b.fontFamily;null==f&&(f=d.fontFamily);e.Pd.fontFamily=f;a.loaded&&a.QJ();c&&(a.U.L("web_player_local_storage_for_captions_setting_killswitch")?E2(a,"display-settings",b):g.Sv("yt-player-caption-display-settings",b,2592E3))},G2=function(a,b,c){b&&!a.J?(b=FVa({Mg:0,
lang:"en"}),a.J=[b,new P1(b.start,b.end-b.start,0,b.id,null!=c?c:"Captions look like this")],a.player.Yd(a.J)):!b&&a.J&&(vWa(a,a.J),a.J=null)},vWa=function(a,b){a.player.Lg(b);
b=g.r(b);for(var c=b.next();!c.done;c=b.next())g.Zb(a.oa,c.value);g.ip(a.ma)},nWa=function(a,b){if(!a.storage)return null;
try{var c=a.storage.get(b)}catch(d){a.storage.remove(b)}return c},E2=function(a,b,c){if(a.storage)try{a.storage.set(b,c)}catch(d){}},D2=function(a,b){a.G.isInline()||g.Sv("yt-player-sticky-caption",b,2592E3)},mWa=function(a){if(!a.G.isInline())return g.Tv("yt-player-sticky-caption")},v2=function(a){return a.U.L("web_player_local_storage_for_captions_setting_killswitch")?nWa(a,"display-settings"):g.Tv("yt-player-caption-display-settings")},lWa=function(a){var b,c=!(null==(b=a.G.Id())||!b.Ez());
return a.Ia&&c&&!a.Ta};
g.qO.prototype.Ix=g.ca(29,function(a){var b=2;this.Fa.has(a)?b=0:g.ZEa(this,a)&&(b=1);return b});
g.XQ.prototype.Ix=g.ca(28,function(a){return this.qd.Ix(a)});
g.qO.prototype.Mz=g.ca(27,function(a,b){this.Da.set(a,b)});
g.XQ.prototype.Mz=g.ca(26,function(a,b){this.qd.Mz(a,b)});
g.hK.prototype.Yt=g.ca(25,function(){for(var a=g.Hh(document,"track",void 0,this.j),b=0;b<a.length;b++)g.Th(a[b])});
g.aO.prototype.Yt=g.ca(24,function(){this.mediaElement.Yt()});
g.hK.prototype.Fz=g.ca(23,function(){return!(!this.j.textTracks||!this.j.textTracks.addEventListener)});
g.aO.prototype.Fz=g.ca(22,function(){return this.mediaElement.Fz()});
g.hK.prototype.Ez=g.ca(21,function(){return!!this.j.textTracks});
g.aO.prototype.Ez=g.ca(20,function(){return this.mediaElement.Ez()});
g.hK.prototype.Yw=g.ca(19,function(a){for(var b=0;b<a.length;b++)this.j.appendChild(a[b])});
g.aO.prototype.Yw=g.ca(18,function(a){this.mediaElement.Yw(a)});
g.QJ.prototype.uI=g.ca(17,function(){return!1});
g.QJ.prototype.Jp=g.ca(16,function(){});
g.RJ.prototype.Jp=g.ca(15,function(a,b,c){var d=this;this.isDisposed();b=this.yr(a,b);this.xo();this.j=g.ir(b,{format:"RAW",onSuccess:function(e){d.j=null;c(e.responseText,a)},
withCredentials:!0})});
g.TJ.prototype.Jp=g.ca(14,function(a,b,c){var d=this;this.isDisposed();b=this.yr(a,b);this.xo();this.j=g.ir(b,{format:"RAW",onSuccess:function(e){d.j=null;c(e.responseText,a)},
withCredentials:!0})});
var qVa={aa:"Afar",ab:"Abkhazian",ace:"Achinese",ach:"Acoli",ada:"Adangme",ady:"Adyghe",ae:"Avestan",aeb:"Tunisian Arabic",af:"Afrikaans",afh:"Afrihili",agq:"Aghem",ain:"Ainu",ak:"Akan",akk:"Akkadian",akz:"Alabama",ale:"Aleut",aln:"Gheg Albanian",alt:"Southern Altai",am:"Amharic",an:"Aragonese",ang:"Old English",anp:"Angika",ar:"Arabic",ar_001:"Arabic (world)",arc:"Aramaic",arn:"Mapuche",aro:"Araona",arp:"Arapaho",arq:"Algerian Arabic",ars:"Najdi Arabic",arw:"Arawak",ary:"Moroccan Arabic",arz:"Egyptian Arabic",
as:"Assamese",asa:"Asu",ase:"American Sign Language",ast:"Asturian",av:"Avaric",avk:"Kotava",awa:"Awadhi",ay:"Aymara",az:"Azerbaijani",az_Cyrl:"Azerbaijani (Cyrillic)",az_Latn:"Azerbaijani (Latin)",ba:"Bashkir",bal:"Baluchi",ban:"Balinese",bar:"Bavarian",bas:"Basaa",bax:"Bamun",bbc:"Batak Toba",bbj:"Ghomala",be:"Belarusian",bej:"Beja",bem:"Bemba",bew:"Betawi",bez:"Bena",bfd:"Bafut",bfq:"Badaga",bg:"Bulgarian",bgn:"Western Balochi",bho:"Bhojpuri",bi:"Bislama",bik:"Bikol",bin:"Bini",bjn:"Banjar",bkm:"Kom",
bla:"Siksika",bm:"Bambara",bn:"Bangla",bo:"Tibetan",bpy:"Bishnupriya",bqi:"Bakhtiari",br:"Breton",bra:"Braj",brh:"Brahui",brx:"Bodo",bs:"Bosnian",bs_Cyrl:"Bosnian (Cyrillic)",bs_Latn:"Bosnian (Latin)",bss:"Akoose",bua:"Buriat",bug:"Buginese",bum:"Bulu",byn:"Blin",byv:"Medumba",ca:"Catalan",cad:"Caddo",car:"Carib",cay:"Cayuga",cch:"Atsam",ccp:"Chakma",ce:"Chechen",ceb:"Cebuano",cgg:"Chiga",ch:"Chamorro",chb:"Chibcha",chg:"Chagatai",chk:"Chuukese",chm:"Mari",chn:"Chinook Jargon",cho:"Choctaw",chp:"Chipewyan",
chr:"Cherokee",chy:"Cheyenne",ckb:"Central Kurdish",ckb_Arab:"Central Kurdish (Arabic)",co:"Corsican",cop:"Coptic",cps:"Capiznon",cr:"Cree",crh:"Crimean Tatar",cs:"Czech",csb:"Kashubian",cu:"Church Slavic",cv:"Chuvash",cy:"Welsh",da:"Danish",dak:"Dakota",dar:"Dargwa",dav:"Taita",de:"German",de_AT:"German (Austria)",de_CH:"German (Switzerland)",del:"Delaware",den:"Slave",dgr:"Dogrib",din:"Dinka",dje:"Zarma",doi:"Dogri",dsb:"Lower Sorbian",dua:"Duala",dum:"Middle Dutch",dv:"Divehi",dyo:"Jola-Fonyi",
dyu:"Dyula",dz:"Dzongkha",dzg:"Dazaga",ebu:"Embu",ee:"Ewe",efi:"Efik",egy:"Ancient Egyptian",eka:"Ekajuk",el:"Greek",elx:"Elamite",en:"English",en_AU:"English (Australia)",en_CA:"English (Canada)",en_GB:"English (United Kingdom)",en_US:"English (United States)",enm:"Middle English",eo:"Esperanto",es:"Spanish",es_419:"Spanish (Latin America)",es_ES:"Spanish (Spain)",es_MX:"Spanish (Mexico)",et:"Estonian",eu:"Basque",ewo:"Ewondo",fa:"Persian",fa_AF:"Persian (Afghanistan)",fan:"Fang",fat:"Fanti",ff:"Fulah",
ff_Adlm:"Fulah (Adlam)",ff_Latn:"Fulah (Latin)",fi:"Finnish",fil:"Filipino",fj:"Fijian",fo:"Faroese",fon:"Fon",fr:"French",fr_CA:"French (Canada)",fr_CH:"French (Switzerland)",frm:"Middle French",fro:"Old French",frr:"Northern Frisian",frs:"Eastern Frisian",fur:"Friulian",fy:"Western Frisian",ga:"Irish",gaa:"Ga",gay:"Gayo",gba:"Gbaya",gd:"Scottish Gaelic",gez:"Geez",gil:"Gilbertese",gl:"Galician",gmh:"Middle High German",gn:"Guarani",goh:"Old High German",gon:"Gondi",gor:"Gorontalo",got:"Gothic",
grb:"Grebo",grc:"Ancient Greek",gsw:"Swiss German",gu:"Gujarati",guz:"Gusii",gv:"Manx",gwi:"Gwich\u02bcin",ha:"Hausa",hai:"Haida",haw:"Hawaiian",he:"Hebrew",hi:"Hindi",hi_Latn:"Hindi (Latin)",hil:"Hiligaynon",hit:"Hittite",hmn:"Hmong",ho:"Hiri Motu",hr:"Croatian",hsb:"Upper Sorbian",ht:"Haitian Creole",hu:"Hungarian",hup:"Hupa",hy:"Armenian",hz:"Herero",ia:"Interlingua",iba:"Iban",ibb:"Ibibio",id:"Indonesian",ie:"Interlingue",ig:"Igbo",ii:"Sichuan Yi",ik:"Inupiaq",ilo:"Iloko","in":"Indonesian",inh:"Ingush",
io:"Ido",is:"Icelandic",it:"Italian",iu:"Inuktitut",iw:"Hebrew",ja:"Japanese",jbo:"Lojban",jgo:"Ngomba",jmc:"Machame",jpr:"Judeo-Persian",jrb:"Judeo-Arabic",jv:"Javanese",ka:"Georgian",kaa:"Kara-Kalpak",kab:"Kabyle",kac:"Kachin",kaj:"Jju",kam:"Kamba",kaw:"Kawi",kbd:"Kabardian",kbl:"Kanembu",kcg:"Tyap",kde:"Makonde",kea:"Kabuverdianu",kfo:"Koro",kg:"Kongo",kgp:"Kaingang",kha:"Khasi",kho:"Khotanese",khq:"Koyra Chiini",ki:"Kikuyu",kj:"Kuanyama",kk:"Kazakh",kkj:"Kako",kl:"Kalaallisut",kln:"Kalenjin",
km:"Khmer",kmb:"Kimbundu",kn:"Kannada",ko:"Korean",kok:"Konkani",kos:"Kosraean",kpe:"Kpelle",kr:"Kanuri",krc:"Karachay-Balkar",krl:"Karelian",kru:"Kurukh",ks:"Kashmiri",ks_Arab:"Kashmiri (Arabic)",ks_Deva:"Kashmiri (Devanagari)",ksb:"Shambala",ksf:"Bafia",ksh:"Colognian",ku:"Kurdish",kum:"Kumyk",kut:"Kutenai",kv:"Komi",kw:"Cornish",ky:"Kyrgyz",la:"Latin",lad:"Ladino",lag:"Langi",lah:"Lahnda",lam:"Lamba",lb:"Luxembourgish",lez:"Lezghian",lg:"Ganda",li:"Limburgish",lkt:"Lakota",ln:"Lingala",lo:"Lao",
lol:"Mongo",loz:"Lozi",lrc:"Northern Luri",lt:"Lithuanian",lu:"Luba-Katanga",lua:"Luba-Lulua",lui:"Luiseno",lun:"Lunda",luo:"Luo",lus:"Mizo",luy:"Luyia",lv:"Latvian",mad:"Madurese",maf:"Mafa",mag:"Magahi",mai:"Maithili",mak:"Makasar",man:"Mandingo",mas:"Masai",mde:"Maba",mdf:"Moksha",mdr:"Mandar",men:"Mende",mer:"Meru",mfe:"Morisyen",mg:"Malagasy",mga:"Middle Irish",mgh:"Makhuwa-Meetto",mgo:"Meta\u02bc",mh:"Marshallese",mi:"M\u0101ori",mic:"Mi'kmaq",min:"Minangkabau",mk:"Macedonian",ml:"Malayalam",
mn:"Mongolian",mnc:"Manchu",mni:"Manipuri",mni_Beng:"Manipuri (Bangla)",mo:"Romanian",moh:"Mohawk",mos:"Mossi",mr:"Marathi",ms:"Malay",mt:"Maltese",mua:"Mundang",mul:"Multiple languages",mus:"Muscogee",mwl:"Mirandese",mwr:"Marwari",my:"Burmese",mye:"Myene",myv:"Erzya",mzn:"Mazanderani",na:"Nauru",nap:"Neapolitan",naq:"Nama",nb:"Norwegian Bokm\u00e5l",nd:"North Ndebele",nds:"Low German",nds_NL:"Low German (Netherlands)",ne:"Nepali","new":"Newari",ng:"Ndonga",nia:"Nias",niu:"Niuean",nl:"Dutch",nl_BE:"Dutch (Belgium)",
nmg:"Kwasio",nn:"Norwegian Nynorsk",nnh:"Ngiemboon",no:"Norwegian",nog:"Nogai",non:"Old Norse",nqo:"N\u2019Ko",nr:"South Ndebele",nso:"Northern Sotho",nus:"Nuer",nv:"Navajo",nwc:"Classical Newari",ny:"Nyanja",nym:"Nyamwezi",nyn:"Nyankole",nyo:"Nyoro",nzi:"Nzima",oc:"Occitan",oj:"Ojibwa",om:"Oromo",or:"Odia",os:"Ossetic",osa:"Osage",ota:"Ottoman Turkish",pa:"Punjabi",pa_Arab:"Punjabi (Arabic)",pa_Guru:"Punjabi (Gurmukhi)",pag:"Pangasinan",pal:"Pahlavi",pam:"Pampanga",pap:"Papiamento",pau:"Palauan",
pcm:"Nigerian Pidgin",peo:"Old Persian",phn:"Phoenician",pi:"Pali",pl:"Polish",pon:"Pohnpeian",pro:"Old Proven\u00e7al",ps:"Pashto",pt:"Portuguese",pt_BR:"Portuguese (Brazil)",pt_PT:"Portuguese (Portugal)",qu:"Quechua",raj:"Rajasthani",rap:"Rapanui",rar:"Rarotongan",rm:"Romansh",rn:"Rundi",ro:"Romanian",ro_MD:"Romanian (Moldova)",rof:"Rombo",rom:"Romany",ru:"Russian",rup:"Aromanian",rw:"Kinyarwanda",rwk:"Rwa",sa:"Sanskrit",sad:"Sandawe",sah:"Sakha",sam:"Samaritan Aramaic",saq:"Samburu",sas:"Sasak",
sat:"Santali",sat_Olck:"Santali (Ol Chiki)",sba:"Ngambay",sbp:"Sangu",sc:"Sardinian",scn:"Sicilian",sco:"Scots",sd:"Sindhi",sd_Arab:"Sindhi (Arabic)",sd_Deva:"Sindhi (Devanagari)",se:"Northern Sami",see:"Seneca",seh:"Sena",sel:"Selkup",ses:"Koyraboro Senni",sg:"Sango",sga:"Old Irish",sh:"Serbo-Croatian",shi:"Tachelhit",shi_Latn:"Tachelhit (Latin)",shi_Tfng:"Tachelhit (Tifinagh)",shn:"Shan",shu:"Chadian Arabic",si:"Sinhala",sid:"Sidamo",sk:"Slovak",sl:"Slovenian",sm:"Samoan",sma:"Southern Sami",smj:"Lule Sami",
smn:"Inari Sami",sms:"Skolt Sami",sn:"Shona",snk:"Soninke",so:"Somali",sog:"Sogdien",sq:"Albanian",sr:"Serbian",sr_Cyrl:"Serbian (Cyrillic)",sr_Latn:"Serbian (Latin)",srn:"Sranan Tongo",srr:"Serer",ss:"Swati",ssy:"Saho",st:"Southern Sotho",su:"Sundanese",su_Latn:"Sundanese (Latin)",suk:"Sukuma",sus:"Susu",sux:"Sumerian",sv:"Swedish",sw:"Swahili",sw_CD:"Swahili (Congo - Kinshasa)",swb:"Comorian",syc:"Classical Syriac",syr:"Syriac",ta:"Tamil",te:"Telugu",tem:"Timne",teo:"Teso",ter:"Tereno",tet:"Tetum",
tg:"Tajik",th:"Thai",ti:"Tigrinya",tig:"Tigre",tiv:"Tiv",tk:"Turkmen",tkl:"Tokelau",tl:"Tagalog",tlh:"Klingon",tli:"Tlingit",tmh:"Tamashek",tn:"Tswana",to:"Tongan",tog:"Nyasa Tonga",tpi:"Tok Pisin",tr:"Turkish",trv:"Taroko",ts:"Tsonga",tsi:"Tsimshian",tt:"Tatar",tum:"Tumbuka",tvl:"Tuvalu",tw:"Twi",twq:"Tasawaq",ty:"Tahitian",tyv:"Tuvinian",tzm:"Central Atlas Tamazight",udm:"Udmurt",ug:"Uyghur",uga:"Ugaritic",uk:"Ukrainian",umb:"Umbundu",ur:"Urdu",uz:"Uzbek",uz_Arab:"Uzbek (Arabic)",uz_Cyrl:"Uzbek (Cyrillic)",
uz_Latn:"Uzbek (Latin)",vai:"Vai",vai_Latn:"Vai (Latin)",vai_Vaii:"Vai (Vai)",ve:"Venda",vi:"Vietnamese",vo:"Volap\u00fck",vot:"Votic",vun:"Vunjo",wa:"Walloon",wae:"Walser",wal:"Wolaytta",war:"Waray",was:"Washo",wo:"Wolof",xal:"Kalmyk",xh:"Xhosa",xog:"Soga",yao:"Yao",yap:"Yapese",yav:"Yangben",ybb:"Yemba",yi:"Yiddish",yo:"Yoruba",yrl:"Nheengatu",yue:"Cantonese",yue_Hans:"Cantonese (Simplified)",yue_Hant:"Cantonese (Traditional)",za:"Zhuang",zap:"Zapotec",zbl:"Blissymbols",zen:"Zenaga",zgh:"Standard Moroccan Tamazight",
zh:"Chinese",zh_Hans:"Chinese (Simplified)",zh_Hant:"Chinese (Traditional)",zh_TW:"Chinese (Taiwan)",zu:"Zulu",zun:"Zuni",zxx:"No linguistic content",zza:"Zaza"};H1.prototype.contains=function(a){a=g.hc(this.segments,a);return 0<=a||0>a&&1===(-a-1)%2};
H1.prototype.length=function(){return this.segments.length/2};
g.w(I1,g.G);g.h=I1.prototype;g.h.ea=function(){g.G.prototype.ea.call(this);this.B&&this.B.cancel()};
g.h.wC=function(){this.seekTo(this.player.getCurrentTime())};
g.h.seekTo=function(a){a-=this.player.xd();var b=this.j;this.j=g.Nb(this.W.zn(a).j);b!==this.j&&this.V&&this.V()};
g.h.reset=function(){this.C=new H1;this.I=-1;this.B&&(this.B.cancel(),this.B=null)};
g.h.JO=function(){this.isDisposed();var a;if(a=null!=this.j)a=this.j,a=a.j.Ho(a);if(a&&!this.B&&!(this.j&&30<this.j.startTime-this.player.getCurrentTime())){a=this.j;a=a.j.Aw(a);var b;if(null==(b=this.player.getVideoData())?0:b.enableServerStitchedDai){var c=this.player.qB();if(c){var d=a.j[0].Ga;if(b=c.wj(a.j[0].B,d,a.j[0].j.info.id,3))if(c=c.Ix(d),0===c)b&&(a.B=new g.Kx(b));else if(2===c){this.J.start();oVa(this)&&this.seekTo(this.player.getCurrentTime());return}}}a.j[0].duration?(this.C.contains(a.j[0].Ga)||
pVa(this,a),this.j=g.Nb(a.j)):!this.U.L("force_caption_seek_for_live_killswitch")&&oVa(this)&&this.seekTo(this.player.getCurrentTime())}this.J.start()};
g.w(J1,g.QJ);g.h=J1.prototype;g.h.Jp=function(a,b,c){var d=this;this.xo();b=sVa(this,a.getId());b||(b=a.languageCode,b=this.j.isManifestless?tVa(this,b,"386"):tVa(this,b));if(b){var e=1E3*(b.index.getStartTimeInPeriod(b.index.getFirstSegmentNumber())-b.index.getStartTime(b.index.getFirstSegmentNumber())),f=new g.NBa(this.U);this.B=new I1(f,this.G,b,function(k,l){c(k,a,l,e)},this.I||g.Dz(b.info),function(){d.B&&d.B.reset();
d.D=!0})}};
g.h.uI=function(){var a=this.D;this.D=!1;return a};
g.h.Su=function(a){var b=this.I?[new g.iD({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.iD({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]:this.j.isManifestless?rVa(this,"386"):rVa(this);b=g.r(b);for(var c=b.next();!c.done;c=b.next())g.PJ(this.u,c.value);a()};
g.h.xo=function(){this.B&&(this.B.dispose(),this.B=null)};
g.h.yr=function(){return""};
var X1=/^#(?:[0-9a-f]{3}){1,2}$/i,vVa=/#(.)(.)(.)/,uVa=/^#(?:[0-9a-f]{3}){1,2}$/i;var xVa=["left","right","center","justify"];g.w(L1,g.W);g.h=L1.prototype;g.h.cU=function(a,b){var c=g.Dm(this.element,this.element.parentElement);this.Za=a-c.x;this.eb=b-c.y;g.N(this.element,"ytp-dragging")};
g.h.bU=function(a,b){var c=g.Fm(this.element);a=a-this.Za-.02*this.playerWidth;var d=b-this.eb-.02*this.playerHeight,e=(a+c.width/2)/this.maxWidth*3;e=Math.floor(g.oh(e,0,2));var f=(d+c.height/2)/this.Ra*3;f=Math.floor(g.oh(f,0,2));b=e+3*f;a=(a+e/2*c.width)/this.maxWidth;a=100*g.oh(a,0,1);c=(d+f/2*c.height)/this.Ra;c=100*g.oh(c,0,1);this.u.params.rj=b;this.u.params.al=c;this.u.params.ji=a;this.j.rj=b;this.j.al=c;this.j.ji=a;this.Fa.rj=b;this.Fa.al=c;this.Fa.ji=a;this.KQ()};
g.h.aU=function(){g.rp(this.element,"ytp-dragging")};
g.h.KQ=function(){this.Iv(this.D)};
g.h.getType=function(){return this.type};
g.h.Iv=function(a){var b=Math.min(this.zN(),this.maxWidth),c=this.yN(),d="";3===this.u.params.Mg&&(d="rotate(180deg)");g.um(this.element,{top:0,left:0,right:"",bottom:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"96%","max-height":"96%",margin:"",transform:""});this.dF(a);a={transform:d,top:"",left:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"","max-height":""};var e=.96*this.j.ji+2;d=this.j.rj;switch(d){case 0:case 3:case 6:(b=this.j.Pd.fontSizeIncrement)&&0<b&&2!==this.j.Mg&&3!==
this.j.Mg&&(e=Math.max(e/(1+2*b),2));a.left=e+"%";break;case 1:case 4:case 7:a.left=e+"%";e=this.C.offsetWidth;b||e?(b=b||e+1,a.width=b+"px",a["margin-left"]=b/-2+"px"):a.transform+=" translateX(-50%)";break;case 2:case 5:case 8:a.right=100-e+"%"}b=.96*this.j.al+2;switch(d){case 0:case 1:case 2:a.top=b+"%";break;case 3:case 4:case 5:a.top=b+"%";(c=c||this.element.clientHeight)?(a.height=c+"px",a["margin-top"]=c/-2+"px"):a.transform+=" translateY(-50%)";break;case 6:case 7:case 8:a.bottom=100-b+"%"}g.um(this.element,
a)};
g.h.dF=function(a){var b;for(b=0;b<a.length&&a[b]===this.D[b];b++);if(this.ma||this.D.length>b)b=0,this.ma=!1,this.D=[],this.I=this.Da=this.va=null,g.Qh(this.C);for(;b<a.length;b++)BVa(this,a[b])};
g.h.zN=function(){return 0};
g.h.yN=function(){return 0};
g.h.toString=function(){return g.W.prototype.toString.call(this)};g.w(M1,g.QJ);M1.prototype.Jp=function(a,b,c){mVa(this.videoData.videoId,a.vssId,c)};
M1.prototype.Su=function(a){if(this.audioTrack)for(var b=g.r(this.audioTrack.captionTracks),c=b.next();!c.done;c=b.next())g.PJ(this.u,c.value);a()};g.w(N1,L1);N1.prototype.dF=function(a){var b=this.u.j;L1.prototype.dF.call(this,a);for(a=a.length;a<b.length;a++){var c=b[a];if(f&&c.j===e)var d=f;else{d={};Object.assign(d,c.j);Object.assign(d,wWa);var e=c.j;var f=d}BVa(this,c,d)}};
var wWa={uW:!0};g.w(O1,L1);g.h=O1.prototype;g.h.KQ=function(){g.kp(this.Qa)};
g.h.tZ=function(){g.rp(this.element,"ytp-rollup-mode");this.Iv(this.Fb,!0)};
g.h.yN=function(){return this.B?this.V:this.N};
g.h.zN=function(){return this.B?this.N:this.V};
g.h.Iv=function(a,b){this.Fb=a;if(this.u.params.Xn){for(var c=0,d=0;d<this.D.length&&c<a.length;d++)this.D[d]===a[c]&&c++;0<c&&c<a.length&&(a=this.D.concat(a.slice(c)));this.gb=this.V;this.N=this.V=0;L1.prototype.Iv.call(this,a);EVa(this,b)}L1.prototype.Iv.call(this,a)};g.w(P1,g.tw);P1.prototype.toString=function(){return g.tw.prototype.toString.call(this)};g.w(Q1,g.tw);Q1.prototype.toString=function(){return g.tw.prototype.toString.call(this)};
var R1=0;g.w(S1,g.G);S1.prototype.u=function(){return[]};
S1.prototype.reset=function(){};g.w(T1,S1);T1.prototype.reset=function(){this.J={};this.B=this.j=null;this.I=!0};
T1.prototype.u=function(a,b){a=a.firstChild;a.getAttribute("format");b=b||0;Number.isFinite(b);a=Array.from(a.childNodes);a=g.r(a);for(var c=a.next();!c.done;c=a.next())if(c=c.value,1===c.nodeType)switch(c.tagName){case "head":var d=c;break;case "body":var e=c}if(d)for(d=Array.from(d.childNodes),d=g.r(d),a=d.next();!a.done;a=d.next())if(a=a.value,1===a.nodeType)switch(a.tagName){case "pen":c=a.getAttribute("id");var f=this.pens,k={},l=a.getAttribute("p");l&&Object.assign(k,this.pens[l]);l=V1(a,"b");
null!=l&&(k.bold=l);l=V1(a,"i");null!=l&&(k.Hk=l);l=V1(a,"u");null!=l&&(k.underline=l);l=W1(a,"et");null!=l&&(k.charEdgeStyle=l);l=W1(a,"of");null!=l&&(k.offset=l);l=Y1(a,"bc");null!=l&&(k.background=l);l=Y1(a,"ec");null!=l&&(k.sF=l);l=Y1(a,"fc");null!=l&&(k.color=l);l=W1(a,"fs");null!=l&&0!==l&&(k.fontFamily=l);l=U1(a,"sz");void 0!==l&&(k.fontSizeIncrement=l/100-1);l=U1(a,"bo");void 0!==l&&(k.backgroundOpacity=l/255);l=U1(a,"fo");void 0!==l&&(k.textOpacity=l/255);l=W1(a,"rb");null!=l&&10!==l&&0!==
l&&(k.We=10<l?l-1:l);a=W1(a,"hg");null!=a&&(k.cO=a);f[c]=k;break;case "ws":c=a.getAttribute("id");this.V[c]=IVa(this,a);break;case "wp":c=a.getAttribute("id"),this.N[c]=JVa(this,a)}if(e){d=[];e=Array.from(e.childNodes);e=g.r(e);for(a=e.next();!a.done;a=e.next())if(a=a.value,1===a.nodeType)switch(a.tagName){case "w":this.j=KVa(this,a,b,!1);(a=this.J[this.j.id])&&a.end>this.j.start&&(a.end=this.j.start);this.J[this.j.id]=this.j;d.push(this.j);break;case "p":l=b;c=[];f=a.getAttribute("w")||this.D;k=
!!V1(a,"a");l=(U1(a,"t")||0)+l;var m=U1(a,"d")||5E3;k||(!this.I&&this.B&&this.B.windowId===f&&this.B.end>l&&(this.B.end=l),this.B&&"\n"===this.B.text&&(this.B.text=""));var n=k?6:5,p=a.getAttribute("p");p=p?this.pens[p]:null;var q=Array.from(a.childNodes);q.length&&(this.I=null!=a.getAttribute("d"));for(var t=0;t<q.length;t++){var v=q[t],x=void 0;0<t&&(k=!0);var y=void 0;1===v.nodeType&&(y=v);if(y&&"s"===y.tagName){if((v=(v=y.getAttribute("p"))?this.pens[v]:null)&&v.We&&(1===v.We?(v=q.slice(t,t+4),
4===v.length&&(x=HVa(l,m,f,k,n,v,this.pens),t+=3)):x=HVa(l,m,f,k,n,[y],this.pens)),!x){var z=y;x=l;y=m;v=f;var E=k,J=n,I=z.textContent?z.textContent:"",M=z.getAttribute("p");M=M?this.pens[M]:null;z=U1(z,"t")||0;x=new P1(x+z,y-z,J,v,I,E,M)}}else x=new P1(l,m,n,f,v.textContent||"",k,p);c.push(x);this.B=x}if(0<c.length)for(c[0].windowId===this.D&&(this.j=KVa(this,a,b,!0),d.push(this.j)),a=g.r(c),c=a.next();!c.done;c=a.next())c=c.value,c.windowId=this.j.id,this.j.j.push(c),d.push(c)}b=d}else b=[];return b};var xWa=new Map([[9,1],[10,1],[11,2],[12,3],[13,4],[14,5]]);g.w(Z1,S1);Z1.prototype.reset=function(){this.B.clear()};
Z1.prototype.u=function(a,b){var c=JSON.parse(a);if(!c)return[];if(c.pens){a=0;for(var d=g.r(c.pens),e=d.next();!e.done;e=d.next()){e=e.value;var f={},k=e.pParentId;k&&Object.assign(f,this.j.get(k));e.bAttr&&(f.bold=!0);e.iAttr&&(f.Hk=!0);e.uAttr&&(f.underline=!0);k=e.ofOffset;null!=k&&(f.offset=k);void 0!==e.szPenSize&&(f.fontSizeIncrement=e.szPenSize/100-1);k=e.etEdgeType;null!=k&&(f.charEdgeStyle=k);void 0!==e.ecEdgeColor&&(f.sF=$1(e.ecEdgeColor));k=e.fsFontStyle;null!=k&&0!==k&&(f.fontFamily=
k);void 0!==e.fcForeColor&&(f.color=$1(e.fcForeColor));void 0!==e.foForeAlpha&&(f.textOpacity=e.foForeAlpha/255);void 0!==e.bcBackColor&&(f.background=$1(e.bcBackColor));void 0!==e.boBackAlpha&&(f.backgroundOpacity=e.boBackAlpha/255);(k=e.rbRuby)&&10!==k&&(f.We=10<k?k-1:k,f.Zk=xWa.get(f.We));e.hgHorizGroup&&(f.cO=e.hgHorizGroup);this.j.set(a++,f)}}if(c.wsWinStyles)for(a=0,d=g.r(c.wsWinStyles),e=d.next();!e.done;e=d.next())e=e.value,f={},(k=e.wsParentId)?Object.assign(f,this.D.get(k)):Object.assign(f,
this.I),void 0!==e.mhModeHint&&(f.Xu=e.mhModeHint),void 0!==e.juJustifCode&&(f.textAlign=e.juJustifCode),void 0!==e.pdPrintDir&&(f.Mg=e.pdPrintDir),void 0!==e.sdScrollDir&&(f.vJ=e.sdScrollDir),void 0!==e.wfcWinFillColor&&(f.windowColor=$1(e.wfcWinFillColor)),void 0!==e.wfoWinFillAlpha&&(f.windowOpacity=e.wfoWinFillAlpha/255),this.D.set(a++,f);if(c.wpWinPositions)for(a=0,d=g.r(c.wpWinPositions),e=d.next();!e.done;e=d.next())e=e.value,f={},(k=e.wpParentId)&&Object.assign(f,this.C.get(k)),void 0!==e.ahHorPos&&
(f.ji=e.ahHorPos),void 0!==e.apPoint&&(f.rj=e.apPoint),void 0!==e.avVerPos&&(f.al=e.avVerPos),void 0!==e.ccCols&&(f.Qo=e.ccCols),void 0!==e.rcRows&&(f.Xn=e.rcRows),this.C.set(a++,f);if(c.events){a=[];c=g.r(c.events);for(d=c.next();!d.done;d=c.next()){var l=d.value;d=(l.tStartMs||0)+b;e=l.dDurationMs||0;if(l.id)f=String(l.id),d=LVa(this,l,d,e,f),a.push(d),this.B.set(f,d);else{l.wWinId?f=l.wWinId.toString():(f="_"+R1++,k=LVa(this,l,d,e,f),a.push(k),this.B.set(f,k));0===e&&(e=5E3);k=this.B.get(f);var m=
!!l.aAppend,n=m?6:5,p=l.segs,q=null;l.pPenId&&(q=this.j.get(l.pPenId));for(l=0;l<p.length;l++){var t=p[l],v=t.utf8;if(v){var x=t.tOffsetMs||0,y=null;t.pPenId&&(y=this.j.get(t.pPenId));if(2===(null!=k.params.Xu?k.params.Xu:1<k.j.length?1:0)&&m&&"\n"===v)continue;if(t=y&&1===y.We)if(t=l,t+3>=p.length||!p[t+1].pPenId||!p[t+2].pPenId||!p[t+3].pPenId)t=!1;else{var z=p[t+1].pPenId;(z=this.j.get(z))&&z.We&&2===z.We?(z=p[t+2].pPenId,z=this.j.get(z),!z||!z.We||3>z.We?t=!1:(z=p[t+3].pPenId,t=(z=this.j.get(z))&&
z.We&&2===z.We?!0:!1)):t=!1}if(t){x=p[l+1].utf8;t=p[l+3].utf8;z=p[l+2].utf8;var E=this.j.get(p[l+2].pPenId);v=GVa(v,x,z,t,E);m=new P1(d,e,n,f,v,m,y);l+=3}else m=new P1(d+x,e-x,n,k.id,v,m,y||q);m&&(a.push(m),k.j.push(m))}m=!0}}}b=a}else b=[];return b};b2.prototype.clear=function(){this.B=this.time=this.mode=0;this.j=[];this.reset()};
b2.prototype.reset=function(){this.mode=0;this.C.reset(0);this.D.reset(1)};
var MVa=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];c2.prototype.set=function(a){this.type=a};
c2.prototype.get=function(){return this.type};
d2.prototype.clear=function(){this.state=0};
d2.prototype.update=function(){this.state=2===this.state?1:0};
d2.prototype.isValid=function(){return 0!==this.state};
d2.prototype.matches=function(a,b){return this.isValid()&&a===this.Sq&&b===this.No};
RVa.prototype.reset=function(){this.timestamp=this.j=0};
e2.prototype.updateTime=function(a){for(var b=1;15>=b;++b)for(var c=1;32>=c;++c)this.B[b][c].timestamp=a};
e2.prototype.debugString=function(){for(var a="\n",b=1;15>=b;++b){for(var c=1;32>=c;++c){var d=this.B[b][c];a=0===d.j?a+"_":a+String.fromCharCode(d.j)}a+="\n"}return a};
e2.prototype.reset=function(a){for(var b=0;15>=b;b++)for(var c=0;32>=c;c++)this.B[b][c].reset();this.C=a;this.j=0;this.u=this.row=1};
var SVa=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],TVa=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],UVa=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],VVa=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];k2.prototype.reset=function(a,b){this.D=b;this.style.set(2);this.u=this.I;this.C=this.J;this.j=this.u;var c=(a<<2)+(b<<1);this.I.reset(c);this.J.reset(c);this.text.reset((a<<2)+(b<<1)+1)};
a2.prototype.reset=function(a){this.D=a;this.u.clear();this.C=this.B;this.B.reset(a,0);this.I.reset(a,1)};$Va.prototype.C=function(){};g.w(m2,$Va);m2.prototype.C=function(a,b,c,d,e){if(c<d){var f="_"+R1++;c=c/1E3-this.I;d=d/1E3-this.I;a=new Q1(c,d-c,5,f,{textAlign:0,rj:0,ji:2.5*b,al:5.33*a});e=new P1(c,d-c,5,f,e);this.u.push(a);this.u.push(e)}};
g.w(p2,S1);p2.prototype.u=function(a){a=new m2(a,a.byteLength,this.B);if(aWa(a)){for(;a.byteOffset<a.j.byteLength;)for(0===a.version?a.B=o2(a)*(1E3/45):1===a.version&&(a.B=4294967296*o2(a)+o2(a)),a.D=n2(a);0<a.D;a.D--){var b=n2(a),c=n2(a),d=n2(a);b&4&&(b&3)===this.track&&(0===this.track||1===this.track)&&(b=this.j,b.j.push({time:a.B,type:this.track,DM:c,EM:d,order:b.j.length}))}QVa(this.j,a);return a.u}return[]};
p2.prototype.reset=function(){this.j.clear()};g.w(r2,S1);
r2.prototype.u=function(a,b){var c=[];a=a.split(yWa);for(var d=1;d<a.length;d++){var e=a[d],f=b;if(""!==e&&!zWa.test(e)){var k=H2.exec(e);if(k&&4<=k.length){var l=s2(k[1]),m=s2(k[2])-l;l+=f;var n=(k=k[3])?k.split(" "):[];k={};var p=null;var q="";var t=null,v="";n=g.r(n);for(var x=n.next();!x.done;x=n.next())if(x=x.value.split(":"),2===x.length){var y=x[1];switch(x[0]){case "line":x=y.split(",");x[0].endsWith("%")&&(p=x[0],k.al=Number.parseInt(p,10),2===x.length&&(q=x[1].trim()));break;case "position":x=
y.split(",");t=x[0];k.ji=Number.parseInt(t,10);2===x.length&&(v=x[1].trim());break;case "align":switch(y){case "start":k.textAlign=0;break;case "middle":k.textAlign=2;break;case "end":k.textAlign=1}}}p||q||(q="end");if(!t)switch(k.textAlign){case 0:k.ji=0;break;case 1:k.ji=100;break;case 2:k.ji=50}if(null!=k.textAlign){p=0;switch(q){case "center":p+=3;break;case "end":p+=6;break;default:p+=0}switch(v){case "line-left":p+=0;break;case "center":p+=1;break;case "line-right":p+=2;break;default:switch(k.textAlign){case 0:p+=
0;break;case 2:p+=1;break;case 1:p+=2}}q=0>p||8<p?7:p;k.rj=q}e=e.substring(H2.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");v=k;k=e;e={};if(0>k.indexOf("<")&&0>k.indexOf("&"))f=cWa(l,m,5,v),m=new P1(l,m,5,f.id,k,!1,g.Qf(e)?void 0:e),c.push(f),c.push(m),f.j.push(m);else for(q=k.split(AWa),1===q.length?(k=5,v=cWa(l,m,k,v)):(p=k=6,v=Object.assign({Qo:32},v),v=new Q1(l,m,p,"_"+R1++,v)),c.push(v),p=l,t=0;t<q.length;t++)n=q[t],0===t%2?(x=g.WZ("<html>"+n+"</html>"),x.getElementsByTagName("parsererror").length?
(y=x.createElement("span"),y.appendChild(x.createTextNode(n))):y=x.firstChild,bWa(this,p,m-(p-l),k,v,0<t,y,e,c)):p=s2(n)+f}H2.lastIndex=0}}return c};
var zWa=/^NOTE/,yWa=/(?:\r\n|\r|\n){2,}/,H2=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),AWa=RegExp("<((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})>");g.cO.MB(r2,{u:"wvppt"});g.w(t2,g.G);t2.prototype.clear=function(){this.j&&this.j.dispose();this.j=null};
t2.prototype.reset=function(){this.j&&this.j.reset()};
t2.prototype.ea=function(){g.G.prototype.ea.call(this);this.clear()};var F2={windowColor:"#080808",windowOpacity:0,textAlign:2,rj:7,ji:50,al:100,Pd:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.w(w2,g.CJ);g.h=w2.prototype;g.h.ea=function(){if(this.B||this.V){var a=this.G.Id();a&&!a.isDisposed()&&a.Yt()}else G2(this,!1);g.CJ.prototype.ea.call(this)};
g.h.Is=function(){if(this.Ia)return this.B||this.V;var a=F1(this.player.getAudioTrack(),G1(this.U));return"CAPTIONS_INITIAL_STATE_ON_REQUIRED"===a?!0:"CAPTIONS_INITIAL_STATE_OFF_REQUIRED"===a?y2(this):x2(this)||y2(this)?!0:oWa(this)};
g.h.load=function(){var a=this;g.CJ.prototype.load.call(this);var b=!this.U.L("web_player_captions_track_list_changed_killswitch");this.I=this.player.getAudioTrack();this.u?(this.j&&(this.Qa.clear(),this.B?rWa(this,!0):3!==this.player.getPresentingPlayerType()&&this.u.Jp(this.j,"json3",function(c,d,e,f){c&&(a.u.uI()&&(a.oa=[],a.G.Kf("captions"),g.ip(a.ma),a.Qa.reset()),c=iWa(a.Qa,c,d,e,f),a.player.Yd(c,void 0,a.Ta),!a.W||a.V||B2(a)||g.oC(a.U)||g.fC(a.U)||(g.lp(a.va),c=FVa({rj:0,ji:5,al:5,Xn:2,textAlign:0,
Mg:0,lang:"en"}),a.Da=[c],d=["Click "," for settings"],a.Za||(e=new g.EG(g.VG()),g.H(a,e),a.Za=e.element),e=c.end-c.start,(f=g.jD(a.j))&&a.Da.push(new P1(c.start,e,0,c.id,f)),a.Da.push(new P1(c.start,e,0,c.id,d[0]),new P1(c.start,e,0,c.id,a.Za,!0),new P1(c.start,e,0,c.id,d[1],!0)),a.player.Yd(a.Da),g.jp(a.va)),!a.W||a.V||B2(a)||(g.BC(a.U)?D2(a,!0):E2(a,"module-enabled",!0),a.I&&(a.I.C=a.j),a.player.Us()),a.W=!1)}),!b||this.B||this.V||B2(this)||this.player.La("captionschanged",g.kD(this.j))),b||(this.j&&
!B2(this)?this.player.La("captionschanged",g.kD(this.j)):this.player.La("onCaptionsTrackListChanged"))):(this.u=pWa(this),g.H(this,this.u),this.u.Su(function(){qWa(a)}))};
g.h.unload=function(){this.B&&this.j?rWa(this,!1):(this.va&&g.lp(this.va),this.player.Kf("captions"),this.oa=[],this.u&&this.u.xo(),this.Qa.clear(),this.J&&this.player.Yd(this.J),this.QJ());g.CJ.prototype.unload.call(this);this.player.Us();this.player.La("captionschanged",{})};
g.h.create=function(){this.Is()&&this.load()};
g.h.a_=function(){for(var a=this.G.Id().jf().textTracks,b=null,c=0;c<a.length;c++)if("showing"===a[c].mode)a:{b=g.OJ(this.u.u,!0);for(var d=0;d<b.length;d++)if(b[d].toString()===a[c].id){b=b[d];break a}b=null}(this.loaded?this.j:null)!==b&&C2(this,b,!0)};
g.h.K0=function(){!this.j&&this.B||this.unload()};
g.h.onCueRangeEnter=function(a){this.oa.push(a);g.ip(this.ma)};
g.h.onCueRangeExit=function(a){g.Zb(this.oa,a);this.u instanceof J1&&this.u.I&&this.player.Lg([a]);g.ip(this.ma)};
g.h.getCaptionWindowContainerId=function(){return this.Ra.element.id};
g.h.I_=function(){vWa(this,this.Da);this.Da=null};
g.h.OJ=function(){var a=this;if(!this.ib||!this.B){this.ma.stop();g.Rf(this.Fa);this.oa.sort(g.uw);var b=this.oa;if(this.J){var c=g.sn(b,function(f){return-1===this.J.indexOf(f)},this);
c.length&&(b=c)}b=g.r(b);for(c=b.next();!c.done;c=b.next())tWa(this,c.value);b={};c=g.r(Object.entries(this.N));for(var d=c.next();!d.done;b={tq:b.tq,fk:b.fk},d=c.next()){var e=g.r(d.value);d=e.next().value;e=e.next().value;b.tq=d;b.fk=e;this.Fa[b.tq]?(b.fk.element.parentNode||(b.fk instanceof O1||b.fk instanceof N1||g.Ef(this.N,function(f){return function(k,l){l!==f.tq&&k.u.params.rj===f.fk.u.params.rj&&k.u.params.ji===f.fk.u.params.ji&&k.u.params.al===f.fk.u.params.al&&(k.dispose(),delete a.N[l]);
return l===f.tq}}(b),this),uWa(this,b.fk.element)),b.fk.Iv(this.Fa[b.tq])):(b.fk.dispose(),delete this.N[b.tq])}}};
g.h.M_=function(){u2(this,{},!0);this.U.L("web_player_disable_publish_captions_settings_changed_on_reset")||this.player.La("captionssettingschanged")};
g.h.RV=function(){var a=F2.Pd;a={background:a.background,backgroundOpacity:a.backgroundOpacity,charEdgeStyle:a.charEdgeStyle,color:a.color,fontFamily:a.fontFamily,fontSizeIncrement:a.fontSizeIncrement,fontStyle:a.bold&&a.Hk?3:a.bold?1:a.Hk?2:0,textOpacity:a.textOpacity,windowColor:F2.windowColor,windowOpacity:F2.windowOpacity};var b=v2(this)||{};null!=b.background&&(a.background=b.background);null!=b.backgroundOverride&&(a.backgroundOverride=b.backgroundOverride);null!=b.backgroundOpacity&&(a.backgroundOpacity=
b.backgroundOpacity);null!=b.backgroundOpacityOverride&&(a.backgroundOpacityOverride=b.backgroundOpacityOverride);null!=b.charEdgeStyle&&(a.charEdgeStyle=b.charEdgeStyle);null!=b.charEdgeStyleOverride&&(a.charEdgeStyleOverride=b.charEdgeStyleOverride);null!=b.color&&(a.color=b.color);null!=b.colorOverride&&(a.colorOverride=b.colorOverride);null!=b.fontFamily&&(a.fontFamily=b.fontFamily);null!=b.fontFamilyOverride&&(a.fontFamilyOverride=b.fontFamilyOverride);null!=b.fontSizeIncrement&&(a.fontSizeIncrement=
b.fontSizeIncrement);null!=b.fontSizeIncrementOverride&&(a.fontSizeIncrementOverride=b.fontSizeIncrementOverride);null!=b.fontStyle&&(a.fontStyle=b.fontStyle);null!=b.fontStyleOverride&&(a.fontStyleOverride=b.fontStyleOverride);null!=b.textOpacity&&(a.textOpacity=b.textOpacity);null!=b.textOpacityOverride&&(a.textOpacityOverride=b.textOpacityOverride);null!=b.windowColor&&(a.windowColor=b.windowColor);null!=b.windowColorOverride&&(a.windowColorOverride=b.windowColorOverride);null!=b.windowOpacity&&
(a.windowOpacity=b.windowOpacity);null!=b.windowOpacityOverride&&(a.windowOpacityOverride=b.windowOpacityOverride);return a};
g.h.NR=function(a,b){var c={};Object.assign(c,v2(this));Object.assign(c,a);u2(this,c,b);this.player.La("captionssettingschanged")};
g.h.QJ=function(){!this.B&&this.loaded&&(g.Bf(this.N,function(a,b){a.dispose();delete this.N[b]},this),this.OJ())};
g.h.Yf=function(a,b){switch(a){case "fontSize":if(isNaN(b))break;var c=g.oh(b,-2,4);this.NR({fontSizeIncrement:c});return c;case "reload":b&&!this.B&&C2(this,this.j,!0);break;case "stickyLoading":void 0!==b&&this.U.B&&(g.BC(this.U)?D2(this,!!b):E2(this,"module-enabled",!!b));break;case "track":if(!this.u)return{};if(b){if(this.B)break;if(!g.Na(b))break;if(g.Qf(b)){C2(this,null,!0);break}a=g.OJ(this.u.u,!0);for(var d=0;d<a.length;d++){var e=a[d];e.languageCode!==b.languageCode||c&&e.languageName!==
b.languageName||(c=b.translationLanguage?lVa(e,b.translationLanguage):e)}!c||c===this.j&&this.loaded||(b=g.Ita(),a=g.lD(c),b.length&&a===b[b.length-1]||(b.push(a),g.Sv("yt-player-caption-language-preferences",b)),C2(this,c,!0))}else return this.loaded&&this.j&&!B2(this)?g.kD(this.j):{};return"";case "tracklist":return this.u?g.Bl(g.OJ(this.u.u,!(!b||!b.includeAsr)),function(f){return g.kD(f)}):[];
case "translationLanguages":return this.u?this.u.C.map(function(f){return Object.assign({},f)}):[];
case "sampleSubtitles":this.B||void 0===b||G2(this,!!b);break;case "sampleSubtitlesCustomized":this.B||G2(this,!!b,b)}};
g.h.getOptions=function(){var a="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.U.B&&a.push("stickyLoading");return a};
g.h.wG=function(){var a=this.j;if(a){var b=a.vssId;a.translationLanguage&&b&&!this.U.L("auto_translation_logging_killswitch")&&(b="t"+b+"."+g.lD(a));return{cc:b}}return{}};
g.h.z0=function(){this.loaded&&this.j&&!B2(this)?(g.BC(this.U)?D2(this,!1):E2(this,"module-enabled",!1),this.unload(),y2(this,!0)&&C2(this,z2(this),!1)):this.uR()};
g.h.uR=function(){this.loaded&&this.j&&!B2(this)||C2(this,B2(this)||!this.j?A2(this,!0):this.j,!0)};
g.h.RX=function(){var a=B2(this);y2(this,a)?C2(this,this.player.getAudioTrack().j,!1):this.videoData.captionTracks.length&&(this.loaded&&this.unload(),this.Is()&&(a?C2(this,A2(this),!1):this.load()))};
g.h.CY=function(){var a=this.G.Id();a&&!a.isDisposed()&&a.Yt();this.G.isFullscreen()?(this.B=this.Ia=!0,this.loaded&&qWa(this)):(this.Ia="3"===this.U.controlsType,this.B=lWa(this));C2(this,this.j)};
g.cO.MB(w2,{OJ:"smucd"});g.BJ("captions",w2);})(_yt_player);
