(function(g){var window=this;'use strict';var DXa=function(a,b){var c=[];return g.Us(a,{query:b},function(d){c.push(d.getValue());return d.continue()}).then(function(){return c})},b4=function(a,b){return"getAll"in IDBIndex.prototype?g.Is(a.j.getAll(b,void 0)):DXa(a,b)},EXa=function(a,b){return g.Os(a,["captions"],{mode:"readonly",
Jc:!0},function(c){return g.lna(c.objectStore("captions"),b)})},FXa=function(a){var b=new g.sx("und",new g.Tz("Default","und",!0));
b.captionTracks=a.captionTracks;return b},GXa=function(a){return new g.hi(function(b,c){var d=a.length,e=[];
if(d)for(var f=function(n,p){d--;e[n]=p;0==d&&b(e)},k=function(n){c(n)},l=0,m;l<a.length;l++)m=a[l],g.Rba(m,g.Sa(f,l),k);
else b(e)})},c4=function(a){this.j=a},d4=function(){c4.apply(this,arguments)},e4=function(){d4.apply(this,arguments)},f4=function(){d4.apply(this,arguments)},g4=function(){d4.apply(this,arguments)},h4=function(){c4.apply(this,arguments)},i4=function(){d4.apply(this,arguments)},j4=function(){d4.apply(this,arguments)},k4=function(){d4.apply(this,arguments)},l4=function(){d4.apply(this,arguments)},m4=function(){d4.apply(this,arguments)},n4=function(){d4.apply(this,arguments)},o4=function(){d4.apply(this,
arguments)},p4=function(){d4.apply(this,arguments)},q4=function(){d4.apply(this,arguments)},r4=function(){d4.apply(this,arguments)},s4=function(){d4.apply(this,arguments)},t4=function(){c4.apply(this,arguments)},u4=function(){d4.apply(this,arguments)},v4=function(){d4.apply(this,arguments)},w4=function(){d4.apply(this,arguments)},x4=function(){d4.apply(this,arguments)},y4=function(){d4.apply(this,arguments)},z4=function(){d4.apply(this,arguments)},A4=function(){d4.apply(this,arguments)},B4=function(){d4.apply(this,
arguments)},C4=function(){d4.apply(this,arguments)},D4=function(){d4.apply(this,arguments)},E4=function(){d4.apply(this,arguments)},F4=function(){d4.apply(this,arguments)},G4=function(){d4.apply(this,arguments)},H4=function(){d4.apply(this,arguments)},I4=function(){d4.apply(this,arguments)},J4=function(){d4.apply(this,arguments)},K4=function(){d4.apply(this,arguments)},L4=function(){d4.apply(this,arguments)},M4=function(){d4.apply(this,arguments)},N4=function(){d4.apply(this,arguments)},O4=function(){d4.apply(this,
arguments)},P4=function(){d4.apply(this,arguments)},Q4=function(){d4.apply(this,arguments)},R4=function(){d4.apply(this,arguments)},S4=function(){d4.apply(this,arguments)},T4=function(){d4.apply(this,arguments)},U4=function(){d4.apply(this,arguments)},V4=function(){d4.apply(this,arguments)},W4=function(){d4.apply(this,arguments)},X4=function(){d4.apply(this,arguments)},HXa=function(a){var b=g.cD();
b=Object.assign({},b);a=Object.assign({},a);for(var c in b)a[c]?(4!==b[c]&&(b[c]=a[c]),delete a[c]):2!==b[c]&&(b[c]=4);Object.assign(b,a);g.jva(b);JSON.stringify(b);return b},IXa=function(a){var b,c;
return g.B(function(d){if(1==d.j)return g.A(d,g.dt(),2);if(3!=d.j)return(b=d.u)?g.A(d,g.fD(b),3):d.return();c=d.u;return d.return(g.Os(c,["index","media","captions"],{mode:"readwrite",Jc:!0},function(e){var f=IDBKeyRange.bound(a+"|",a+"~");e=[e.objectStore("index").delete(f),e.objectStore("media").delete(f),e.objectStore("captions").delete(f)];return g.Gs.all(e).then(function(){})}))})},JXa=function(){var a,b;
return g.B(function(c){if(1==c.j)return g.A(c,g.dt(),2);if(3!=c.j){a=c.u;if(!a)throw g.Es("rvdfd");return g.A(c,g.fD(a),3)}b=c.u;return c.return(g.Os(b,["index","media"],{mode:"readwrite",Jc:!0},function(d){var e={};return g.Ss(d.objectStore("index"),{},function(f){var k=f.getKey().match(/^([\w\-_]+)\|(a|v)$/),l=g.Gs.resolve(void 0);if(k){var m=k[1];k=k[2];e[m]=e[m]||{};var n;e[m][k]=g.ova(null==(n=f.getValue())?void 0:n.fmts)}else l=f.delete().then(function(){});
return g.Gs.all([f.continue(),l]).then(function(p){return g.r(p).next().value})}).then(function(){for(var f={},k=g.r(Object.keys(e)),l=k.next();!l.done;l=k.next()){l=l.value;
var m=e[l].v;f[l]=e[l].a&&m?1:2}var n=HXa(f);return g.ona(d.objectStore("media"),{},function(p){var q=p.getKey().match(g.sva);q&&f[q[1]]||d.objectStore("media").delete(p.getKey());return p.continue()}).then(function(){return n})})}))})},KXa=function(a,b){var c,d;
return g.B(function(e){if(1==e.j)return g.A(e,g.dt(),2);if(3!=e.j){c=e.u;if(!c)throw g.Es("wct");return g.A(e,g.fD(c),3)}d=e.u;return g.A(e,g.Os(d,["captions"],{mode:"readwrite",Jc:!0},function(f){var k=[];f=f.objectStore("captions");for(var l=0;l<b.length;l++){var m=g.Ps(f,b[l],a+"|"+b[l].metadata.vss_id);k.push(m)}return g.Gs.all(k)}),0)})},LXa=function(a){var b,c,d;
return g.B(function(e){if(1==e.j)return b=IDBKeyRange.bound(a+"|",a+"~"),g.A(e,g.dt(),2);if(3!=e.j){c=e.u;if(!c)throw g.Es("gactfv");return g.A(e,g.fD(c),3)}d=e.u;return e.return(EXa(d,b))})},MXa=function(a){return g.B(function(b){g.eD(a,0);
return b.return(IXa(a))})},NXa=function(a){return{context:g.dG(),
videoIds:a}},Y4=function(a){a=a.key||a.id;
if(!a)throw Error("Entity key is missing");return a},Z4=function(a,b){b=void 0===b?{}:b;
g.us.call(this,g.ATa[a],Object.assign({},{name:"PESEncoderError",type:a},b));this.type=a;this.level="WARNING";Object.setPrototypeOf(this,Z4.prototype)},OXa=function(a){return new Z4("WRONG_DATA_TYPE",{xV:a})},PXa=function(a){return a instanceof Error?new Z4("UNKNOWN_ENCODE_ERROR",{originalMessage:a.message}):new Z4("UNKNOWN_ENCODE_ERROR")},QXa=function(a){return a instanceof Error?new Z4("UNKNOWN_DECODE_ERROR",{originalMessage:a.message}):new Z4("UNKNOWN_DECODE_ERROR")},RXa=function(a,b){a=a instanceof
Z4?a:b(a);
g.S(a);throw a;},SXa=function(){},TXa=function(a,b,c){try{return a.B(b,c)}catch(d){RXa(d,PXa)}},UXa=function(a,b,c){try{return a.u(b,c)}catch(d){RXa(d,QXa)}},$4=function(a){a=(new TextEncoder).encode(a).subarray(0,16);
var b=new Uint8Array(16);b.set(a);return b},a5=function(a){this.j=a},b5=function(){},VXa=function(){this.j={};
this.j[0]=new b5;if(!g.Q("aes_pes_encoder_killswitch")){var a=this.j;try{var b=g.vs();var c=$4(b);var d=new a5(new g.zB(c),new g.yB(c))}catch(e){throw a=e instanceof Error?new Z4("KEY_CREATION_FAILED",{originalMessage:e.message}):new Z4("KEY_CREATION_FAILED"),g.S(a),a;}a[1]=d}},c5=function(a,b){b=void 0===b?0:b;
a=a.j[b];if(!a)throw b=new Z4("INVALID_ENCODER_VERSION",{xV:b}),g.S(b),b;return a},XXa=function(a){var b=WXa[a];
if(b)return b;g.uv(new g.us("Entity model not found.",{entityType:a}))},YXa=function(a){var b=new VXa,c=a.objectStore("EntityStore"),d=a.objectStore("EntityAssociationStore");
g.Ss(c,{},function(e){var f=e.getValue(),k=UXa(c5(b,f.version),f.data,f.key),l=g.VI(f.key).entityType;l=XXa(l);if(!l)return e.continue();l=(new l(k)).Wb();k=[];l=g.r(l);for(var m=l.next();!m.done;m=l.next())k.push(g.Ps(d,{parentEntityKey:f.key,childEntityKey:m.value}));return g.Gs.all(k).then(function(){return e.continue()})})},ZXa=function(){if(d5)return d5();
var a={};d5=g.rt("PersistentEntityStoreDb",{Wr:(a.EntityStore={Lo:1},a.EntityAssociationStore={Lo:2},a),xz:!1,upgrade:function(b,c,d){c(1)&&g.Rs(g.Ms(b,"EntityStore",{keyPath:"key"}),"entityType","entityType");c(2)&&(b=g.Ms(b,"EntityAssociationStore",{keyPath:["parentEntityKey","childEntityKey"]}),g.Rs(b,"byParentEntityKey","parentEntityKey"),g.Rs(b,"byChildEntityKey","childEntityKey"));c(3)&&!c(1)&&YXa(d)},
version:g.Q("pes_migrate_association_data")?3:2});return d5()},$Xa=function(a){return g.Xs(ZXa(),a)},aYa=function(a,b){this.j=a;
this.u=b;this.B={}},bYa=function(a,b){return UXa(c5(a.u,b.version),b.data,b.key)},e5=function(a,b,c){return a.j.objectStore("EntityStore").get(b).then(function(d){if(d){if(c&&d.entityType!==c)throw Error("Incorrect entity type");
return bYa(a,d)}})},f5=function(a,b,c){return c?(c=c.map(function(d){return e5(a,d,b)}),g.Gs.all(c)):b4(a.j.objectStore("EntityStore").index("entityType"),IDBKeyRange.only(b)).then(function(d){return d.map(function(e){return bYa(a,e)})})},h5=function(a,b,c){var d=Y4(b),e=c5(a.u,1),f={key:d,
entityType:c,data:TXa(e,b,d),version:1};return a.j.objectStore("EntityStore").get(d).then(function(k){if(k&&k.entityType!==c)throw Error("Incorrect entity type");}).then(function(){return g.Gs.all([g.Ps(a.j.objectStore("EntityStore"),f),
cYa(a,b,c)])}).then(function(){g5(a,d,c);
return d})},i5=function(a,b,c){b=b.map(function(d){return h5(a,d,c)});
return g.Gs.all(b)},j5=function(a,b,c){if(null==c?0:c.rF){var d=new Set;
return dYa(a,b,d).then(function(){for(var f=[],k=g.r(d),l=k.next();!l.done;l=k.next())f.push(j5(a,l.value));return g.Gs.all(f).then(function(){})})}var e=g.VI(b).entityType;
return g.Gs.all([a.j.objectStore("EntityStore").delete(b),k5(a,b)]).then(function(){g5(a,b,e)})},eYa=function(a,b){return g.Us(a.j.objectStore("EntityStore").index("entityType"),{query:IDBKeyRange.only(b)},function(c){return g.Gs.all([c.delete(),
k5(a,c.xB())]).then(function(){g5(a,c.xB(),b);return c.continue()})})},fYa=function(a,b,c,d){var e=c5(a.u,1);
return e5(a,b,d).then(function(f){if(f){f=g.FI(f,c);var k={key:b,entityType:d,data:TXa(e,f,b),version:1};return g.Gs.all([g.Ps(a.j.objectStore("EntityStore"),k),cYa(a,f,d)])}}).then(function(){g5(a,b,d);
return b})},g5=function(a,b,c){var d=a.B[c];
d||(d=new Set,a.B[c]=d);d.add(b)},gYa=function(a,b,c){var d=Y4(b);
c=XXa(c);if(!c)return g.Gs.resolve([]);c=new c(b);a=a.j.objectStore("EntityAssociationStore");b=[];c=g.r(c.Wb());for(var e=c.next();!e.done;e=c.next())b.push(g.Ps(a,{parentEntityKey:d,childEntityKey:e.value}));return g.Gs.all(b).then(function(f){return f.map(function(k){return k[1]})})},k5=function(a,b){return a.j.objectStore("EntityAssociationStore").index("byParentEntityKey").delete(IDBKeyRange.only(b))},cYa=function(a,b,c){var d=Y4(b);
return k5(a,d).then(function(){return gYa(a,b,c)})},dYa=function(a,b,c){if(c.has(b))return g.Gs.resolve(void 0);
c.add(b);return hYa(a,b).then(function(d){return a.j.objectStore("EntityAssociationStore").index("byParentEntityKey").delete(IDBKeyRange.only(b)).then(function(){return d})}).then(function(d){var e=g.Gs.resolve(void 0),f={};
d=g.r(d);for(var k=d.next();!k.done;f={LD:f.LD},k=d.next())f.LD=k.value,e=e.then(function(l){return function(){return dYa(a,l.LD,c)}}(f));
return e}).then(function(){})},hYa=function(a,b){var c=a.j.objectStore("EntityAssociationStore");
return b4(c.index("byParentEntityKey"),IDBKeyRange.only(b)).then(function(d){var e=[];d=g.r(d);for(var f=d.next();!f.done;f=d.next())f=f.value,e.push(b4(c.index("byChildEntityKey"),f.childEntityKey));return g.Gs.all(e)}).then(function(d){var e=[];
d=g.r(d);for(var f=d.next();!f.done;f=d.next())f=f.value,1===f.length&&e.push(f[0].childEntityKey);return e})},l5=function(a,b){g.G.call(this);
this.token=a;this.u=b;this.j=[];a=new g.C.BroadcastChannel("PERSISTENT_ENTITY_STORE_SYNC:"+g.vs());a.onmessage=this.B.bind(this);this.channel=a},m5=function(a,b,c){var d,e,f,k;
return g.B(function(l){if(1==l.j)return g.A(l,$Xa(a.token),2);if(3!=l.j)return d=l.u,g.A(l,g.Os(d,["EntityStore","EntityAssociationStore"],b,function(m){e=new aYa(m,a.u);return c(e)}),3);
f=l.u;e&&(k=e.B,0<Object.keys(k).length&&(a.channel.postMessage(k),iYa(a,k)));return l.return(f)})},n5=function(a,b){a.j.push(b);
return function(){var c=a.j.indexOf(b);0<=c&&a.j.splice(c,1)}},o5=function(a,b,c){return m5(a,{mode:"readwrite",
Jc:!0},function(d){return h5(d,b,c)})},jYa=function(a,b){return m5(a,{mode:"readwrite",
Jc:!0},function(c){return i5(c,b,"offlineOrchestrationActionWrapperEntity")})},kYa=function(a,b){return m5(a,{mode:"readwrite",
Jc:!0},function(c){return j5(c,b)})},p5=function(a,b,c){return m5(a,{mode:"readonly",
Jc:!0},function(d){return e5(d,b,c)})},q5=function(a,b,c){return m5(a,{mode:"readonly",
Jc:!0},function(d){return f5(d,b,c)})},iYa=function(a,b){a=g.r(a.j);
for(var c=a.next();!c.done;c=a.next())c=c.value,c(b)},lYa=function(){var a,b,c;
return g.B(function(d){if(1==d.j)return g.ua(d,2),g.A(d,g.dt(),4);if(2!=d.j){a=d.u;if(!a||!g.ws()||"undefined"===typeof g.C.BroadcastChannel)return d.return();b=new VXa;return d.return(new l5(a,b))}c=g.wa(d);c instanceof Error&&g.S(c);return d.return()})},s5=function(){r5||(r5=lYa());
return r5},mYa=function(a){var b;
a=null==(b=a.options)?void 0:b.persistenceOption;return"ENTITY_PERSISTENCE_OPTION_PERSIST"===a||"ENTITY_PERSISTENCE_OPTION_INMEMORY_AND_PERSIST"===a},nYa=function(a){var b;
return g.B(function(c){return 1==c.j?g.A(c,s5(),2):(b=c.u)?g.A(c,m5(b,"readwrite",function(d){for(var e={},f={},k=g.r(a),l=k.next();!l.done;f={fh:f.fh,ot:f.ot},l=k.next())f.fh=l.value,f.fh.entityKey&&mYa(f.fh)&&(f.ot=g.Gf(f.fh.payload),l=void 0,"ENTITY_MUTATION_TYPE_REPLACE"===f.fh.type&&(l=function(m){return function(){return h5(d,m.fh.payload[m.ot],m.ot)}}(f)),"ENTITY_MUTATION_TYPE_DELETE"===f.fh.type&&(l=function(m){return function(){return j5(d,m.fh.entityKey)}}(f)),"ENTITY_MUTATION_TYPE_UPDATE"===
f.fh.type&&(l=function(m){return function(){return fYa(d,m.fh.entityKey,m.fh.payload[m.ot],m.ot)}}(f)),l&&(e[f.fh.entityKey]=e[f.fh.entityKey]?e[f.fh.entityKey].then(l):l()));
return g.Gs.all(Object.values(e))}),0):c.return()})},oYa=function(a){var b;
return g.B(function(c){if(1==c.j){b=a.mutations;if(!b||0>=b.length)return c.return();if(g.l0){var d={type:"ENTITY_LOADED"};void 0!==b&&(d.payload=b);g.l0.dispatch(d)}return g.A(c,nYa(b),2)}b.length=0;g.ta(c)})},pYa=function(a){return void 0!==a},t5=function(a,b,c){g.uv(new g.us("Woffle: "+a,c?{cotn:c}:""));
b instanceof Error&&g.uv(b)},qYa=function(a){var b,c,d,e,f,k,l,m,n,p,q,t,v,x,y,z,E;
return g.B(function(J){if(1==J.j)return g.A(J,m5(a,{mode:"readonly",Jc:!0},function(I){return f5(I,"playbackData").then(function(M){var da=M.map(function(pa){return pa.transfer}).filter(function(pa){return!!pa}),K=M.map(function(pa){return pa.offlineVideoPolicy}).filter(function(pa){return!!pa});
da=f5(I,"transfer",da);K=f5(I,"offlineVideoPolicy",K);return g.Gs.all([da,K]).then(function(pa){var za=g.r(pa);pa=za.next().value;za=za.next().value;return[M,pa,za]})})}),2);
b=J.u;c=g.r(b);d=c.next().value;e=c.next().value;f=c.next().value;k=d;l=e;m=f;n={};p={};q=g.r(l);for(t=q.next();!t.done;t=q.next())(v=t.value)&&(n[v.key]=v);x=g.r(m);for(y=x.next();!y.done;y=x.next())(z=y.value)&&(p[z.key]=z);E=k.map(function(I){var M=n[I.transfer],da=p[I.offlineVideoPolicy];I=g.VI(da.key).entityId;if("OFFLINE_VIDEO_POLICY_ACTION_DISABLE"===da.action){var K="OFFLINE_VIDEO_STATE_DISABLED";da.expirationTimestamp&&Number(da.expirationTimestamp)<Date.now()/1E3&&(K="OFFLINE_VIDEO_STATE_EXPIRED");
da=K}else if("OFFLINE_VIDEO_POLICY_ACTION_DOWNLOAD_FAILED"===da.action)da="OFFLINE_VIDEO_STATE_OFFLINE_FAILED";else{switch(null==M?void 0:M.transferState){case "TRANSFER_STATE_TRANSFER_IN_QUEUE":K="OFFLINE_VIDEO_STATE_PENDING";break;case "TRANSFER_STATE_TRANSFERRING":K="OFFLINE_VIDEO_STATE_TRANSFERRING";break;case "TRANSFER_STATE_PAUSED_BY_USER":K="OFFLINE_VIDEO_STATE_PAUSED_TRANSFER";break;case "TRANSFER_STATE_FAILED":K="OFFLINE_VIDEO_STATE_OFFLINE_FAILED";break;case "TRANSFER_STATE_COMPLETE":K=
"OFFLINE_VIDEO_STATE_PLAYABLE";break;case "TRANSFER_STATE_WAITING_FOR_PLAYER_RESPONSE_REFRESH":K="OFFLINE_VIDEO_STATE_STREAMS_OUT_OF_DATE";break;default:K="OFFLINE_VIDEO_STATE_UNKNOWN"}if("OFFLINE_VIDEO_STATE_OFFLINE_FAILED"===K)switch(null==M?void 0:M.failureReason){case "TRANSFER_FAILURE_REASON_EXTERNAL_FILESYSTEM_WRITE":case "TRANSFER_FAILURE_REASON_FILESYSTEM_WRITE":K="OFFLINE_VIDEO_STATE_OUT_OF_STORAGE_ERROR";break;case "TRANSFER_FAILURE_REASON_STREAM_MISSING":K="OFFLINE_VIDEO_STATE_STREAMS_MISSING";
break;case "TRANSFER_FAILURE_REASON_NETWORK":case "TRANSFER_FAILURE_REASON_NETWORK_LOST":K="OFFLINE_VIDEO_STATE_NETWORK_ERROR"}da=K}I={id:I,videoState:da};if(null==M?0:M.cotn)I.cotn=M.cotn;if(null==M?0:M.maximumDownloadQuality)I.selectedVideoQuality=null==M?void 0:M.maximumDownloadQuality;return I});
return J.return({offlineVideos:E})})},rYa=function(a){var b;
return g.B(function(c){if(1==c.j)return g.A(c,qYa(a),2);b=c.u;g.os("offlineStateSnapshot",b);g.ta(c)})},u5=function(a){g.G.call(this);
this.api=a;"undefined"!==typeof g.C.BroadcastChannel&&(this.j=new g.C.BroadcastChannel("PLAYER_OFFLINE_ERROR_SYNC:"+g.vs()),this.j.onmessage=this.B.bind(this),this.u=new g.C.BroadcastChannel("PLAYER_OFFLINE_PAUSE_SYNC:"+g.vs()),this.u.onmessage=this.C.bind(this))},v5=function(a,b){a.api.La("onOfflineOperationFailure",b);
var c;null==(c=a.j)||c.postMessage(b)},sYa=function(){this.locks=navigator.locks},tYa=function(){try{var a=g.Ja("ytglobal.locks_");
if(a)return a;var b;if(b=navigator){var c=navigator;b="locks"in c&&!!c.locks}if(b)return g.C.localStorage&&g.C.localStorage.getItem("noop"),a=new sYa,g.Ia("ytglobal.locks_",a),a}catch(d){}},vYa=function(a,b,c,d){var e=this;
this.N=a;this.V=b;this.visibility=c;this.L=d;this.C=this.I=this.D=this.u=this.j=!1;this.J=new g.L(function(){uYa(e)});
this.visibility.subscribe("visibilitystatechange",function(){e.rf()})},wYa=function(a){if(!a.u&&!a.j){var b=tYa();
if(b){a.u=!0;var c=g.vs("OfflineLockManager");b.request("woffle_orchestration_leader:"+c,{},function(){var d,e,f,k;return g.B(function(l){switch(l.j){case 1:return g.ua(l,2),a.B=new g.Cj,a.j=!0,a.u=!1,g.A(l,a.N(),4);case 4:return g.A(l,a.B.promise,5);case 5:g.va(l,0);break;case 2:d=g.wa(l),(null==(f=(e=a).L)?0:f.call(e,"wo_relinquish_leadership_on_lock_request_error"))||uYa(a),d instanceof Error&&(k=d,k.args=[{name:"WoLockManagerError",BC:d.name}],g.S(k)),g.ta(l)}})})}}},xYa=function(a){a.j&&(a.C=
!0,w5(a))},yYa=function(a,b){a.j&&(a.D=b,w5(a))},zYa=function(a,b){a.j&&(a.I=b,w5(a))},w5=function(a){a.I&&a.D&&a.C&&a.visibility.isBackground()?g.jp(a.J,6E4):a.J.stop()},uYa=function(a){a.B&&a.B.resolve();
a.j=!1;a.u=!1;a.V()},x5=function(a,b){var c=b.ej;
a.encryptedVideoId=b.videoId;a.cotn=c.cotn;a.offlineabilityFormatType=c.maximumDownloadQuality;var d;a.isRefresh=null!=(d=c.isRefresh)?d:!1;var e;a.softErrorCount=null!=(e=c.transferRetryCount)?e:0;g.os("offlineTransferStatusChanged",a)},AYa=function(a,b,c,d){b=Math.floor(b/1024).toFixed();
x5({transferStatusType:"TRANSFER_STATUS_TYPE_PROCESSING",statusType:"OFFLINING_STARTED",transferFirstStarted:!!d,alreadyDownloadedKbytes:b,totalFetchedKbytes:b,totalContentKbytes:Math.floor(c/1024).toFixed()},a)},BYa=function(a){x5({transferStatusType:"TRANSFER_STATUS_TYPE_DEQUEUED_BY_USER_PAUSE",
statusType:"SUSPENDED"},a)},CYa=function(a){switch(a){case "TRANSFER_FAILURE_REASON_FILESYSTEM_WRITE":case "TRANSFER_FAILURE_REASON_EXTERNAL_FILESYSTEM_WRITE":return"OFFLINE_DATABASE_ERROR";
case "TRANSFER_FAILURE_REASON_PLAYABILITY":return"NOT_PLAYABLE";case "TRANSFER_FAILURE_REASON_TOO_MANY_RETRIES":return"TOO_MANY_RETRIES";case "TRANSFER_FAILURE_REASON_INTERNAL":return"OFFLINE_DOWNLOAD_CONTROLLER_ERROR";case "TRANSFER_FAILURE_REASON_STREAM_MISSING":return"STREAM_VERIFICATION_FAILED";case "TRANSFER_FAILURE_REASON_SERVER":case "TRANSFER_FAILURE_REASON_SERVER_PROPERTY_MISSING":return"OFFLINE_REQUEST_FAILURE";case "TRANSFER_FAILURE_REASON_NETWORK":return"OFFLINE_NETWORK_ERROR";default:return"UNKNOWN_FAILURE_REASON"}},
y5=function(){},z5=function(){},A5=function(a){if(a.includes(":"))throw Error("Invalid user cache name: "+a);
return a+":"+g.vs("CacheStorage get")},DYa=function(){return g.B(function(a){if(void 0!==B5)return a.return(B5);
B5=new Promise(function(b){var c;return g.B(function(d){switch(d.j){case 1:return g.ua(d,2),g.A(d,C5.open("test-only"),4);case 4:return g.A(d,C5.delete("test-only"),5);case 5:g.va(d,3);break;case 2:if(c=g.wa(d),c instanceof Error&&"SecurityError"===c.name)return b(!1),d.return();case 3:b("caches"in window),g.ta(d)}})});
return a.return(B5)})},E5=function(){return g.B(function(a){if(1==a.j)return g.A(a,DYa(),2);
if(!a.u)return a.return(void 0);D5||(D5=new z5);return a.return(D5)})},EYa=function(){var a;
return g.B(function(b){return 1==b.j?g.A(b,E5(),2):(a=b.u)?b.return(a.delete("yt-player-local-img")):b.return(!0)})},FYa=function(a){var b,c;
return g.B(function(d){if(1==d.j)return g.A(d,E5(),2);if(3!=d.j){b=d.u;if(!b)throw Error("Cache API not supported");return a.length?g.A(d,b.open("yt-player-local-img"),3):d.return()}c=d.u;return g.A(d,Promise.all(a.map(function(e){return c.delete(e)})),0)})},GYa=function(a){var b,c;
return g.B(function(d){if(1==d.j)return g.A(d,E5(),2);if(3!=d.j){b=d.u;if(!b)throw Error("Cache API not supported");return a.length?g.A(d,b.open("yt-player-local-img"),3):d.return()}c=d.u;return g.A(d,c.addAll(a),0)})},F5=function(a){var b,c,d;
return 0<(null!=(d=null==(b=a.actionMetadata)?void 0:null==(c=b.retryScheduleIntervalsInSeconds)?void 0:c.length)?d:0)},G5=function(a){return"OFFLINE_ORCHESTRATION_ACTION_TYPE_ADD"===a.actionType&&!!a.entityKey},H5=function(a){return"OFFLINE_ORCHESTRATION_ACTION_TYPE_REFRESH"===a.actionType&&!!a.entityKey},J5=function(a,b,c,d){var e,f,k,l,m,n,p,q,t,v,x,y,z,E,J,I,M,da,K,pa,za,Xa,Pa,Ob,Db;
return g.B(function(zc){switch(zc.j){case 1:return e=g.WI(a,"ytMainVideoEntity"),f=g.WI(a,"ytMainChannelEntity"),k=g.WI(a,"transfer"),g.A(zc,m5(b,{mode:"readonly",Jc:!0},function(Sc){return g.Gs.all([e5(Sc,e,"ytMainVideoEntity"),e5(Sc,f,"ytMainChannelEntity"),e5(Sc,k,"transfer"),f5(Sc,"ytMainChannelEntity"),f5(Sc,"offlineOrchestrationActionWrapperEntity")])}),2);
case 2:l=zc.u;m=g.r(l);n=m.next().value;p=m.next().value;q=m.next().value;t=m.next().value;v=m.next().value;x=n;y=p;z=q;E=t;J=v;if(!x&&!y){zc.Sa(3);break}I=x?I5(x.thumbnail):[];if(!y){M=[];zc.Sa(4);break}return g.A(zc,HYa(y,E),5);case 5:M=zc.u;case 4:return da=M,g.A(zc,FYa(I.concat(da)),3);case 3:K=[];pa=g.WI(a,"ytMainDownloadedVideoEntity");za=g.WI(a,"mainVideoEntity");Xa=g.r(J);for(Pa=Xa.next();!Pa.done;Pa=Xa.next())Ob=Pa.value,Db=g.VI(Ob.key).entityId,Db!==a||IYa(c,Ob.actionProto)||K.push(Ob.key);
return g.A(zc,m5(b,{mode:"readwrite",Jc:!0},function(Sc){var hd=K.map(function(je){return j5(Sc,je)});
hd.push(j5(Sc,pa,{rF:!0}));hd.push(j5(Sc,za,{rF:!0}));return g.Gs.all(hd)}),7);
case 7:JYa(z),v5(d,{entityKey:pa,failureReason:"OFFLINE_OPERATION_FAILURE_REASON_VIDEO_DELETED"}),g.ta(zc)}})},LYa=function(a,b,c){var d,e,f,k,l,m;
return g.B(function(n){if(1==n.j)return g.A(n,m5(a,{mode:"readwrite",Jc:!0},function(p){var q=f5(p,"transfer"),t=f5(p,"offlineOrchestrationActionWrapperEntity");return g.Gs.all([q,t]).then(function(v){v=g.r(v);var x=v.next().value,y=v.next().value;v=KYa.map(function(I){return eYa(p,I)});
y=g.r(y);for(var z=y.next();!z.done;z=y.next()){z=z.value;var E="ytMainDownloadedVideoEntity"===g.VI(z.actionProto.entityKey).entityType,J="OFFLINE_ORCHESTRATION_ACTION_TYPE_ADD"===z.actionProto.actionType;IYa(b,z.actionProto)||E&&(!E||J)||v.push(j5(p,z.key,{rF:!0}))}return g.Gs.all(v).then(function(){return x})})}),2);
d=n.u;e=g.r(d);for(f=e.next();!f.done;f=e.next())k=f.value,JYa(k),l=g.VI(k.key).entityId,m=g.WI(l,"ytMainDownloadedVideoEntity"),v5(c,{entityKey:m,failureReason:"OFFLINE_OPERATION_FAILURE_REASON_VIDEO_DELETED"});return g.A(n,EYa(),0)})},IYa=function(a,b){return a.actionType===b.actionType&&a.entityKey===b.entityKey},JYa=function(a){if(a&&"TRANSFER_STATE_COMPLETE"!==a.transferState&&"TRANSFER_STATE_FAILED"!==a.transferState){var b=g.VI(a.key).entityId;
x5({transferStatusType:"TRANSFER_STATUS_TYPE_TERMINATED_BY_USER",statusType:"CANCELLED"},{videoId:b,ej:a})}},I5=function(a){if(!a||!a.thumbnails)return[];
var b=[];a=g.r(a.thumbnails);for(var c=a.next();!c.done;c=a.next())c=c.value,c.url&&b.push(c.url);return b},HYa=function(a,b){var c,d,e,f,k,l,m,n;
return g.B(function(p){c=I5(a.avatar);d=g.r(b);for(e=d.next();!e.done;e=d.next())if(f=e.value,f.id!==a.id)for(k=g.r(I5(f.avatar)),l=k.next();!l.done;l=k.next())m=l.value,n=c.indexOf(m),-1!==n&&c.splice(n,1);return p.return(c)})},K5=function(a){this.j=a},MYa=function(a,b){var c,d,e,f,k,l,m;
return g.B(function(n){switch(n.j){case 1:c=new Map,d=g.r(b),e=d.next();case 2:if(e.done){n.Sa(4);break}f=e.value;k=c;l=k.set;m=f;return g.A(n,a.B(f),5);case 5:l.call(k,m,n.u);e=d.next();n.Sa(2);break;case 4:return n.return(c)}})},L5=function(a,b,c,d){this.status=a;
this.j=b;this.u=c;this.failureReason=d},M5=function(a,b,c){this.j=a;
this.U=b;this.u=c},PYa=function(a,b){var c,d,e,f,k,l,m;
return g.B(function(n){switch(n.j){case 1:c=b.entityKey;f=null==(d=b.actionMetadata)?void 0:null==(e=d.playbackDataActionMetadata)?void 0:e.isEnqueuedForExpiredStreamUrlRefetch;g.ua(n,2);var p;var q=null!=(p=b.actionMetadata)&&p.playbackDataActionMetadata?{maximumDownloadQuality:b.actionMetadata.playbackDataActionMetadata.maximumDownloadQuality}:void 0;return g.A(n,NYa(a,c,{isEnqueuedForExpiredStreamUrlRefetch:f,SR:q}),4);case 4:return(k=n.u)?g.A(n,OYa(a,k,b),5):n.return(N5(b,!1,void 0,"OFFLINE_OPERATION_FAILURE_REASON_NETWORK_REQUEST_FAILED"));
case 5:return n.return(N5(b,!0,k.orchestrationActions));case 2:return l=g.wa(n),m="OFFLINE_OPERATION_FAILURE_REASON_UNKNOWN",l instanceof g.zs&&"QUOTA_EXCEEDED"===l.type&&(m="OFFLINE_OPERATION_FAILURE_REASON_DATABASE_REQUEST_FAILED"),t5("PDE handleAdd error"),n.return(N5(b,!1,void 0,m))}})},QYa=function(a,b){var c,d,e,f,k,l,m,n,p,q,t,v,x,y,z;
return g.B(function(E){switch(E.j){case 1:return c=b.entityKey,g.A(E,m5(a.j,{mode:"readonly",Jc:!0},function(J){var I=e5(J,c,"playbackData"),M=e5(J,g.WI(g.VI(b.entityKey).entityId,"offlineVideoPolicy"),"offlineVideoPolicy");J=e5(J,g.WI(g.VI(b.entityKey).entityId,"transfer"),"transfer");return g.Gs.all([I,M,J])}),2);
case 2:d=E.u;e=g.r(d);f=e.next().value;k=e.next().value;l=e.next().value;m=f;n=k;p=l;if(!m||!n)return E.return(N5(b,!0));q={lastPlayerResponseTimestampSeconds:m.playerResponseTimestamp,offlineToken:n.offlineToken};t={};if(null==(v=p)?0:v.maximumDownloadQuality)t.maximumDownloadQuality=p.maximumDownloadQuality;g.ua(E,3);return g.A(E,NYa(a,c,{refreshData:q,SR:t}),5);case 5:return(x=E.u)?g.A(E,OYa(a,x,b),6):E.return(N5(b,!1,void 0,"OFFLINE_OPERATION_FAILURE_REASON_NETWORK_REQUEST_FAILED"));case 6:return E.return(N5(b,
!0,x.orchestrationActions));case 3:return y=g.wa(E),z="OFFLINE_OPERATION_FAILURE_REASON_UNKNOWN",y instanceof g.zs&&"QUOTA_EXCEEDED"===y.type&&(z="OFFLINE_OPERATION_FAILURE_REASON_DATABASE_REQUEST_FAILED"),E.return(N5(b,!1,void 0,z))}})},NYa=function(a,b,c){var d,e,f;
return g.B(function(k){d=g.pI();var l=a.U,m=c.refreshData,n=c.isEnqueuedForExpiredStreamUrlRefetch,p=c.SR,q={entityKey:b};m&&(q.refreshData=m);n&&(q.isExpiredStreamUrlRefetch=n);p&&(q.downloadParameters=p);e={context:g.BI(l),signatureTimestamp:19115,videos:[q]};f=g.ZH(RYa);return k.return(g.jG(d,e,f))})},OYa=function(a,b,c){var d;
return g.B(function(e){if(1==e.j){if(!b.frameworkUpdates||!b.frameworkUpdates.entityBatchUpdate)return e.return();if(!(b.frameworkUpdates.entityBatchUpdate.mutations&&0<b.frameworkUpdates.entityBatchUpdate.mutations.length&&"ENTITY_MUTATION_TYPE_DELETE"===b.frameworkUpdates.entityBatchUpdate.mutations[0].type))return e.Sa(2);d=g.VI(b.frameworkUpdates.entityBatchUpdate.mutations[0].entityKey).entityId;return g.A(e,J5(d,a.j,c,a.u),2)}return g.A(e,oYa(b.frameworkUpdates.entityBatchUpdate),0)})},N5=function(a,
b,c,d){return new L5(b?"OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS":"OFFLINE_ORCHESTRATION_ACTION_RESULT_FAILURE",F5(a),c,d)},O5=function(){K5.apply(this,arguments)},TYa=function(a,b){var c,d;
return g.B(function(e){switch(e.j){case 1:return c=F5(b),g.A(e,p5(a.j,b.entityKey,"transfer"),2);case 2:if(d=e.u)return e.return(new L5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",c));g.ua(e,3);return g.A(e,SYa(a,b),5);case 5:g.va(e,4);break;case 3:return g.wa(e),e.return(new L5("OFFLINE_ORCHESTRATION_ACTION_RESULT_FAILURE",c,void 0,"OFFLINE_OPERATION_FAILURE_REASON_DATABASE_REQUEST_FAILED"));case 4:return e.return(new L5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",c))}})},UYa=function(a,b){var c,
d;
return g.B(function(e){switch(e.j){case 1:return c=F5(b),g.A(e,p5(a.j,b.entityKey,"transfer"),2);case 2:d=e.u;if(!d||"TRANSFER_STATE_COMPLETE"!==d.transferState)return e.return(new L5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",c));g.ua(e,3);return g.A(e,SYa(a,b,!0),5);case 5:g.va(e,4);break;case 3:return g.wa(e),e.return(new L5("OFFLINE_ORCHESTRATION_ACTION_RESULT_FAILURE",c,void 0,"OFFLINE_OPERATION_FAILURE_REASON_DATABASE_REQUEST_FAILED"));case 4:return e.return(new L5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",
c))}})},SYa=function(a,b,c){c=void 0===c?!1:c;
var d,e,f,k,l,m;return g.B(function(n){if(1==n.j)return e=null==(d=b.actionMetadata)?void 0:d.transferEntityActionMetadata,l={key:b.entityKey,transferState:"TRANSFER_STATE_TRANSFER_IN_QUEUE",cotn:g.Av(16),enqueuedTimestampMs:Date.now().toString(),maximumDownloadQuality:null==(f=e)?void 0:f.maximumDownloadQuality,preferredAudioTrack:null==(k=e)?void 0:k.preferredAudioTrack,transferRetryCount:0,isRefresh:c,hasLoggedFirstStarted:!1},m=g.VI(l.key).entityId,g.A(n,m5(a.j,{mode:"readwrite",Jc:!0},function(p){var q=
[];c&&q.push(j5(p,g.WI(m,"offlineVideoStreams")));q.push(h5(p,l,"transfer"));return g.Gs.all(q)}),2);
x5({transferStatusType:"TRANSFER_STATUS_TYPE_ENQUEUED",statusType:"ADDED_TO_QUEUE"},{videoId:m,ej:l});g.ta(n)})},VYa=function(a,b,c){return new g.zD(a,{cotn:b,
raw_player_response:c,download_media:!0,start:Infinity,disable_watch_next:!0})},WYa=function(){return{priority:1,
retryScheduleIntervalsInSeconds:[1,2,4]}},P5=function(a,b,c,d,e,f,k,l,m,n,p){this.entityType=a;
this.actionId=b;this.action=c;this.parentActionId=d;this.rootActionId=void 0===e?b:e;this.childActionIds=f;this.prereqActionId=k;this.postreqActionIds=l;this.hasChildActionFailed=n;this.retryScheduleIndex=0;this.j=p||Date.now();this.retryScheduleIndex=m||0},Q5=function(a){return{key:g.WI(a.actionId,"offlineOrchestrationActionWrapperEntity"),
actionProto:a.action,parentActionId:a.parentActionId,rootActionId:a.rootActionId,childActionIds:a.childActionIds,prereqActionId:a.prereqActionId,postreqActionIds:a.postreqActionIds,retryScheduleIndex:a.retryScheduleIndex,hasChildActionFailed:a.hasChildActionFailed,enqueueTimeSec:(a.j/1E3).toFixed()}},XYa=function(){this.j=new Map},YYa=function(){R5||(R5=new XYa);
return R5},ZYa=function(a,b){return{eventType:{flowEventNamespace:"FLOW_EVENT_NAMESPACE_OFFLINE_ORCHESTRATION",
flowEventType:a},metadata:b,statusCode:void 0,csn:void 0,can:void 0}},$Ya=function(a,b,c){if(!c){var d=void 0===d?!1:d;
c=a.j.get("FLOW_TYPE_OFFLINE_ORCHESTRATION");if(!c||d)c=g.Av(16),a.j.set("FLOW_TYPE_OFFLINE_ORCHESTRATION",c)}a={flowNonce:c,flowType:"FLOW_TYPE_OFFLINE_ORCHESTRATION",flowEventType:b.eventType};b.metadata&&(a.flowMetadata=b.metadata);void 0!==b.statusCode&&(a.flowEventStatus=b.statusCode);b.csn&&(a.csn=b.csn);b.can&&(a.can=b.can);g.os("flowEvent",a,void 0)},aZa=function(a,b,c){if(!a.action.entityKey)throw Error("entityKey is missing.");
var d=g.VI(a.action.entityKey);a={entityType:d.AV,entityId:d.entityId,offlineOrchestrationActionType:a.action.actionType,orchestrationAction:{orchestrationActionId:a.actionId}};b&&(a.offlineOrchestrationActionResult=b.status,a.isRetryable=b.j);c&&(a.additionalOrchestrationActions=c.map(function(e){return{orchestrationActionId:e.actionId}}));
return a},S5=function(a,b){var c={offlineOrchestrationContext:aZa(a)};
b=ZYa(b,c);$Ya(YYa(),b,a.rootActionId)},T5=function(a,b,c){c=void 0===c?[]:c;
b={offlineOrchestrationContext:aZa(a,b,c)};b=ZYa(3,b);$Ya(YYa(),b,a.rootActionId)},bZa=function(){this.actions=[]},cZa=function(a,b){b=g.r(b);
for(var c=b.next();!c.done;c=b.next())c=c.value,S5(c,1),a.actions.push(c);a.actions.sort(a.j)},dZa=function(a,b){a=g.r(a.actions);
for(var c=a.next();!c.done;c=a.next())if(c.value.actionId===b)return!0;return!1},U5=function(a,b,c,d){g.G.call(this);
var e=this;this.u=a;this.Y=b;this.V=c;this.D=d;this.j=new bZa;this.N=new g.Gt;this.C=new g.L(function(){e.retry()});
this.I=NaN;g.H(this,this.C);this.J=n5(this.u,this.W.bind(this))},fZa=function(a,b,c,d){var e;
return g.B(function(f){if(1==f.j)return e=new U5(a,b,c,d),g.A(f,eZa(e),2);e.B?Promise.resolve():V5(e);return f.return(e)})},V5=function(a){var b,c,d,e,f,k,l,m,n,p,q,t,v,x,y;
return g.B(function(z){switch(z.j){case 1:if(a.B)throw Error("Already processing an action");if(a.isDisposed())return z.return();b=a.j.actions.shift();yYa(a.V,!b);if(void 0===b)return z.return();for(c=[b];;)if((d=a.j.actions[0])&&0===d.retryScheduleIndex&&d.entityType===b.entityType)c.push(a.j.actions.shift());else break;a.B=c;if(e=a.Y[b.entityType]){z.Sa(2);break}a.B=void 0;return g.A(z,V5(a),3);case 3:return z.return();case 2:f=g.r(c);for(k=f.next();!k.done;k=f.next())l=k.value,S5(l,2);g.ua(z,4,
5);return g.A(z,MYa(e,c.map(function(E){return E.action})),7);
case 7:m=z.u,n=g.r(c),k=n.next();case 8:if(k.done){z.Sa(5);break}p=k.value;q=m.get(p.action);return g.A(z,gZa(a,p,q),9);case 9:k=n.next();z.Sa(8);break;case 5:g.xa(z);a.B=void 0;g.ya(z,6);break;case 4:return t=g.wa(z),t5("Orchestration error",t),g.ua(z,12),g.A(z,hZa(a,c),14);case 14:g.va(z,5);break;case 12:v=g.wa(z);t5("Orchestration retry error",v);x=g.r(c);for(k=x.next();!k.done;k=x.next())y=k.value,3>y.retryScheduleIndex&&cZa(a.j,[y]);z.Sa(5);break;case 6:return g.A(z,V5(a),0)}})},gZa=function(a,
b,c){var d,e,f,k,l,m;
return g.B(function(n){if(1==n.j){if("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS"===c.status){k=void 0;try{k=null==(l=c.u)?void 0:l.map(function(p){return a.createAction(p,b)})}catch(p){return T5(b,c),m={entityKey:b.action.entityKey,
failureReason:"OFFLINE_OPERATION_FAILURE_REASON_UNSUPPORTED_ENTITY_FAILED"},v5(a.D,m),t5("Orchestration subactions creation error",p),n.return()}T5(b,c,k);return g.A(n,m5(a.u,{mode:"readwrite",Jc:!0},function(p){var q=[];if(k){var t=k.map(function(v){return Q5(v)});
q.push(i5(p,t,"offlineOrchestrationActionWrapperEntity"))}t=Q5(b);q.push(j5(p,t.key));return g.Gs.all(q)}),9)}if("OFFLINE_ORCHESTRATION_ACTION_RESULT_FAILURE"!==c.status)return n.Sa(0);
T5(b,c);if(c.j&&3>b.retryScheduleIndex+1)return g.A(n,hZa(a,[b]),0);e=(null==(d=c)?0:d.failureReason)?c.failureReason:"OFFLINE_OPERATION_FAILURE_REASON_UNKNOWN";f={entityKey:b.action.entityKey,failureReason:e};v5(a.D,f);t5("Orchestration result is not retryable, deleting action");return g.A(n,kYa(a.u,Q5(b).key),0)}S5(b,4);g.ta(n)})},W5=function(a,b){var c,d,e,f,k,l,m,n,p,q,t,v;
return g.B(function(x){c=[];d=Infinity;e=4E3;f=g.r(b);for(k=f.next();!k.done;k=f.next())l=k.value,m=Number(l.enqueueTimeSec),n=iZa(m),p=l.retryScheduleIndex,q=null!=p&&0<p,0<n&&q?(d=Math.min(d,m),e=Math.min(n,e)):c.push(l);isFinite(d)&&(!a.C.isActive()||d<a.I)&&(a.I=d,a.C.start(e));a.N.qf()||(t=c.length,c=c.filter(function(y){var z;y=(null==(z=y.actionProto)?void 0:z.actionType)||"OFFLINE_ORCHESTRATION_ACTION_TYPE_UNKNOWN";return!jZa.includes(y)}),v=c.length<t,!a.C.isActive()&&v&&a.C.start(1));
0<c.length&&kZa(a,c);return g.A(x,a.B?Promise.resolve():V5(a),0)})},mZa=function(a){var b,c,d,e,f,k,l;
return g.B(function(m){if(1==m.j)return g.A(m,lZa(a),2);b=m.u;c=[];d=g.r(b);for(e=d.next();!e.done;e=d.next())f=e.value,k=g.VI(f.key),l=k.entityId,dZa(a.j,l)||c.push(f);return g.A(m,W5(a,c),0)})},iZa=function(a){a=1E3*a-Date.now();
return 4E3<a?4E3:a},hZa=function(a,b){var c,d,e;
return g.B(function(f){c=g.r(b);for(d=c.next();!d.done;d=c.next()){e=d.value;var k=void 0,l=void 0,m=(null==(l=e.action)?void 0:null==(k=l.actionMetadata)?void 0:k.retryScheduleIntervalsInSeconds)||[1,2,4];k=1;e.retryScheduleIndex<m.length&&(k=m[e.retryScheduleIndex]);e.j=1E3*k+Date.now();e.retryScheduleIndex++}return g.A(f,nZa(a,b),0)})},eZa=function(a){var b;
return g.B(function(c){if(1==c.j)return g.A(c,q5(a.u,"offlineOrchestrationActionWrapperEntity"),2);b=c.u;return g.A(c,W5(a,b),0)})},kZa=function(a,b){0!==b.length&&b.forEach(function(c){if(!c.key)throw Error("Entity key is required.");
if(!c.actionProto)throw Error("OfflineOrchestrationAction is required.");var d=g.VI(c.key),e=g.VI(c.actionProto.entityKey);c=new P5(e.entityType,d.entityId,c.actionProto,c.parentActionId,c.rootActionId,c.childActionIds,c.prereqActionId,c.postreqActionIds,c.retryScheduleIndex,c.hasChildActionFailed,1E3*Number(c.enqueueTimeSec));3>c.retryScheduleIndex&&cZa(a.j,[c])})},lZa=function(a,b){var c;
return g.B(function(d){if(1==d.j)return g.A(d,q5(a.u,"offlineOrchestrationActionWrapperEntity",b),2);c=d.u;return d.return(c.filter(pYa))})},nZa=function(a,b){if(0===b.length)return Promise.resolve([]);
b=b.map(function(c){return Q5(c)});
return jYa(a.u,b)},oZa=function(){this.j=void 0},qZa=function(a,b){var c,d,e,f,k;
return g.B(function(l){c=b.videoId;d=b.S();e=!0;if(b.captionTracks.length)f=FXa(b),a.j=new g.RJ(d,b,f);else if(b.Kc)k=g.Ewa(b),a.j=new g.TJ(d,b.Kc,c,k,b.ql),e=b.ql;else return l.return();return l.return(new Promise(function(m){var n;null==(n=a.j)||n.Su(function(){return g.B(function(p){if(1==p.j)return g.A(p,pZa(a,c,e),2);m();g.ta(p)})})}))})},pZa=function(a,b,c){c=void 0===c?!0:c;
var d,e,f,k,l,m,n,p,q,t,v,x,y,z;return g.B(function(E){switch(E.j){case 1:if(!a.j)return E.return();d=[];e=g.OJ(a.j.u,c);f=[];k={};l=g.r(e.entries());for(m=l.next();!m.done;k={HD:k.HD},m=l.next())n=m.value,p=g.r(n),q=p.next().value,t=p.next().value,k.HD=q,v=t,x=a.j.yr(v,"json3"),y=g.lr(x,{withCredentials:!0,format:"RAW"},3,500).then(function(J){return function(I){I={metadata:g.kD(e[J.HD]),trackData:I.xhr.responseText};f.push(I)}}(k)).Di(function(J){t5("Caption fetch error",J)}),d.push(y);
return g.A(E,GXa(d),2);case 2:return g.ua(E,3),g.A(E,KXa(b,f),5);case 5:g.va(E,0);break;case 3:z=g.wa(E),t5("Caption DB transaction error",z),g.ta(E)}})},rZa=function(a){var b;
return g.B(function(c){if(1==c.j)return g.A(c,LXa(a),2);b=c.u;return c.return(!!b&&0<b.length)})},sZa=function(a,b){this.api=a;
this.j=b;this.logger=new g.TO("woffle");this.u=!1},tZa=function(a){return g.B(function(b){return b.return(MXa(a))})},uZa=function(a){var b;
return g.B(function(c){if(1==c.j)return g.A(c,g.pva(a),2);b=c.u;return c.return(b.filter(function(d){return!!d.url}).map(function(d){return d.url}))})},X5=function(a,b){var c=g.dD(b);
if(1===c||0===c)return Promise.resolve();(c=vZa(a,b))&&c.stopVideo();a.B=0;return tZa(b)},Y5=function(a,b,c,d){c=void 0===c?!1:c;
d=void 0===d?!0:d;var e="string"===typeof b?b:b.videoDetails.videoId;2===g.dD(e)&&((b=vZa(a,e))?b.stopVideo():a.logger.info(function(){return"Corresponding player for "+e+" not found. Pausing anyway"}),g.eD(e,2),a.B=2,c?wZa(a.j):d&&xZa(a.j))},vZa=function(a,b){var c;
return(null==(c=a.player)?void 0:c.getVideoData().videoId)===b?a.player:null},yZa=function(a){switch(a){case "HD_1080":return"hd1080";
case "HD":return"hd720";case "SD":return"large";case "LD":return"tiny";default:return"hd720"}},Z5=function(a){g.G.call(this);
this.j=a;this.u=n5(this.j,this.B.bind(this))},zZa=function(a,b){var c,d,e,f,k,l,m;
return g.B(function(n){switch(n.j){case 1:if(0===b.length)return n.return([]);c=b.map(function(p){return g.WI(p,"transfer")});
return g.A(n,q5(a.j,"transfer",c),2);case 2:d=n.u;e=d.filter(pYa).map(function(p){return g.VI(p.key).entityId});
f=b.filter(function(p){return-1===e.indexOf(p)});
if(0===f.length)return n.return([]);k=g.r(f);l=k.next();case 3:if(l.done){n.Sa(5);break}m=l.value;return g.A(n,tZa(m),4);case 4:l=k.next();n.Sa(3);break;case 5:return n.return(f)}})},BZa=function(a,b,c,d,e,f){var k,l,m;
return g.B(function(n){k="STREAM_TYPE_UNKNOWN";c.video&&c.audio?(k="STREAM_TYPE_AUDIO_AND_VIDEO",t5("unexpected stream type")):c.video&&!c.audio?k="STREAM_TYPE_VIDEO":!c.video&&c.audio&&(k="STREAM_TYPE_AUDIO");l=g.WI(b,"offlineVideoStreams");m={numBytesDownloaded:e.toFixed(),numTotalBytes:f.toFixed(),streamType:k,streamState:"DOWNLOAD_STREAM_STATE_IN_PROGRESS",formatStreamBytes:JSON.stringify(d),itag:"STREAM_TYPE_AUDIO_AND_VIDEO"===k?Number(c.Xb()):void 0};return g.A(n,m5(a,{mode:"readwrite",Jc:!0},
function(p){var q=e5(p,l,"offlineVideoStreams"),t=e5(p,g.WI(b,"transfer"),"transfer");return g.Gs.all([q,t]).then(function(v){var x=g.r(v);v=x.next().value;x=x.next().value;if(!x)return j5(p,l).then(function(){});
v=[h5(p,AZa(v,d,m,l),"offlineVideoStreams")];x.offlineVideoStreams||(x.offlineVideoStreams=[]);-1===x.offlineVideoStreams.indexOf(l)&&(x.offlineVideoStreams.push(l),v.push(h5(p,x,"transfer")));return g.Gs.all(v)})}),0)})},CZa=function(a,b){var c,d,e,f,k;
return g.B(function(l){if(1==l.j)return c=g.WI(b,"offlineVideoStreams"),g.A(l,p5(a,c,"offlineVideoStreams"),2);d=l.u;if(!d||!d.streamsProgress)return l.return();e=g.r(d.streamsProgress);for(f=e.next();!f.done;f=e.next())k=f.value,k.streamState="DOWNLOAD_STREAM_STATE_COMPLETE",k.numTotalBytes!==k.numBytesDownloaded&&(k.numBytesDownloaded=k.numTotalBytes);return g.A(l,o5(a,d,"offlineVideoStreams"),0)})},AZa=function(a,b,c,d){if(a&&a.streamsProgress){d=a;
a:{b=b.itag+";"+b.xtags;for(var e=a.streamsProgress,f=0;f<e.length;f++){var k=JSON.parse(e[f].formatStreamBytes);if(k.itag+";"+k.xtags===b){e[f]=c;c=e;break a}}e.push(c);c=e}d.streamsProgress=c}else a={key:d,streamsProgress:[c]};return a},$5=function(a,b,c,d){g.G.call(this);
var e=this;this.u=a;this.api=b;this.va=c;this.ma=d;this.D=new g.Gt;this.C=new g.L(function(){e.j&&"TRANSFER_STATE_TRANSFERRING"===e.j.transferState&&e.D.qf()&&(3>(e.j.transferRetryCount||0)?Y5(e.I,e.B,!1,!1):X5(e.I,e.B.videoDetails.videoId),e.Zr("TRANSFER_FAILURE_REASON_TIMEOUT_NO_PROGRESS"))});
this.V=0;this.oa=new g.Uz(this);this.J=n5(this.u,this.sU.bind(this));this.I=new sZa(b,this);this.Fa=new oZa;this.N=new Z5(this.u);this.Y=this.D.Ja("publicytnetworkstatus-online",this.oz.bind(this));this.W=this.D.Ja("publicytnetworkstatus-offline",this.t_.bind(this));g.H(this,this.oa);this.oa.P(b,"offlinetransferpause",this.u_);this.Da=g.PA(this.api.S().experiments,"web_player_transfer_timeout_threshold_ms")},DZa=function(a){return g.B(function(b){if(1==b.j)b=g.A(b,JXa(),2);
else{var c=a.N;var d=g.cD();d=Object.keys(d);c=zZa(c,d);b=g.A(b,c,0)}return b})},b6=function(a,b){b=void 0===b?!1:b;
var c;return g.B(function(d){if(1==d.j){if(a.j)throw Error("Already downloading a video");return g.A(d,EZa(a),2)}return 4!=d.j?(c=d.u,zYa(a.va,!c),c&&a.D.qf()?b?g.A(d,new Promise(function(e){g.dr(e,1E3)}),4):d.Sa(4):(!c&&a.j&&a6(a),d.Sa(0))):g.A(d,FZa(a,c),0)})},GZa=function(a){return g.B(function(b){if(1==b.j)return a.B?g.A(b,X5(a.I,a.B.videoDetails.videoId),3):b.Sa(0);
a6(a);g.ta(b)})},HZa=function(a,b){var c,d,e;
return g.B(function(f){switch(f.j){case 1:return g.ua(f,2),(c=!!b.captionTracks.length||!!b.Kc)?g.A(f,rZa(b.videoId),4):f.return();case 4:return(d=f.u)?f.return():g.A(f,qZa(a.Fa,b),5);case 5:g.va(f,0);break;case 2:e=g.wa(f),t5("Caption downloading error",e,b.cotn),g.ta(f)}})},FZa=function(a,b){var c,d,e,f,k;
return g.B(function(l){switch(l.j){case 1:return a.j=b,c=g.VI(a.j.key),"TRANSFER_STATE_TRANSFERRING"===a.j.transferState&&x5({transferStatusType:"TRANSFER_STATUS_TYPE_RESUME_PROCESSING",statusType:"OFFLINING_RETRIED"},{videoId:c.entityId,ej:a.j}),g.A(l,c6(a),2);case 2:return d=null,g.ua(l,3),g.A(l,IZa(a,b),5);case 5:d=l.u;a.B=d;g.va(l,4);break;case 3:return e=g.wa(l),t5("error getting player response",e,b.cotn),g.A(l,a.Zr("TRANSFER_FAILURE_REASON_INTERNAL"),6);case 6:return l.return();case 4:return f=
VYa(a.api.S(),b.cotn,d),g.A(l,HZa(a,f),7);case 7:return k=f,g.A(l,uZa(f.videoId),8);case 8:k.Pm=l.u;var m=a.I,n=b.maximumDownloadQuality;f.getPlayerResponse();g.eD(f.videoId,2);m.B=2;m.u=!1;var p;null==(p=m.player)||p.dispose();m.player=m.api.So(9,f);p={};g.Wu(m.player,(p.localmediachange=m.tC,p.signatureexpired=m.YH,p.statechange=m.lY,p),m);n=yZa(n);m.L("hoffle_lmqf_killswitch")||g.TLa(m.player,g.vx(n,n,!0,"m"),!1);g.iO(m.player,!1);d6(a);g.ta(l)}})},EZa=function(a){var b,c;
return g.B(function(d){if(1==d.j)return g.A(d,q5(a.u,"transfer"),2);b=d.u;c=b.filter(JZa).sort(KZa);return 0===c.length?d.return():d.return(c[0])})},c6=function(a){return g.B(function(b){d6(a);
return g.A(b,e6(a,"TRANSFER_STATE_TRANSFERRING"),0)})},wZa=function(a){var b;
g.B(function(c){if(1==c.j)return a.C.stop(),g.A(c,e6(a,"TRANSFER_STATE_PAUSED_BY_USER"),2);b=g.VI(a.j.key);BYa({videoId:b.entityId,ej:a.j});a6(a);b6(a);g.ta(c)})},xZa=function(a){g.B(function(b){if(1==b.j)return a.C.stop(),g.A(b,e6(a,"TRANSFER_STATE_TRANSFER_IN_QUEUE"),2);
a6(a);g.ta(b)})},LZa=function(a){var b,c,d;
g.B(function(e){switch(e.j){case 1:a.C.stop();if(!a.j||!a.B){e.Sa(2);break}b=VYa(a.api.S(),a.j.cotn,a.B);return g.A(e,HZa(a,b),2);case 2:return g.A(e,e6(a,"TRANSFER_STATE_COMPLETE","DOWNLOAD_STREAM_STATE_COMPLETE"),4);case 4:return c=g.VI(a.j.key),d=c.entityId,g.A(e,CZa(a.u,d),5);case 5:x5({transferStatusType:"TRANSFER_STATUS_TYPE_COMPLETED",statusType:"SUCCESS"},{videoId:d,ej:a.j}),a6(a),b6(a),g.ta(e)}})},NZa=function(a,b,c){var d;
g.B(function(e){switch(e.j){case 1:if("TRANSFER_STATE_TRANSFERRING"===a.j.transferState){e.Sa(2);break}return g.A(e,c6(a),2);case 2:d=Date.now();if(!(1E3<d-a.V)){e.Sa(4);break}a.V=d;return g.A(e,BZa(a.u,c.videoId,c.u,c.formatStream,c.bytesDownloaded,c.j),5);case 5:if(a.j.hasLoggedFirstStarted){AYa({videoId:b,ej:a.j},c.bytesDownloaded,c.j);e.Sa(4);break}a.j.hasLoggedFirstStarted=!0;return g.A(e,MZa(a),7);case 7:AYa({videoId:b,ej:a.j},c.bytesDownloaded,c.j,!0);case 4:d6(a),g.ta(e)}})},OZa=function(a){var b=
3>(a.j.transferRetryCount||0);
b&&(a=a.j,a.transferRetryCount=(a.transferRetryCount||0)+1);return b},PZa=function(a,b){b=void 0===b?"TRANSFER_FAILURE_REASON_UNKNOWN":b;
var c,d;return g.B(function(e){if(1==e.j)return c="OFFLINE_OPERATION_FAILURE_REASON_UNKNOWN","TRANSFER_FAILURE_REASON_NETWORK"===b?c="OFFLINE_OPERATION_FAILURE_REASON_NETWORK_REQUEST_FAILED":"TRANSFER_FAILURE_REASON_FILESYSTEM_WRITE"===b&&(c="OFFLINE_OPERATION_FAILURE_REASON_DATABASE_REQUEST_FAILED"),g.A(e,e6(a,"TRANSFER_STATE_FAILED","DOWNLOAD_STREAM_STATE_ERROR_STREAMS_MISSING",b),2);v5(a.ma,{entityKey:a.j.key,failureReason:c});d=g.VI(a.j.key).entityId;var f={videoId:d,ej:a.j},k=b,l={transferStatusType:"TRANSFER_STATUS_TYPE_TERMINATED_WITH_FAILURE",
statusType:"FAILED"};k&&(l.transferFailureReason=k,l.failureReason=CYa(k));x5(l,f);g.ta(e)})},e6=function(a,b,c,d){var e;
return g.B(function(f){if(1==f.j)return a.j.transferState=b,a.j.failureReason=d,g.ua(f,2),g.A(f,MZa(a,function(k){return c?f5(k,"offlineVideoStreams",a.j.offlineVideoStreams).then(function(l){for(var m=g.r(l),n=m.next();!n.done;n=m.next())if((n=n.value)&&n.streamsProgress){n=g.r(n.streamsProgress);for(var p=n.next();!p.done;p=n.next())p.value.streamState=c}return i5(k,l.filter(function(q){return!!q}),"offlineVideoStreams")}):g.Gs.resolve(void 0)}),4);
if(2!=f.j)return g.va(f,0);e=g.wa(f);return e instanceof g.zs&&"QUOTA_EXCEEDED"===e.type?g.A(f,a.Zr("TRANSFER_FAILURE_REASON_FILESYSTEM_WRITE"),0):f.Sa(0)})},MZa=function(a,b){var c;
return g.B(function(d){if(!a.j)return d.return();c=a.j;return g.A(d,m5(a.u,{mode:"readwrite",Jc:!0},function(e){var f=[h5(e,c,"transfer")];b&&f.push(b(e));return g.Gs.all(f)}),0)})},a6=function(a){a.j=void 0;
a.B=void 0;a.C.stop()},IZa=function(a,b){var c,d,e,f,k;
return g.B(function(l){if(1==l.j)return c=g.VI(b.key),d=c.entityId,e=g.WI(d,"playbackData"),g.A(l,p5(a.u,e,"playbackData"),2);f=l.u;if(null==(k=f)?0:k.playerResponseJson)return l.return(JSON.parse(f.playerResponseJson));throw Error("No PlayerResponse found");})},d6=function(a){a.C.start(a.Da||18E5)},JZa=function(a){return void 0!==f6[a.transferState]},KZa=function(a,b){var c=f6[a.transferState],d=f6[b.transferState];
return c!==d?c-d:Number(a.enqueuedTimestampMs)-Number(b.enqueuedTimestampMs)},g6=function(a,b){var c=this;
this.U=a;this.api=b;this.N=new g.Gt;this.u=new vYa(function(){return QZa(c)},function(){RZa(c)},this.api.yp(),this.api.L.bind(this.api));
this.B=new u5(this.api);this.C=new g.Cj;wYa(this.u)},QZa=function(a){return g.B(function(b){a.api.La("onOrchestrationBecameLeader");
a.j&&a.D||SZa(a).then(a.C.resolve).catch(a.C.reject);var c=a.C.promise;return g.A(b,c,0)})},SZa=function(a){var b,c,d;
return g.B(function(e){if(1==e.j)return g.A(e,s5(),2);if(3!=e.j){b=e.u;if(!b)return t5("PES is undefined"),e.return();a.j=new $5(b,a.api,a.u,a.B);c=a.jG(b);d=a;return g.A(e,fZa(b,c,a.u,a.B),3)}d.D=e.u;return g.A(e,TZa(a),0)})},TZa=function(a){var b;
return g.B(function(c){switch(c.j){case 1:if(!a.j)return t5("transferManager is undefined"),c.return();if(a.j.j){c.Sa(2);break}return g.A(c,b6(a.j),2);case 2:return g.A(c,a.kz(),4);case 4:return a.I=g.er(function(){a.kz()},9E5),g.es(g.gs(),function(){return a.OI()}),g.A(c,s5(),5);
case 5:return b=c.u,g.A(c,rYa(b),6);case 6:xYa(a.u),g.ta(c)}})},RZa=function(a){var b,c;
g.B(function(d){if(1==d.j)return a.j||a.D?g.A(d,a.C.promise,2):d.return();void 0!==a.I&&(window.clearInterval(a.I),a.I=void 0);null==(b=a.j)||b.dispose();a.j=void 0;null==(c=a.D)||c.dispose();a.D=void 0;a.api.La("onOrchestrationLostLeader");a.C=new g.Cj;g.ta(d)})},UZa=function(){var a,b,c,d,e,f;
return g.B(function(k){switch(k.j){case 1:return g.A(k,s5(),2);case 2:a=k.u;if(!a)return k.return([]);b=Date.now()/1E3;return g.A(k,q5(a,"offlineVideoPolicy"),3);case 3:c=k.u,d=g.r(c),e=d.next();case 4:if(e.done){k.Sa(6);break}f=e.value;if(!(f.expirationTimestamp&&Number(f.expirationTimestamp)<b)){k.Sa(5);break}f.action="OFFLINE_VIDEO_POLICY_ACTION_DISABLE";return g.A(k,o5(a,f,"offlineVideoPolicy"),5);case 5:e=d.next();k.Sa(4);break;case 6:return k.return(c.map(function(l){return l.key}))}})},h6=
function(a,b,c,d,e){var f,k,l;
return g.B(function(m){if(1==m.j)return g.A(m,s5(),2);f=m.u;if(!f)return m.return([]);k=b.map(function(n){var p=g.WI(n,c);p={actionType:d,entityKey:p,actionMetadata:Object.assign({},WYa(),e)};"OFFLINE_ORCHESTRATION_ACTION_TYPE_REFRESH"!==d&&(p.actionMetadata.priority=0);n=new P5(c,n,p);return Q5(n)});
l=jYa(f,k);wYa(a.u);return m.return(l)})},WZa=function(a){var b,c,d,e,f;
return g.B(function(k){switch(k.j){case 1:return b=g.pI(),c=NXa(a),d=g.ZH(VZa),g.ua(k,2),g.A(k,g.jG(b,c,d),4);case 4:e=k.u;g.va(k,3);break;case 2:throw f=g.wa(k),t5("GetOffline fetch request error",f),Error("GetOffline fetch request error");case 3:if(!e)throw Error("Network request failed");if(!e.videos||!e.videos.length)throw Error("No data");return k.return(e.videos.map(function(l){return l.offlineVideoData}))}})},i6=function(a,b,c){this.j=a;
this.U=b;this.u=c},ZZa=function(a,b){var c,d,e,f,k,l;
return g.B(function(m){switch(m.j){case 1:return c=F5(b),d=g.VI(b.entityKey),e=d.entityId,g.ua(m,2),g.A(m,XZa(a,e),4);case 4:g.va(m,3);break;case 2:return f=g.wa(m),k="OFFLINE_OPERATION_FAILURE_REASON_UNKNOWN",f instanceof g.zs&&"QUOTA_EXCEEDED"===f.type&&(k="OFFLINE_OPERATION_FAILURE_REASON_DATABASE_REQUEST_FAILED"),m.return(new L5("OFFLINE_ORCHESTRATION_ACTION_RESULT_FAILURE",c,void 0,k));case 3:var n;var p=null!=(n=b.actionMetadata)&&n.ytMainDownloadedVideoEntityActionMetadata?{playbackDataActionMetadata:{maximumDownloadQuality:b.actionMetadata.ytMainDownloadedVideoEntityActionMetadata.maximumDownloadQuality}}:
void 0;l=YZa("OFFLINE_ORCHESTRATION_ACTION_TYPE_ADD",e,p);return m.return(new L5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",c,[l]))}})},$Za=function(a,b){var c,d,e,f,k,l,m;
return g.B(function(n){switch(n.j){case 1:return c=F5(b),d=g.VI(b.entityKey),e=d.entityId,g.A(n,p5(a.j,b.entityKey,"ytMainDownloadedVideoEntity"),2);case 2:f=n.u;if(!f)return n.return(new L5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",c));g.ua(n,3);return g.A(n,XZa(a,e,f.addedTimestampMillis),5);case 5:k=YZa("OFFLINE_ORCHESTRATION_ACTION_TYPE_REFRESH",e);g.va(n,4);break;case 3:return l=g.wa(n),l instanceof Error&&"No data"===l.message?g.A(n,J5(e,a.j,b,a.u),4):(m="OFFLINE_OPERATION_FAILURE_REASON_UNKNOWN",
l instanceof g.zs&&"QUOTA_EXCEEDED"===l.type&&(m="OFFLINE_OPERATION_FAILURE_REASON_DATABASE_REQUEST_FAILED"),n.return(new L5("OFFLINE_ORCHESTRATION_ACTION_RESULT_FAILURE",c,void 0,m)));case 4:return n.return(new L5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",c,k?[k]:void 0))}})},a_a=function(a,b){var c,d;
return g.B(function(e){switch(e.j){case 1:return c=F5(b),g.ua(e,2),d=g.VI(b.entityKey).entityId,"!*$_ALL_ENTITIES_!*$"===d?g.A(e,LYa(a.j,b,a.u),5):g.A(e,J5(d,a.j,b,a.u),5);case 5:g.va(e,3);break;case 2:return g.wa(e),e.return(new L5("OFFLINE_ORCHESTRATION_ACTION_RESULT_FAILURE",c,void 0,"OFFLINE_OPERATION_FAILURE_REASON_DATABASE_REQUEST_FAILED"));case 3:return e.return(new L5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",c))}})},XZa=function(a,b,c){var d,e,f,k,l,m;
return g.B(function(n){switch(n.j){case 1:return g.A(n,WZa([b]),2);case 2:return d=n.u,e=d[0],g.A(n,b_a(a,e,c),3);case 3:f=n.u;k=f.videoEntity;l=f.channelEntity;g.ua(n,4);var p=I5(k.thumbnail),q=I5(l.avatar);return g.A(n,GYa(p.concat(q)),6);case 6:g.va(n,0);break;case 4:m=g.wa(n);if(!a.U.L("woffle_disable_thumbnails"))throw m;g.ta(n)}})},b_a=function(a,b,c){var d,e,f,k,l,m,n;
return g.B(function(p){if(1==p.j){if(!(b&&b.channel&&b.channel.offlineChannelData&&b.videoId))throw Error("Invalid OfflineVideoData");c||(c=Date.now().toString());e=null==(d=b.channel)?void 0:d.offlineChannelData;f={id:g.WI(b.videoId,"ytMainChannelEntity"),channelId:e.channelId,title:e.title,avatar:e.thumbnail};k={id:g.WI(b.videoId,"ytMainVideoEntity"),videoId:b.videoId,title:b.title,thumbnail:b.thumbnail,localizedStrings:{viewCount:b.shortViewCountText},lengthSeconds:b.lengthSeconds?Number(b.lengthSeconds):
void 0,publishedTimestampMillis:b.publishedTimestamp?(1E3*Number(b.publishedTimestamp)).toString():void 0,formattedDescription:b.description,channelOwner:f.id};l={id:g.WI(b.videoId,"ytMainDownloadedVideoEntity"),video:k.id,playbackData:g.WI(b.videoId,"playbackData"),offlineVideoPolicy:g.WI(b.videoId,"offlineVideoPolicy"),addedTimestampMillis:c};return a.U.L("woffle_entity_migration")?(m={key:g.WI(b.videoId,"mainVideoDownloadStateEntity"),playbackData:g.WI(b.videoId,"playbackData"),addedTimestampMillis:c},
n={key:g.WI(b.videoId,"mainVideoEntity"),videoId:b.videoId,title:b.title,thumbnail:b.thumbnail,localizedStrings:{viewCount:b.shortViewCountText},lengthSeconds:b.lengthSeconds?Number(b.lengthSeconds):void 0,publishedTimestampMillis:b.publishedTimestamp?(1E3*Number(b.publishedTimestamp)).toString():void 0,formattedDescription:b.description,owner:f.id,downloadState:m.key},g.A(p,m5(a.j,{mode:"readwrite",Jc:!0},function(q){var t=h5(q,f,"ytMainChannelEntity"),v=h5(q,k,"ytMainVideoEntity"),x=h5(q,l,"ytMainDownloadedVideoEntity"),
y=h5(q,m,"mainVideoDownloadStateEntity");q=h5(q,n,"mainVideoEntity");return g.Gs.all([t,v,x,y,q])}),3)):g.A(p,m5(a.j,{mode:"readwrite",
Jc:!0},function(q){var t=h5(q,f,"ytMainChannelEntity"),v=h5(q,k,"ytMainVideoEntity");q=h5(q,l,"ytMainDownloadedVideoEntity");return g.Gs.all([t,v,q])}),3)}return p.return({videoEntity:k,
channelEntity:f,ija:l})})},YZa=function(a,b,c){b=g.WI(b,"playbackData");
c=Object.assign({},c,{priority:1,retryScheduleIntervalsInSeconds:c_a});return{actionType:a,entityKey:b,actionMetadata:c}},j6=function(){g6.apply(this,arguments);
this.J="ytMainDownloadedVideoEntity"},d_a=function(){var a;
return g.B(function(b){return 1==b.j?g.A(b,s5(),2):(a=b.u)?g.A(b,m5(a,{mode:"readwrite",Jc:!0},function(c){var d=f5(c,"ytMainDownloadedVideoEntity"),e=f5(c,"ytMainVideoEntity"),f=f5(c,"mainVideoEntity");return g.Gs.all([d,e,f]).then(function(k){k=g.r(k);var l=k.next().value,m=k.next().value,n=k.next().value;k={};l=g.r(l);for(var p=l.next();!p.done;p=l.next()){p=p.value;var q=g.VI(p.id).entityId;k[q]=p}l={};m=g.r(m);for(p=m.next();!p.done;p=m.next())p=p.value,q=g.VI(p.id).entityId,l[q]=p;m={};n=g.r(n);
for(p=n.next();!p.done;p=n.next())p=p.value,q=g.VI(p.key).entityId,m[q]=p;n=[];p=g.r(Object.keys(k));for(q=p.next();!q.done;q=p.next())if(q=q.value,!m[q]&&l[q]){var t=k[q],v=l[q];t={key:g.WI(q,"mainVideoDownloadStateEntity"),playbackData:g.WI(q,"playbackData"),addedTimestampMillis:t.addedTimestampMillis};q=[{key:g.WI(q,"mainVideoEntity"),videoId:q,title:v.title,thumbnail:v.thumbnail,localizedStrings:v.localizedStrings,lengthSeconds:v.lengthSeconds,publishedTimestampMillis:v.publishedTimestampMillis,
formattedDescription:v.formattedDescription,owner:v.channelOwner,downloadState:t.key},t];n.push(h5(c,q[0],"mainVideoEntity"),h5(c,q[1],"mainVideoDownloadStateEntity"))}return g.Gs.all(n)})}),0):b.return()})},k6=function(){g.CJ.apply(this,arguments)};
g.w(d4,c4);g.w(e4,d4);e4.prototype.Wb=function(){return[]};
g.w(f4,d4);f4.prototype.Wb=function(){var a=[];this.j.alternateChannel&&a.push(this.j.alternateChannel);this.j.alternateChannelList&&a.push.apply(a,g.u(this.j.alternateChannelList));this.j.oneofChannelEntity&&a.push(this.j.oneofChannelEntity);return[].concat(g.u(new Set(a)))};
g.w(g4,d4);g4.prototype.Wb=function(){var a=[];this.j.entryCollection&&a.push(this.j.entryCollection);return[].concat(g.u(new Set(a)))};
g.w(h4,c4);h4.prototype.Wb=function(){var a=[];this.j.video&&a.push(this.j.video);return[].concat(g.u(new Set(a)))};
g.w(i4,d4);i4.prototype.Wb=function(){var a=[];this.j.parentPlaylist&&a.push(this.j.parentPlaylist);if(this.j.entries)for(var b=g.r(this.j.entries),c=b.next();!c.done;c=b.next())a.push.apply(a,g.u((new h4(c.value)).Wb()));return[].concat(g.u(new Set(a)))};
g.w(j4,d4);j4.prototype.Wb=function(){var a=[];this.j.descriptionEntity&&a.push(this.j.descriptionEntity);this.j.creators&&a.push.apply(a,g.u(this.j.creators));this.j.theBiggestFan&&a.push(this.j.theBiggestFan);return[].concat(g.u(new Set(a)))};
g.w(k4,d4);k4.prototype.Wb=function(){return[]};
g.w(l4,d4);l4.prototype.Wb=function(){return[]};
g.w(m4,d4);m4.prototype.Wb=function(){return[]};
g.w(n4,d4);n4.prototype.Wb=function(){return[]};
g.w(o4,d4);o4.prototype.Wb=function(){var a=[];this.j.playbackData&&a.push(this.j.playbackData);this.j.localImageEntities&&a.push.apply(a,g.u(this.j.localImageEntities));return[].concat(g.u(new Set(a)))};
g.w(p4,d4);p4.prototype.Wb=function(){return[]};
g.w(q4,d4);q4.prototype.Wb=function(){var a=[];this.j.fakeChildren&&a.push.apply(a,g.u(this.j.fakeChildren));return[].concat(g.u(new Set(a)))};
g.w(r4,d4);r4.prototype.Wb=function(){var a=[];this.j.video&&a.push(this.j.video);this.j.playbackData&&a.push(this.j.playbackData);this.j.offlineVideoPolicy&&a.push(this.j.offlineVideoPolicy);return[].concat(g.u(new Set(a)))};
g.w(s4,d4);s4.prototype.Wb=function(){var a=[];this.j.channelOwner&&a.push(this.j.channelOwner);this.j.videos&&a.push.apply(a,g.u(this.j.videos));this.j.collaboratorChannels&&a.push.apply(a,g.u(this.j.collaboratorChannels));return[].concat(g.u(new Set(a)))};
g.w(t4,c4);t4.prototype.Wb=function(){var a=[];this.j.playbackPosition&&a.push(this.j.playbackPosition);return[].concat(g.u(new Set(a)))};
g.w(u4,d4);u4.prototype.Wb=function(){var a=[];this.j.owner&&a.push(this.j.owner);this.j.downloadState&&a.push(this.j.downloadState);this.j.userState&&a.push.apply(a,g.u((new t4(this.j.userState)).Wb()));return[].concat(g.u(new Set(a)))};
g.w(v4,d4);v4.prototype.Wb=function(){return[]};
g.w(w4,d4);w4.prototype.Wb=function(){var a=[];this.j.channelOwner&&a.push(this.j.channelOwner);this.j.playbackPosition&&a.push(this.j.playbackPosition);this.j.localImageEntities&&a.push.apply(a,g.u(this.j.localImageEntities));this.j.downloadStatus&&a.push(this.j.downloadStatus);return[].concat(g.u(new Set(a)))};
g.w(x4,d4);x4.prototype.Wb=function(){return[]};
g.w(y4,d4);y4.prototype.Wb=function(){return[]};
g.w(z4,d4);z4.prototype.Wb=function(){var a=[];this.j.trackDownloadMetadatas&&a.push.apply(a,g.u(this.j.trackDownloadMetadatas));return[].concat(g.u(new Set(a)))};
g.w(A4,d4);A4.prototype.Wb=function(){var a=[];this.j.playbackData&&a.push(this.j.playbackData);this.j.localImageEntities&&a.push.apply(a,g.u(this.j.localImageEntities));return[].concat(g.u(new Set(a)))};
g.w(B4,d4);B4.prototype.Wb=function(){var a=[];this.j.musicLibraryStatusEntity&&a.push(this.j.musicLibraryStatusEntity);this.j.primaryArtists&&a.push.apply(a,g.u(this.j.primaryArtists));this.j.details&&a.push(this.j.details);this.j.userDetails&&a.push(this.j.userDetails);this.j.tracks&&a.push.apply(a,g.u(this.j.tracks));this.j.share&&a.push(this.j.share);this.j.downloadMetadata&&a.push(this.j.downloadMetadata);return[].concat(g.u(new Set(a)))};
g.w(C4,d4);C4.prototype.Wb=function(){var a=[];this.j.albumRelease&&a.push(this.j.albumRelease);this.j.tracks&&a.push.apply(a,g.u(this.j.tracks));return[].concat(g.u(new Set(a)))};
g.w(D4,d4);D4.prototype.Wb=function(){var a=[];this.j.albumRelease&&a.push(this.j.albumRelease);return[].concat(g.u(new Set(a)))};
g.w(E4,d4);E4.prototype.Wb=function(){var a=[];this.j.details&&a.push(this.j.details);this.j.userDetails&&a.push(this.j.userDetails);return[].concat(g.u(new Set(a)))};
g.w(F4,d4);F4.prototype.Wb=function(){var a=[];this.j.parentArtist&&a.push(this.j.parentArtist);return[].concat(g.u(new Set(a)))};
g.w(G4,d4);G4.prototype.Wb=function(){var a=[];this.j.parentArtist&&a.push(this.j.parentArtist);return[].concat(g.u(new Set(a)))};
g.w(H4,d4);H4.prototype.Wb=function(){return[]};
g.w(I4,d4);I4.prototype.Wb=function(){return[]};
g.w(J4,d4);J4.prototype.Wb=function(){return[]};
g.w(K4,d4);
K4.prototype.Wb=function(){var a=[];this.j.musicLibraryStatusEntity&&a.push(this.j.musicLibraryStatusEntity);this.j.artists&&a.push.apply(a,g.u(this.j.artists));this.j.audioModeVersion&&a.push(this.j.audioModeVersion);this.j.videoModeVersion&&a.push(this.j.videoModeVersion);this.j.userDetails&&a.push(this.j.userDetails);this.j.details&&a.push(this.j.details);this.j.albumRelease&&a.push(this.j.albumRelease);this.j.share&&a.push(this.j.share);this.j.libraryEdit&&a.push(this.j.libraryEdit);this.j.downloadMetadata&&
a.push(this.j.downloadMetadata);return[].concat(g.u(new Set(a)))};
g.w(L4,d4);L4.prototype.Wb=function(){var a=[];this.j.parentTrack&&a.push(this.j.parentTrack);return[].concat(g.u(new Set(a)))};
g.w(M4,d4);M4.prototype.Wb=function(){var a=[];this.j.parentTrack&&a.push(this.j.parentTrack);return[].concat(g.u(new Set(a)))};
g.w(N4,d4);N4.prototype.Wb=function(){return[]};
g.w(O4,d4);O4.prototype.Wb=function(){return[]};
g.w(P4,d4);P4.prototype.Wb=function(){return[]};
g.w(Q4,d4);Q4.prototype.Wb=function(){return[]};
g.w(R4,d4);R4.prototype.Wb=function(){var a=[];this.j.transfer&&a.push(this.j.transfer);this.j.adsPlaybackData&&a.push.apply(a,g.u(this.j.adsPlaybackData));this.j.drmLicense&&a.push(this.j.drmLicense);this.j.offlineVideoPolicy&&a.push(this.j.offlineVideoPolicy);return[].concat(g.u(new Set(a)))};
g.w(S4,d4);S4.prototype.Wb=function(){var a=[];this.j.offlineVideoStreams&&a.push.apply(a,g.u(this.j.offlineVideoStreams));this.j.captionTrack&&a.push.apply(a,g.u(this.j.captionTrack));return[].concat(g.u(new Set(a)))};
g.w(T4,d4);T4.prototype.Wb=function(){return[]};
g.w(U4,d4);U4.prototype.Wb=function(){return[]};
g.w(V4,d4);V4.prototype.Wb=function(){return[]};
g.w(W4,d4);W4.prototype.Wb=function(){return[]};
g.w(X4,d4);X4.prototype.Wb=function(){return[]};
var VZa=["offline"],RYa=["offline/get_playback_data_entity"],e_a={Q2:"captionTrack",E6:"ytMainDownloadedVideoEntity",F6:"ytMainVideoEntity",u$:"ytMainChannelEntity",v$:"mainPlaylistEntity",w$:"mainVideoEntity",x$:"mainVideoDownloadStateEntity",Iba:"musicAlbumReleaseDetail",Jba:"musicAlbumReleaseDownloadMetadataEntity",Kba:"musicAlbumRelease",Lba:"musicAlbumReleaseUserDetail",Mba:"musicArtistDetail",Nba:"musicArtist",Pba:"musicArtistUserDetail",Yba:"musicLibraryEdit",Zba:"musicLibraryStatusEntity",
jca:"musicShare",oca:"musicTrackDetail",pca:"musicTrackDownloadMetadataEntity",qca:"musicTrack",rca:"musicTrackUserDetail",Jca:"offlineOrchestrationActionWrapperEntity",Tca:"offlineVideoPolicy",Uca:"offlineVideoStreams",Gda:"playbackData",Hea:"orchestrationWebSamplingEntity",Gga:"transfer"};g.w(Z4,g.us);g.w(a5,SXa);a5.prototype.B=function(a,b){b=$4(b);a=(new TextEncoder).encode(JSON.stringify(a));return this.j.encrypt(a,b)};
a5.prototype.u=function(a,b){if(!(a instanceof Uint8Array))throw OXa(1);var c=new TextDecoder;b=$4(b);a=this.j.decrypt(a,b);return JSON.parse(c.decode(a))};
g.w(b5,SXa);b5.prototype.B=function(a){return a};
b5.prototype.u=function(a){if(a instanceof Uint8Array)throw OXa(0);return a};
var WXa={buttonEntity:T4,captionTrack:N4,channelHandle:e4,commerceCartListEntity:V4,downloadQualityPickerEntity:n4,fakeChannel:f4,fakePlaylist:g4,fakePlaylistEntryCollection:i4,fakeVideo:j4,fakeVideoDescription:k4,iconBadgeEntity:W4,liveChatPollStateEntity:m4,logoEntity:l4,mainPlaylistEntity:s4,mainVideoDownloadStateEntity:o4,mainVideoEntity:u4,markersVisibilityOverrideEntity:x4,musicAlbumReleaseDetail:C4,musicAlbumReleaseDownloadMetadataEntity:z4,musicAlbumRelease:B4,musicAlbumReleaseUserDetail:D4,
musicArtistDetail:F4,musicArtist:E4,musicArtistUserDetail:G4,musicLibraryEdit:H4,musicLibraryStatusEntity:I4,musicShare:J4,musicTrackDetail:L4,musicTrackDownloadMetadataEntity:A4,musicTrack:K4,musicTrackUserDetail:M4,offlineOrchestrationActionWrapperEntity:O4,offlineVideoPolicy:P4,offlineVideoStreams:Q4,offlineabilityEntity:p4,orchestrationWebSamplingEntity:q4,pinnedProductEntity:y4,playbackData:R4,quantityIncrementerEntity:X4,transfer:S4,videoPlaybackPositionEntity:U4,ytMainChannelEntity:v4,ytMainDownloadedVideoEntity:r4,
ytMainVideoEntity:w4},d5;g.w(l5,g.G);l5.prototype.B=function(a){iYa(this,a.data)};
l5.prototype.ea=function(){this.channel.close()};
var r5;g.w(u5,g.G);u5.prototype.B=function(a){this.api.La("onOfflineOperationFailure",a.data)};
u5.prototype.C=function(a){this.api.X("offlinetransferpause",a.data)};
u5.prototype.ea=function(){var a;null==(a=this.j)||a.close();var b;null==(b=this.u)||b.close()};sYa.prototype.request=function(a,b,c){b=void 0===b?{}:b;return this.locks.request(a,b,function(d){return c(d)})};vYa.prototype.rf=function(){this.j&&w5(this)};var C5=g.C.caches,B5,D5;y5.prototype.open=function(a){return C5.open(A5(a))};
y5.prototype.has=function(a){return C5.has(A5(a))};
y5.prototype.delete=function(a){return C5.delete(A5(a))};
y5.prototype.match=function(a,b){var c=this,d,e,f,k,l,m;return g.B(function(n){switch(n.j){case 1:return g.A(n,c.keys(),2);case 2:d=n.u,e=g.r(d),f=e.next();case 3:if(f.done){n.Sa(5);break}k=f.value;return g.A(n,c.open(k),6);case 6:return l=n.u,g.A(n,l.match(a,b),7);case 7:if(m=n.u)return n.return(m);f=e.next();n.Sa(3);break;case 5:return n.return()}})};
g.w(z5,y5);z5.prototype.keys=function(){var a,b,c,d,e,f,k,l,m;return g.B(function(n){if(1==n.j)return a=[],b=g.vs("CacheStorage keys"),g.A(n,C5.keys(),2);c=n.u;d=g.r(c);for(e=d.next();!e.done;e=d.next()){f=e.value;var p=f.indexOf(":");k=-1===p?{BC:f}:{BC:f.substring(0,p),datasyncId:f.substring(p+1)};l=k.BC;m=k.datasyncId;m===b&&a.push(l)}return n.return(a)})};Object.keys(e_a).map(function(a){return e_a[a]});
var KYa="captionTrack ytMainDownloadedVideoEntity ytMainVideoEntity ytMainChannelEntity mainVideoEntity mainVideoDownloadStateEntity offlineVideoPolicy offlineVideoStreams playbackData transfer".split(" ");g.w(M5,K5);M5.prototype.B=function(a){return G5(a)?PYa(this,a):H5(a)?QYa(this,a):Promise.reject(Error("Unsupported action type: "+a.actionType))};g.w(O5,K5);O5.prototype.B=function(a){return G5(a)?TYa(this,a):H5(a)?UYa(this,a):"OFFLINE_ORCHESTRATION_ACTION_TYPE_UPDATE"===a.actionType&&a.entityKey?this.handleUpdate(a):Promise.reject(Error("Unsupported action type: "+a.actionType))};
O5.prototype.handleUpdate=function(a){var b=this,c,d,e;return g.B(function(f){switch(f.j){case 1:return c=F5(a),g.A(f,p5(b.j,a.entityKey,"transfer"),2);case 2:d=f.u;if(!d||"TRANSFER_STATE_WAITING_FOR_PLAYER_RESPONSE_REFRESH"!==d.transferState)return f.return(new L5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",c));g.ua(f,3);d.transferState="TRANSFER_STATE_TRANSFER_IN_QUEUE";return g.A(f,o5(b.j,d,"transfer"),5);case 5:e=g.VI(d.key).entityId;x5({transferStatusType:"TRANSFER_STATUS_TYPE_REENQUEUED_BY_PLAYER_RESPONSE_REFRESH",
statusType:"ADDED_TO_QUEUE"},{videoId:e,ej:d});g.va(f,4);break;case 3:return g.wa(f),f.return(new L5("OFFLINE_ORCHESTRATION_ACTION_RESULT_FAILURE",c,void 0,"OFFLINE_OPERATION_FAILURE_REASON_DATABASE_REQUEST_FAILED"));case 4:return f.return(new L5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",c))}})};var jZa=["OFFLINE_ORCHESTRATION_ACTION_TYPE_ADD","OFFLINE_ORCHESTRATION_ACTION_TYPE_REFRESH"];var R5;bZa.prototype.j=function(a,b){var c=a.action.actionMetadata.priority-b.action.actionMetadata.priority;0===c&&(a.j<b.j?c=-1:a.j>b.j&&(c=1));return c};g.w(U5,g.G);U5.prototype.ea=function(){this.J&&this.J();g.G.prototype.ea.call(this)};
U5.prototype.createAction=function(a,b){var c=g.VI(a.entityKey).entityType,d=g.Av(16);return new P5(c,d,a,b.actionId,b.rootActionId)};
U5.prototype.W=function(a){var b=this,c,d,e,f,k,l,m,n,p;return g.B(function(q){if(1==q.j){if(b.isDisposed())return q.return();d=null!=(c=a.offlineOrchestrationActionWrapperEntity)?c:new Set;e=[];f=g.r(d);for(k=f.next();!k.done;k=f.next())l=k.value,m=g.VI(l),n=m.entityId,dZa(b.j,n)||e.push(l);return g.A(q,lZa(b,e),2)}p=q.u;return g.A(q,W5(b,p),0)})};
U5.prototype.retry=function(){var a=this;return g.B(function(b){return g.A(b,mZa(a),0)})};g.h=sZa.prototype;
g.h.lY=function(a){var b=this,c,d,e,f;return g.B(function(k){if(!g.V(a.state,128))return k.Sa(0);var l=null==(c=a.state.getData())?void 0:c.errorCode,m=null==(d=a.state.getData())?void 0:d.zI,n=null==(e=a.state.getData())?void 0:e.YA;f=b.L("html5_eliminate_net_retryexhausted_error")&&"net.connect"===l&&1===n||"net.retryexhausted"===l&&(null==m?0:m.includes("net.connect"))?"TRANSFER_FAILURE_REASON_NETWORK_LOST":(null==l?0:l.startsWith("net."))?"TRANSFER_FAILURE_REASON_NETWORK":"TRANSFER_FAILURE_REASON_INTERNAL";return g.A(k,
b.Zr(b.player.getVideoData().videoId,f),0)})};
g.h.Zr=function(a,b){var c=this;return g.B(function(d){if(1==d.j){if(c.u)return d.return();c.u=!0;return"TRANSFER_FAILURE_REASON_NETWORK_LOST"===b?(Y5(c,a,!1,!0),d.Sa(0)):g.A(d,X5(c,a),3)}g.eD(a,4);return g.A(d,c.j.Zr(b),0)})};
g.h.tC=function(a){2===a.status?(a.status!==this.B&&(c6(this.j),g.eD(a.videoId,2)),a.bz&&NZa(this.j,a.videoId,a.bz)):4===a.status?(X5(this,a.videoId),this.Zr(a.videoId,a.IB?"TRANSFER_FAILURE_REASON_FILESYSTEM_WRITE":"TRANSFER_FAILURE_REASON_INTERNAL")):1===a.status&&LZa(this.j);this.B=a.status;this.api.La("localmediachange",{videoId:a.videoId,status:a.status})};
g.h.YH=function(){var a=this,b;return g.B(function(c){if(1==c.j){if(a.u)return c.return();a.u=!0;b=a.player.getVideoData().videoId;return g.A(c,X5(a,b),2)}return g.A(c,a.j.YH(),0)})};
g.h.L=function(a){return this.api.S().L(a)};g.w(Z5,g.G);Z5.prototype.ea=function(){this.u&&this.u();g.G.prototype.ea.call(this)};
Z5.prototype.B=function(a){var b=this,c,d,e,f,k,l,m,n;return g.B(function(p){d=null!=(c=a.transfer)?c:new Set;e=[];f=g.r(d);for(k=f.next();!k.done;k=f.next())l=k.value,m=g.VI(l),n=m.entityId,e.push(n);return 0===e.length?p.return():g.A(p,zZa(b,e),0)})};g.w($5,g.G);g.h=$5.prototype;g.h.ea=function(){this.J&&this.J();this.N.dispose();this.C.dispose();this.Y&&g.ag(this.D.B,this.Y);this.W&&g.ag(this.D.B,this.W);g.G.prototype.ea.call(this)};
g.h.u_=function(a){var b=this,c,d;return g.B(function(e){if(1==e.j)return c=g.WI(a,"transfer"),b.j&&c===b.j.key?(Y5(b.I,b.B,!0),b.C.stop(),e.Sa(0)):g.A(e,m5(b.u,{mode:"readwrite",Jc:!0},function(f){return e5(f,c,"transfer").then(function(k){if(k&&"TRANSFER_STATE_COMPLETE"!==k.transferState&&"TRANSFER_STATE_FAILED"!==k.transferState)return k.transferState="TRANSFER_STATE_PAUSED_BY_USER",h5(f,k,"transfer").then(function(){return k})})}),3);
(d=e.u)&&BYa({videoId:a,ej:d});g.ta(e)})};
g.h.t_=function(){this.j&&this.B&&Y5(this.I,this.B,!1);this.C.stop()};
g.h.oz=function(){this.j?FZa(this,this.j):b6(this)};
g.h.sU=function(a){var b=this,c;return g.B(function(d){switch(d.j){case 1:if(!b.j){d.Sa(2);break}if("TRANSFER_STATE_COMPLETE"===b.j.transferState||"TRANSFER_STATE_FAILED"===b.j.transferState||!a.transfer||!a.transfer.has(b.j.key)){d.Sa(3);break}c=b;return g.A(d,p5(b.u,b.j.key,"transfer"),4);case 4:c.j=d.u;if(b.j){d.Sa(3);break}return g.A(d,GZa(b),3);case 3:if(b.j)return d.return();case 2:return g.A(d,b6(b),0)}})};
g.h.Zr=function(a,b){var c=this,d,e;return g.B(function(f){if(1==f.j){a:switch(a){case "TRANSFER_FAILURE_REASON_FILESYSTEM_WRITE":case "TRANSFER_FAILURE_REASON_EXTERNAL_FILESYSTEM_WRITE":case "TRANSFER_FAILURE_REASON_PLAYABILITY":case "TRANSFER_FAILURE_REASON_TOO_MANY_RETRIES":var k=!1;break a;default:k=!0}return k&&OZa(c)?g.A(f,e6(c,"TRANSFER_STATE_TRANSFER_IN_QUEUE"),5):g.A(f,PZa(c,a),3)}3!=f.j&&(d=g.VI(c.j.key).entityId,x5({transferStatusType:"TRANSFER_STATUS_TYPE_REENQUEUED_BY_RETRY",statusType:"ADDED_TO_QUEUE"},
{videoId:d,ej:c.j}));a6(c);e=b6(c,!0);b&&b(e);g.ta(f)})};
g.h.YH=function(a){var b=this,c,d,e,f,k,l;return g.B(function(m){if(1==m.j)return OZa(b)?g.A(m,e6(b,"TRANSFER_STATE_WAITING_FOR_PLAYER_RESPONSE_REFRESH"),5):g.A(m,PZa(b,"TRANSFER_FAILURE_REASON_STREAM_MISSING"),3);if(3!=m.j)return c=g.VI(b.j.key).entityId,x5({transferStatusType:"TRANSFER_STATUS_TYPE_DEQUEUED_BY_PLAYER_RESPONSE_EXPIRATION",statusType:"ADDED_TO_QUEUE"},{videoId:c,ej:b.j}),d=WYa(),d.playbackDataActionMetadata={isEnqueuedForExpiredStreamUrlRefetch:!0},e=g.WI(c,"playbackData"),f={actionType:"OFFLINE_ORCHESTRATION_ACTION_TYPE_ADD",
entityKey:e,actionMetadata:d},k=Q5(new P5("playbackData",c,f)),g.A(m,o5(b.u,k,"offlineOrchestrationActionWrapperEntity"),3);a6(b);l=b6(b,!0);a&&a(l);g.ta(m)})};
var l6={},f6=(l6.TRANSFER_STATE_TRANSFERRING=1,l6.TRANSFER_STATE_TRANSFER_IN_QUEUE=2,l6);g.h=g6.prototype;g.h.jG=function(a){var b={};return b.playbackData=new M5(a,this.U,this.B),b.transfer=new O5(a),b};
g.h.OI=function(){var a=this;return g.B(function(b){return a.j?g.A(b,DZa(a.j),0):b.Sa(0)})};
g.h.isOrchestrationLeader=function(){return this.u.j};
g.h.nI=function(a){var b=this.B;b.api.X("offlinetransferpause",a);var c;null==(c=b.u)||c.postMessage(a)};
g.h.oz=function(a){var b,c;return g.B(function(d){if(1==d.j)return g.A(d,s5(),2);b=d.u;if(!b)return d.return();c=g.WI(a,"transfer");return g.A(d,m5(b,{mode:"readwrite",Jc:!0},function(e){return e5(e,c,"transfer").then(function(f){return f&&"TRANSFER_STATE_PAUSED_BY_USER"===f.transferState?(f.transferState="TRANSFER_STATE_TRANSFER_IN_QUEUE",h5(e,f,"transfer").then(function(){x5({transferStatusType:"TRANSFER_STATUS_TYPE_REENQUEUED_BY_USER_RESUME",statusType:"USER_RESUMED"},{videoId:a,ej:f});return g.Gs.resolve(null)})):
g.Gs.resolve(null)})}),0)})};
g.h.kz=function(a){a=void 0===a?43200:a;var b=this,c,d,e,f,k,l,m,n;return g.B(function(p){if(1==p.j)return b.N.qf()?g.A(p,s5(),2):p.return(UZa());if(3!=p.j){c=p.u;if(!c)return p.return([]);d=Date.now()/1E3;return g.A(p,q5(c,"offlineVideoPolicy"),3)}e=p.u;f=[];k=g.r(e);for(l=k.next();!l.done;l=k.next())m=l.value,Number(m.lastUpdatedTimestampSeconds)+a<=d&&(n=g.VI(m.key).entityId,f.push(n));return f.length?p.return(h6(b,f,b.J,"OFFLINE_ORCHESTRATION_ACTION_TYPE_REFRESH")):p.return([])})};
g.h.deleteAll=function(){return h6(this,["!*$_ALL_ENTITIES_!*$"],this.J,"OFFLINE_ORCHESTRATION_ACTION_TYPE_DELETE")};g.w(i6,K5);i6.prototype.B=function(a){return G5(a)?ZZa(this,a):H5(a)?$Za(this,a):"OFFLINE_ORCHESTRATION_ACTION_TYPE_DELETE"===a.actionType&&a.entityKey?a_a(this,a):Promise.reject(Error("Unsupported action type: "+a.actionType))};
var c_a=[10];g.w(j6,g6);j6.prototype.jG=function(a){var b=g6.prototype.jG.call(this,a);b.ytMainDownloadedVideoEntity=new i6(a,this.U,this.B);return b};
j6.prototype.OI=function(){var a=this;return g.B(function(b){return 1==b.j?g.A(b,g6.prototype.OI.call(a),2):a.U.L("woffle_entity_migration")?g.A(b,d_a(),0):b.Sa(0)})};g.w(k6,g.CJ);g.h=k6.prototype;g.h.create=function(){var a=this.player.S();g.xC(a)&&(this.j=new j6(a,this.player))};
g.h.aj=function(){return!1};
g.h.AI=function(a,b,c,d){var e=this;return g.B(function(f){return e.j?f.return(h6(e.j,a,b,c,d)):f.return(Promise.reject())})};
g.h.deleteAll=function(){return this.j.deleteAll()};
g.h.kz=function(a){return this.j.kz(a)};
g.h.nI=function(a){this.j.nI(a)};
g.h.oz=function(a){return this.j.oz(a)};
g.h.isOrchestrationLeader=function(){return this.j.isOrchestrationLeader()};g.BJ("offline",k6);})(_yt_player);
